### ISSUE TITLE
ClassCastException when casting a value retrieved from a Python list

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-core#1009]
When creating a table using `emptyTable`, we want the resulting X column to be an int column. We've tried a few variations of queries, but either it executes and the column does NOT become an int column (verified w/ `getMeta`), or we get an exception.

Jianfeng tried the following: 

```
from deephaven.TableTools import emptyTable
empty = emptyTable(5)
a = [1, 2, 3, 4, 10]
result2 = empty.update("X = (int)a[ (int) i ]")
```
I tried casting it to int and got this exception

```
caused by java.lang.ClassCastException: org.jpy.PyObject cannot be cast to java.lang.Integer
	at io.deephaven.db.tables.lang.DBLanguageFunctionUtil.intCast(DBLanguageFunctionUtil.java:18609)
	at io.deephaven.temp.cm302811563987228486v52_0.Formula.applyFormulaPerItem(Formula.java:177)
	... 33 more
```

**Comment by chipkent** [comment]
I'm looking at the key AI code.  It is in Scatterer at https://github.com/deephaven/deephaven-core/blob/2bd974818ab054230ddc35676a0cca7941fe4ffb/Integrations/src/main/java/io/deephaven/integrations/learn/Scatterer.java#L46.  

The AI code is simply trying to create a query string to cast values.  The java array solution does not work.  For dynamic cases, the static array just doesn't work.  The `.getIntValue()` solution could work for a subset of types.  I would play with that case first to see if it can be made to work as a stopgap.

**Comment by chipkent** [comment]
Ugh... I tried an alternative solution:

```
from deephaven.TableTools import emptyTable

def extract(a,i):
    return a[i].intValue()

result = emptyTable(5).update("X = extract(a,i))"
```
This looks like a reasonable workaround for the various failures here.  Unfortunately, this triggers yet another problem.  I get an error about `a` not being subscriptable and being of type `org.jpy.PyListWrapper`.  The query language is clearly falling down all over the place.  @jmao-denver this may need to be another ticket.
