### ISSUE TITLE
Support console autocomplete in gRPC

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#101]
The rpc methods and payloads are stubbed in, but the server implementation is just TODOs.

**Comment by JamesXNelson** [comment]
@mofojed 
Should I open separate sub-issues for particular problems I've had along the way?  Or try to keep it `1 issue:1 merge`?

**Comment by mofojed** [comment]
@JamesXNelson yes separate sub-issues please, if the merges can be broken down as well even better (smaller reviews)

**Comment by JamesXNelson** [comment]
@mofojed I dunno how to explicity mark things as sub-issues, so I just linked back to the ticket for paper-trail purposes.

**Comment by JamesXNelson** [comment]
We've merged enough individual pieces to consider this epic closed.
