### ISSUE TITLE
JS API Table snapshot should support specific rows, columns

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#1039]
Without this, we will either need to modify how the JS UI handles CSV download of very large tables, or will need to find another way to slice up content, like with head/tail calls before requesting a snapshot.

DoGet does not support extra metadata, so we can't just attach a custom barrage object with an index for rows and a bitset for columns.

**Comment by nbauernfeind** [comment]
It would also be reasonable (and desirable) to support a filterable DoGet over DoExchange. See #925.

**Comment by nbauernfeind** [comment]
Head and Tail is probably not enough. The selected rows do not need to be contiguous; if you break this up into one DoGet per contiguous range then you still can't get a consistent snapshot on a ticking table.

**Comment by nbauernfeind** [comment]
Also, one parameter I want to add to the "DoGet over DoExchange" is the ability to control chunk size. Since DoGet/DoExchange are modeled as a stream of record batches, it becomes very easy to respect a user requested batch size.

**Comment by niloc132** [comment]
This is also the issue behind input table delete row deleting all rows.
