### ISSUE TITLE
Kafka: Handle DBDateTime from Avro Generic Records

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#1045]
As a user, I want to import data that has dates and see them as DBDateTimes so that I can easily manipulate them.

Part of #293

**Comment by jcferretti** [comment]
Done: https://github.com/deephaven/deephaven-core/blob/33a930ff9b2b9183e1f40fa36b1cc6319af5f9e0/Kafka/src/main/java/io/deephaven/kafka/KafkaTools.java#L188
