### ISSUE TITLE
Automate the code generation, building, and testing for the new Python client

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#1073]
Currently, the package name used to generate Python code from DH proto definitions is 'deephaven', that needs to be changed to 'pydeephaven' which is the package name for the new Python client. And it should be made part of the full gradle integration which includes auto building and testing of the Python client.

**Comment by niloc132** [comment]
`python setup.py bdist_wheel` to create the wheel

`python setup.py bdist_wheel` with `DHCE_HOST` and `DHCE_PORT` env vars set to point to the grpc-api instance

**Comment by jmao-denver** [comment]
@devinrsmith made some breaking changes to DH PB messages and needed to regen the Python code for the client and rename the 'deephaven' namespace to 'pydeephaven'.  We have come up with the following commands to automate the process. It may be possible to integrate the two sed commands into the generateProtobuf task.

```
./gradlew proto:proto-backplane-grpc:generateProtobuf
sed -i "s/: 'deephaven.proto./: 'pydeephaven.proto./g" ./proto/proto-backplane-grpc/build/generated/source/proto/main/python/deephaven/proto/*_pb*.py
sed -i "s/from deephaven.proto/from pydeephaven.proto/g" ./proto/proto-backplane-grpc/build/generated/source/proto/main/python/deephaven/proto/*_pb*.py
cp ./proto/proto-backplane-grpc/build/generated/source/proto/main/python/deephaven/proto/*_pb*.py ./pyclient/pydeephaven/proto/
```

**Comment by devinrsmith** [comment]
I can't verify the above actually works, b/c things are breaking.

Sucks about the manually hacking. Looks like it's been a long outstanding proto request: https://github.com/protocolbuffers/protobuf/issues/7061
