### ISSUE TITLE
Python not matching by aggregation with lists

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1101]
Jpy method matching does not work in this case when provided with a python list. It should match

`Table.by(Collection<? extends Selectable> groupByColumns, Collection<? extends Aggregation> aggregations)`

```python
from deephaven import TableTools
import jpy

ColumnName = jpy.get_type('io.deephaven.api.ColumnName').of
AggMax = jpy.get_type('io.deephaven.api.agg.Aggregation').AggMax
AsList = jpy.get_type('java.util.Arrays').asList

works = TableTools.timeTable("00:00:01")\
    .updateView("I=i%4")\
    .by(AsList(ColumnName("I")), AsList(AggMax("Max=Timestamp")))

broken = TableTools.timeTable("00:00:01")\
    .updateView("I=i%4")\
    .by([ ColumnName("I") ], [ AggMax("Max=Timestamp") ])
```

```
Value: no matching Java method overloads found
```

**Comment by devinrsmith** [comment]
Note: we could fix this natively at the jpy layer, or at the Table wrapper layer.

**Comment by jmao-denver** [comment]
his fails earlier than #1102, possibly related to the generics used in the method signature, but need to debug the code to find out exactly why JPY failed to match a overload method, so far the quick code study hasn't been sufficient for a confident diagnosis.
