### ISSUE TITLE
ParquetTools.writeTable does not throw an error if file path is incorrect

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#1113]
**Description**

Using the `ParquetTools.writeTable` function does not work if you do not include the full path (eg. `grades.parquet` instead of `/path/grades.parquet`)

**Steps to reproduce**
1. Open up a Python session
2. Run this following snippet to create a table
```
from deephaven.TableTools import newTable, intCol, doubleCol, stringCol
grades = newTable(    stringCol("Name", "Ashley", "Jeff", "Rita", "Zach"),    intCol("Test1", 92, 78, 87, 74),    intCol("Test2", 94, 88, 81, 70),    intCol("Average", 93, 83, 84, 72),    doubleCol("GPA", 3.9, 2.9, 3.0, 1.8))
```
3. Try and write the table to a parquet file by just specifying the name of the file:
```
from deephaven.ParquetTools import writeTable

writeTable(grades, "grades.parquet")
```

**Expected results**
3. The table writes to the data directory OR it throws and an error is shown

**Actual results**
3. The command appears to execute successfully, but there is no file in the data directory.

It also doesn't work if you specify `/grades.parquet`, it seems you have to specify `/data/grades.parquet`. Why do we require users to prefix with `/data/` anyway? I would think just specifying `grades.parquet` should write in the default folder. 

**Versions**
 - OS: Mac OS
 - Browser: Chrome

**Comment by rcaudy** [comment]
It sounds like this issue is really about where $PWD is. It's certainly not a Parquet issue.

**Comment by malhotrashivam** [comment]
I verified the above on docker and my local setup.
When I run the core app locally using `./gradlew server-jetty-app:run`, and run the following commands,

```
import os
from deephaven import empty_table
from deephaven.parquet import write

dh_table = empty_table(5).update(formulas=[
    "someCharColumn = (char)i",
])

write(dh_table, "data_from_dh.parquet")
print('Get current working directory : ', os.getcwd())
print(os.listdir(os.curdir))
```
a new file gets created in the `server/jetty-app` directory.

When I run the app in a container using `docker run --rm -p 10000:10000 ghcr.io/deephaven/server:0.26.1` and run the same commands as above, the  file gets created in the root(/) of the container.

So like Ryan said, the file gets written to the $PWD of the app and not a parquet issue.
