### ISSUE TITLE
Automate the process of uploading DH python client to PYPI

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#1180]
The MVP release of DH Python client includes publishing it on PYPI. The process, however, is all manual.

tools required: 
```
    pip install twine
```
```
1. update the versions in both setup.py and pydeephaven/__init__.py
2. update the manual installation instruction in README.md to use the wheel fie with the updated version in the name
at shell: 
$. python setup.py bdist_wheel
$. twine check dist/* 
$. twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username:
Enter your password:
```

**Comment by devinrsmith** [comment]
I've started automating release processes for python projects that are not part of deephaven-core, namely deephaven-plugin and deephaven-plugin-matplotlib.

See
* https://github.com/deephaven/deephaven-plugin/commit/786d7ac1d353249e0b0c0109cca5a4a18d46593e
* https://github.com/deephaven/deephaven-plugin-matplotlib/pull/2

deephaven-plugin repo is setup with a PYPI_TOKEN secret just for the deephaven-plugin package.
deephaven-plugin-matplotlib repo is setup with a PYPI_TOKEN secret just for the deephaven-plugin-matplotlib package.

I also went ahead and setup deephaven-core repo with a PYDEEPHAVEN_PYPI_TOKEN secret just for the pydeephaven package.

deephaven-core can likely use https://github.com/pypa/gh-action-pypi-publish as the above repos do, but will likely need to explicitly set the `dist/` directory.
