### ISSUE TITLE
 readHeaderlessCsv() seems to make a bad parsing decision when parsing a time offset

### ISSUE THREAD

**Issue by mikeblas** [deephaven/deephaven-core#1222]
**Description**

**Steps to reproduce**
I have this data (which is attached as example.csv):

```
"2021-09-03","04:15:00.558"
"2021-09-03","04:15:00.558"
"2021-09-03","04:15:02.663"
"2021-09-03","04:15:03.166"
"2021-09-03","04:15:03.166"
"2021-09-03","04:15:06.332"
"2021-09-03","04:15:06.342"
"2021-09-03","04:15:06.342"
"2021-09-03","04:15:06.366"
"2021-09-03","04:15:06.436"
"2021-09-03","04:15:06.542"
"2021-09-03","04:15:08.338"
"2021-09-03","04:15:08.373"
"2021-09-03","04:15:08.378"
"2021-09-03","04:15:08.385"
"2021-09-03","04:15:08.393"
"2021-09-03","04:15:08.396"
"2021-09-03","04:15:08.681"
"2021-09-03","04:15:08.681"
"2021-09-03","04:15:08.682"
```

	
I can try to import that data with `readHeaderlessCsv()` :

```
from deephaven.TableTools import readHeaderlessCsv
x = readHeaderlessCsv("/data/example.csv")
```

**Expected results**

I'd like to add the offset in the second column to the date in the first column to have an absolute time of day (with a date). But I can't do so, since this number is now unusable and missing information that used to be in the column.

**Actual results**
The data in the second column is parsed into a really large number, as a `long` type:

![image](https://user-images.githubusercontent.com/6632219/132553575-5e7c4d40-ff14-4f2c-be5d-7180c5291b5b.png)

**Additional details and attachments**

[example.csv](https://github.com/deephaven/deephaven-core/files/7130632/example.csv)

**Versions**
 - Deephaven: Version 0.3.1
 - OS: Ubuntu 20 LTS
 - Browser:  Chrome
 - Docker: `Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.1`

**Comment by nbauernfeind** [comment]
Linking to #654.
