### ISSUE TITLE
Newly appended nulls show up as 0.0

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1224]
Noticed a column of 0.0s showing up that were supposed to be nulls. They "fixed" themselves after re-sorting. But then newly appended values were continuing to show up as 0.0. This example shows it caught in the act, w/ the bidSize and askSize exhibiting the behavior.

To reproduce use this query:
```groovy
x = timeTable("00:00:01").update("D = (Double)null")
```

![Screenshot from 2021-09-08 11-28-07](https://user-images.githubusercontent.com/6764691/132565354-ed6f6282-c987-49cf-99ec-e2097eea2ada.png)

**Comment by devinrsmith** [comment]
TODO: create instructions to reproduce.

**Comment by rcaudy** [comment]
Presumably we have a bug in formatting code for deltas only?
