### ISSUE TITLE
Python Issues with pre-defined constants

### ISSUE THREAD

**Issue by AlSpinks** [deephaven/deephaven-core#1247]
**Description**
There is an issue with using predefined constants. For example, we can't use HOUR in formulas.

```
from deephaven.TableTools import newTable, stringCol, dateTimeCol
from deephaven.DBTimeUtils import *

time1 = convertDateTime("2020-04-01T09:00:00 NY")
time2 = convertDateTime("2020-04-01T10:28:32 NY")
time3 = convertDateTime("2020-04-01T12:00:00 NY")
time4 = convertDateTime("2020-04-01T16:59:59 NY")

events = ttools.newTable(
   dateTimeCol("EventDateTime", time1, time2, time3, time4),
   stringCol("Level", "Info", "Error", "Warning", "Info"),
   stringCol("Event", "System starting", "Something bad happened", "Invalid login", "System stopping"),
)

baseTime = convertDateTime("2020-04-01T10:00:00 NY")
eventsMiddleDay3 = events.where("EventDateTime >= baseTime && EventDateTime <= baseTime + HOUR")
Exception indicates it's having trouble on the formula:
io.deephaven.db.v2.select.FormulaCompilationException: Formula compilation error for: EventDateTime >= baseTime && EventDateTime <= baseTime + HOUR
```
gives
```Having trouble with the following expression:
Full expression           : EventDateTime >= baseTime && EventDateTime <= baseTime + HOUR
Exception message         : Cannot find method lessEquals(io.deephaven.db.tables.utils.DBDateTime, java.lang.Object) 
```

**Steps to reproduce**
See above. Per Colin:
```
# These work:
x = TableTools.emptyTable(1).update("HR = currentTime() + (long)HOUR")
x = TableTools.emptyTable(1).update("HR = currentTime() + (int)HOUR")
x = TableTools.emptyTable(1).update("HR = currentTime() + java.lang.Long.valueOf((int)HOUR)")

# These fail:
x = TableTools.emptyTable(1).update("HR = currentTime() + HOUR")
x = TableTools.emptyTable(1).update("HR = currentTime() + (java.lang.Integer)HOUR")
```

**Expected results**
Formulas like this should work.

**Actual results**
See above exception.

**Additional details and attachments**
From slack discussion;

This actually works:
```from deephaven.DBTimeUtils import *
from deephaven import TableTools
x = TableTools.emptyTable(1).update("HR = currentTime() + (long)HOUR")
```

Colin: if i am tracing this properly, we go through PyObject.getObjectValue()
we should be checking this by calling pyobject.isLong()
PyObject.getObjectValue() is the culprit
we must stop using that, as it necessarily boxes, and in native code
the incorrect method is in PythonScopeJpyImp.convert

**Versions**
 - Deephaven: 0.3.1
 - OS: mac 10.15.6
 - Browser: Chrome
 - Docker: ...

**Comment by niloc132** [comment]
The other fix not mentioned is to teach our expression parser to either unbox (and perform null checks) during overload resolution, or more realistically to offer automatic overloads of any method that takes a primitive to also take a boxed variant (plus a null check). Without this, the same bug is possible with groovy, if a local variable happens to be an int instead of a long.
