### ISSUE TITLE
ClassCastException received when hiding a column in a random data table (all types) which includes null and nan values.

### ISSUE THREAD

**Issue by staceybrusco** [deephaven/deephaven-core#1250]
**Description**

Hiding a column in a random data table containing all data types with null and nan values throws a ClassCastException in the Chrome console log.

**Steps to reproduce**
1. Used this query:

[SupportedDataTypes.txt](https://github.com/deephaven/deephaven-core/files/7146493/SupportedDataTypes.txt)

2. Bring up the Chrome console logs in dev tools.
3. From the "randomValuesWithNullNan" table, right click on any column header (doesn't matter which Type), and select "Hide Column"

**Expected results**

The column should be hidden without error in the log.

**Actual results**

The following ClassCastException is thrown and will repeatedly be thrown when moving around the table as long as there is a hidden column:

[ClassCastException-Hidden.txt](https://github.com/deephaven/deephaven-core/files/7146511/ClassCastException-Hidden.txt)

**Additional details and attachments**

<img width="1657" alt="ClassCastException-HideColumn" src="https://user-images.githubusercontent.com/84403742/132918588-78c61659-6048-4283-8522-d511df42f92d.png">

**Versions**
 - Deephaven: 0.3.1
 - OS: Mac Big Sur 11.5.2
 - Browser: Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - Docker: 4.0.0

**Comment by niloc132** [comment]
Can't reproduce the issue in 0.5.3, 0.6.0, or 0.8.0, though in 0.5.3 and 0.6.0 I do get an assertion error that doesn't happen in 0.8.0 or latest.

Note that the layoutHints method has been renamed to setLayoutHints in latest versions.
