### ISSUE TITLE
EPIC: OpenAPI  Input table support 

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#1271]

**Comment by devinrsmith** [comment]
I'd like to have support for 

`io.deephaven.db.v2.utils.AppendOnlyArrayBackedMutableTable#make(io.deephaven.db.tables.TableDefinition)`

via table.proto/BatchTableRequest. The interesting part of this will likely be serializing `TableDefinition` into an appropriate grpc structure. I'm assuming we'd want to use the flight schema? (Is flight schema opaque bytes? If so, does it make sense for use to capture it in a more structured form?)

There was some mention of supporting this via a doPut - and I'd also like to make sure we can do it via BatchTableRequest.

Note: it would probably be good to have support for `io.deephaven.db.v2.utils.KeyedArrayBackedMutableTable#make(io.deephaven.db.tables.TableDefinition, java.lang.String...)` too, if it's not too much more work.

Off-topic(?): I've chatted with @nbauernfeind and I think that doPut's against existing input table tickets should trigger `io.deephaven.db.util.config.MutableInputTable#add(Table newData)`
