### ISSUE TITLE
Syntax error found in the overview example of pydeephaven

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#1279]
from pydeephaven import Session
from pyarrow import csv
session = Session() # assuming Deephaven Community Edition is running locally with the default configuration
table1 = session.import_table(csv.read_csv("data1.csv") **<--- missing ')'**
table2 = session.import_table(csv.read_csv("data2.csv") **<--- missing ')'**
joined_table = table1.join(table2, keys=["key_col_1", "key_col_2"], columns_to_add=["data_col1"])
df = joined_table.snapshot().to_pandas()) **<--- extra ')'**
print(df)
session.close()) **<-- extra ')'**

**Comment by niloc132** [comment]
This is fixed, right? https://github.com/deephaven/deephaven-core/pull/1281

**Comment by jmao-denver** [comment]
yes, not sure why it wasn't auto closed by the squash/merge of #1281

**Comment by jmao-denver** [comment]
should have put in 'fixes #1279' in the commit comment of #1281 to trigger the auto-close
