### ISSUE TITLE
Consider using standardized Java classes for date/time

### ISSUE THREAD

**Issue by mikeblas** [deephaven/deephaven-core#1304]
DH has a set of its own classes for date-time representation. While removing them would cause some work for customers with code against them, using more modern date-time classes (like `java.time` ) would lessen the learning curve for newer users and leverage familiar practices in the Java community.

**Comment by nbauernfeind** [comment]
Is this maybe a duplicate of https://github.com/deephaven/deephaven-core/issues/528?

**Comment by mikeblas** [comment]
Yeah, definitely a dupe of that one. Thanks!
