### ISSUE TITLE
Upgrade JDK to enable upgrading Groovy 3

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#1323]
Groovy 3 requires building on JDK9+ and requires JRE8+.

We should decide what minimum JDK/JRE we want to require, document it (maybe we should agree to a minimum date of support; so that we can continue to upgrade), and quickly migrate.

There is substantial desire (at least James, Matt, Devin) to upgrade Groovy.

**Comment by devinrsmith** [comment]
Completed by https://github.com/deephaven/deephaven-core/pull/1397
