### ISSUE TITLE
Expose conditional formatting methods in JS API

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#1324]
In order to implement conditional formatting menu in the Web UI we need to expose the following formatting methods in JS API: `formatColumns`, `formatColumnWhere `, `formatRowWhere`, `setColumnRenderers` (for progress bar format).

**Comment by mofojed** [comment]
@vbabich / @dsmmcken : What do we need these APIs for? I'm looking at the Conditional Formatting impl in Swing, and it appears to be entirely client side (unless I'm missing something). Why do we need this API?

**Comment by dsmmcken** [comment]
It's client side in swing? Probably easier to accomplish client side in java then in js. We don't do client side anything, and would need to re-implement all the comparisons and query parsing for all column types, including datetimes, bigints, etc. Also, it formatting can support any valid query condition, like `Spread / Ask * 100.0000 > Last`, do you really want to be computing that client side?

**Comment by mofojed** [comment]
I misunderstood some things previously, now I see what's going on. Basically need to wire some functionality through `JsTable` to call `Table.formatColumnWhere`, `Table.formatRowWhere`, `Table.formatColumns`. We could do this a couple ways (could use @niloc132 's and @vbabich 's input here). 

**Option 1 - Passing string array**
- Add `JsTable.applyFormatting(string[])`. Calls `Table.formatColumns` with the string array provided. 
- `Table.formatColumnWhere` and `Table.formatRowWhere` call `Table.formatColumns` anyway, so really only need to call `Table.formatColumns`
- One complication is getting the `formatRowWhere` functionality - would require knowledge of the value of `ColumnFormattingValues.ROW_FORMAT_NAME`, which is `__ROWFORMATTED`.
- Also ignores how to handle `setColumnRenders` as well, might be difficult/hacky to add that in later (cannot just be expressed as string)

**Option 2 - Building it similar to filters:**
- Add `FormatValue format()` method on `Column`
- Create `FormatValue` class, with a ref to the column
- Add `JsTable.applyFormatting(FormatValue[])`, which ends up converting all the args to text and then passing to server to call `Table.formatColumns`
- Could be extended to support progress bar - just add a constant `PROGRESS` that format can be set to?
```java
class Column {
  ...
  FormatValue format(String format) {
    return new FormatValue(this.name, format);
  }
  ...
}

class JsTable {
  ...
  void applyFormatting(FormatValue[] formats) { ... }
  ...
}

class FormatValue {
  static rowFormat(String format) {
    return new FormatValue("__ROWFORMATTED", format);
  }

  String columnName;
  String format;

  FormatValue(String name, String format) {
    this.columnName = name;
    this.format = format;
  }  
}
```

**Comment by niloc132** [comment]
Slack call:
 * All format methods eventually route through Table.updateView, and even conditional formatting can do this (with or without client api syntactic sugar), roughly columnName + formatSuffix = formatType + "(" + formula + ")", where formatType can be `Color`/`Decimal`/`Date`, and formatSuffix depends on the format type
 * This means if we take that approach, the client can avoid exposing the Color(...)/Decimal(...) etc wrappers to the API consumer, and automatically add the correct wrapping.
 * `*` appears to be a magic string that can be used when calling Table.formatColumns to mean "this is a row format column" (though this doesn't really help for directly invoking Table.updateView)
 * Table.select, Table.update, Table.lazyUpdate still require the LTM, but if you end up changing JsTable.applyCustomColumns at all, consider stubbing this work in for when those are optimized.
 * If we stick with Table.updateView, DHCC and DHE already support it, and server side changes will be minimal

**Comment by mofojed** [comment]
Only thing remaining on this ticket is `setColumnRenderers`
