### ISSUE TITLE
Python timetable arithmetic is not working with Deephaven DBTimeUtils time constants like MINUTE

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#1348]
**Description**

In the Python console, constants such as MINUTE are not performing as expected when doing arithmetic on time tables. The following example shows what happens.

```python
from deephaven.time import MINUTE
from deephaven import time_table

source = time_table('00:00:01')
result = source.update(formulas=["wrong = Timestamp + MINUTE", "correct = Timestamp + 60000000000", "eq = wrong == correct"])
```

<img width="506" alt="Screen Shot 2021-09-23 at 2 33 08 PM" src="https://user-images.githubusercontent.com/8659799/134563994-1d9f1e28-4d19-4d37-b0ff-8851111d6d87.png">

Based on the nanosecond difference between the incorrect and source values, it appears that `MINUTE` is being truncated to a 32 bit integer. The following code shows the value of the difference

```python
from deephaven.time import to_datetime, minus

t1 = to_datetime("2021-09-23T14:04:37.870457856 NY")
t2 = to_datetime("2021-09-23T14:04:38 NY")
print(minus(t1, t2))
```

which is `-129542144`. This is the same value that truncating `60000000000` to 32 bits yields.

**Steps to reproduce**

Described above

**Expected results**

The constants should be treated as long values and not int values. `MINUTE` and `60000000000` should yield the same results in the above query.

**Actual results**

Described above.

**Additional details and attachments**

Python doesn't have `long` as a class. Integers have been extended to cover longs. This may help in figuring this out

**Versions**
 - Deephaven: latest
 - OS: OSX
 - Browser: Chrome
 - Docker: Docker version 20.10.8, build 3967b7d

**Comment by nbauernfeind** [comment]
This must be a test case that I missed when implementing #1248. It shouldn't be allowed to shorten from long to int; so that's pretty strange.

Actually super strange is that you can't cast to a long to fix the behavior either:
```python
from deephaven.DBTimeUtils import MINUTE
from deephaven.TableTools import timeTable

source = timeTable('00:00:01')
result = source.update("wrong = Timestamp + (long)MINUTE", "correct = Timestamp + 60000000000")
```

Also true if you explicitly box as a Long:
```python
from deephaven.DBTimeUtils import MINUTE
from deephaven.TableTools import timeTable

source = timeTable('00:00:01')
result = source.update("wrong = Timestamp + java.lang.Long.valueOf(MINUTE)", "correct = Timestamp + 60000000000")
```

Even smaller example demonstrating the issue:
```python
from deephaven.DBTimeUtils import MINUTE
from deephaven.TableTools import emptyTable
print(MINUTE)
print(type(MINUTE))
result = emptyTable(1).update("I = MINUTE")
```

It's not obvious at first glance; will need to spend more time. (But I accept the report.)

**Comment by chipkent** [comment]
I just did a quick search.  Python seems to use a variable number of bits to store integers (https://www.pythontutorial.net/advanced-python/python-integers/).  I don't know if this is related or not, but I want to point it out.
