### ISSUE TITLE
Inconsistency in how Python and Groovy lists are displayed in the UI

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#1353]
**Description**

The following query creates a table with a simple array

```groovy
lst = [1,2,3]

source = emptyTable(10).update("X = ii")
result = source.update("A = lst")
```

Running this in Groovy shows a table like this in the UI

<img width="154" alt="Screen Shot 2021-09-24 at 10 29 34 AM" src="https://user-images.githubusercontent.com/8659799/134700079-de1bce5e-03a5-47af-9da1-d8271d93cb02.png">

While Python shows this

<img width="273" alt="Screen Shot 2021-09-24 at 9 38 23 AM" src="https://user-images.githubusercontent.com/8659799/134700171-8708bb9a-e795-42c2-aa36-ffa9cad05dc2.png">

**Steps to reproduce**

Described above

**Expected results**

The Python table should show the same as the Groovy table

**Actual results**

The Python table shows the JPY class name

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by nbauernfeind** [comment]
This is related to #755 and should probably be a simple addition to that work.
