### ISSUE TITLE
Description undefined when using withColumnDescription

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#1354]
**Description**

Column descriptions don't appear to be sent with column info. Inspecting the table model in the Web UI shows description as undefined. Doing the same in DHE shows the description value.

**Steps to reproduce**
Run the following Python code

```python
from deephaven.TableTools import newTable, stringCol

source = newTable(
    stringCol("Letter", "A", "B", "C")
).withColumnDescription("Letter", "Letter Description")
```

**Expected results**

The JS API object for the table should have
`table.columns[0].description === 'Letter Description'`

In the Web UI hovering over the column header shows the description below column name and above column count.

**Actual results**

The JS API object for the table has
`table.columns[0].description === undefined`

No column description when hovering over column header in Web UI

**Versions**
 - Deephaven: 0.4.1

**Comment by niloc132** [comment]
This is fixed in 0.8.0 and latest, possibly as part of the input table work, which required improving support for other table attributes.
![screenshot769](https://user-images.githubusercontent.com/241630/147979695-6e812d7a-bd66-4751-b7c8-319185b36351.png)
