### ISSUE TITLE
New CSV parser does not handle empty columns

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#1469]
The `readCSV` CSV parser would ignore columns with empty header names.  The new CSV parser:
1) raises an exception about improper column names
2) the exception is cryptic because quotes are not used to indicate the name.  With an empty string, this just looks like we don't indicate what the problematic column is.

We had a client provide such a CSV.  It would run fine on `v0.5.0` with the old CSV parser.  It failed on `v0.5.1` and `v0.5.2` with the new CSV parser.

Example data can be found at:
https://github.com/chipkent/neptune-demo-20211105/blob/main/data/TX%20Signature%20Data/Texas_Concerns_Batch.csv

This is proprietary data, so request access from @chipkent if you need access.

**Comment by rcaudy** [comment]
@devinrsmith Raises a valid point that maybe we shouldn't support this.

**Comment by devinrsmith** [comment]
If we want to support this - should we raise an error when there happens to be data in the csv associated w/ the empty column name?

**Comment by chipkent** [comment]
I think it is very reasonable that we might not want to support this, but it is a regression with the old parser.  

For a CSV parser with headers, it seems like there are two valid paths forward if a header value is missing.  You can either raise an exception, or you can ignore the column.  I spoke with @pchambre to get some background info.
1) DHE CSV import raises an exception.
2) DHE (old) CSV parser ignores the column.
This means that DHE is inconsistent in what it does.

Pandas appears to parse such cases with a column name `""`.

I think that we should either leave things as they are and throw an exception, or we should add an explicit input param to ignore such columns, with the default to raise an error.

**Comment by rcaudy** [comment]
There's another workaround; explicitly name the columns. Might be a little bit annoying to do as a user.

**Comment by chipkent** [comment]
Does a column name override work right now?
