### ISSUE TITLE
Pydeephaven Session() should display tables that currently exist in Deephaven

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#1480]
As a Python user, I want to see tables that already exist in Deephaven when I make a new connection via the `pydeephaven` package, so that I can interact with tables that have already been created (such as through app mode, another script, UI actions, etc).

For example, if I have a Deephaven instance and use the UI to create a table called `result`, I'd expect the following Python script to work

```
from pydeephaven import Session

session = Session()

print(session.tables) #Should display a list with ["result"]

result = session.open_table("result") #Should connect to the "result" table on the server
```

**Comment by devinrsmith** [comment]
Workaround: 

```python
session.run_script("new_table_name = known_table_name")
new_table_name = session.open_table("new_table_name")
```

**Comment by devinrsmith** [comment]
We might want an explicit way to opt into server side changes (instead of baking it in for every client):

```python
session.subscribe_fields()
```
Or something like that.
