### ISSUE TITLE
EPIC: Deephaven Plugins (formerly but no longer called "Extensions")

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#1484]
Deephaven Extensions - allowing installing a packaged extension that will allow some additional functionality. See discussion https://github.com/deephaven/deephaven-core/discussions/1468
- Needs back end and front end hooks
- Extension can include python packages to be installed on backend, plugins for the web UI on the frontend
- Object provide a custom method (`_deephaven_object` or something similar) to indicate they want to be exported to front end, can include a custom payload, and links to tables/input tables (for two way communication between front end and backend)
- No intent to support Groovy backend extensions at this time
- Prove for at least three different libraries/use cases: matplotlib, seaborn, and a custom needle/meter widget

- [x] #1485
- [ ] #1511
- [x] #1766 
- [x] #1874
- [x] #1875
- [x] Build three use cases/examples utilizing the Deephaven Extension framework

**Comment by pete-petey** [comment]
Make sure this includes ideas for layout management, etc.

**Comment by mofojed** [comment]
Closing this ticket, as we have https://github.com/deephaven/deephaven-plugin and a few different examples already implemented.
