### ISSUE TITLE
stream table semantics via Barrage

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1492]
If a stream table has a fast update cycle, and a remote subscriber has a slow update cycle; it would be nice if the update to the remote subscriber was the aggregate of the underlying stream changes.

**Comment by nbauernfeind** [comment]
Doesn't that happen automatically? Barrage will propagate updates no faster than at a configured interval. By default, along a chain, you get the maximum interval of all of them.

Can you be more specific of this request?
