### ISSUE TITLE
pydeephaven should utilize '*args' whenever possible to make it easier for the users and be consistent with server Python

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#1503]
For instance: Table.update(formulas : List[str]) requires a Python list parameter even when a single formula is needed.
A better way to define the update method is Table.update(*formulas: str) which would not require a list being provided.

**Comment by jakemulf** [comment]
Discussions on this have made us move to the following solution. We want to supply either a single string _or_ a list of strings, such as

```
table.update("column = value")
table.update(["column1 = value1", "column2= value2"])
```

**Comment by pete-petey** [comment]
I think this is done.
