### ISSUE TITLE
Support importing a Deephaven Extension package with hooks in backend and frontend

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#1511]
See discussion: https://github.com/deephaven/deephaven-core/discussions/1468

Extension needs a directory structure specified, ie:
```
/MyExtension
  /init
    /grpc-api
    /py-env
  /ui
    /dashboard-plugins
```
Not too sure what the install command/process would be yet, that is something to discuss here. But in terms of the structure:
- `/init` folder for initialization scripts. In the matplotlib case, this would need a script in grpc-api to [pip install matplotlib](https://github.com/mofojed/deephaven-core/blob/cf0940e3f1737771e5fa29d1dab11a6fcbcc07f5/README.md?plain=1#L8) and a script in py-env to [extend matplotlib.figure.Figure with the getDeephavenObject method](https://github.com/mofojed/deephaven-core/blob/cf0940e3f1737771e5fa29d1dab11a6fcbcc07f5/README.md?plain=1#L21). We could add subfolders for any other initialization scripts we may need (eg. for other containers)
- `/ui` folder for Web UI dashboard plugins. In the matplotlib case, the [MatPlotLibPlugin](https://github.com/mofojed/web-client-ui/blob/matplotlib/packages/dashboard-core-plugins/src/MatPlotLibPlugin.tsx) handles it.

**Comment by devinrsmith** [comment]
I don't think we should try to create a new directory structure for the server side code just for type-extensions - extending the server with any 3rd-party code is a wider issues IMO, and can be handled in a more generic (and just as "easy") way.

At the end of the day, to support 3rd-party code we need to have a way for the 3rd-party to easily add a jar(s) to the classpath, or to install a new python library (which will be lreachable via java/jpy).

**Comment by mofojed** [comment]
What about installing local/private jars/python libs?

**Comment by devinrsmith** [comment]
That's all fine - I'm including local/private jars, etc. I'm going to link to some other relevant tickets shortly...
