### ISSUE TITLE
JS API can fail to handle deltas with both shifts and modifies

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#1554]
Sample code to repro this in the web IDE:
```python
from deephaven.TableTools import emptyTable, timeTable
import jpy
KeyedArrayBackedMutableTable = jpy.get_type('io.deephaven.db.v2.utils.KeyedArrayBackedMutableTable')
MutableGroups = KeyedArrayBackedMutableTable.make(emptyTable(0).updateView('Groups=""'), 'Groups')
WithUpdatingColumn = MutableGroups.naturalJoin(MutableGroups.select("K=k").sumBy(), "")
Sets = emptyTable(9).updateView("I=i")
Joined = Sets.join(WithUpdatingColumn)
```

To set it up, position MutableGroups and Joined side by side, and give MutableGroups 3 rows, A, B, C. Sort Joined by the “I” column, and ensure that it has about 11-15 rows visible (this is fuzzy, may need to resize and try again). Delete the C row, then:

* Add the C row
* Delete the C row

If the error doesn’t occur, adjust the size and try again.

Expected results, when C is added/removed to MutableGroups, then rows will be added/removed with C in the “Groups” column.

Actual results, error in the browser console, and the table stops getting updates.

**Comment by devinrsmith** [comment]
Any chance this is related to https://github.com/deephaven/deephaven-core/issues/1224 ?

**Comment by niloc132** [comment]
Almost certainly not - that only has adds, no shifts or modifies - it is the interaction between shift and modify that causes this bug.
