### ISSUE TITLE
TableTools.readCsv should be able to type detect ISO 8601 format for timestamps as DBDateTime.

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#1570]
A file generated in python pandas using `.to_csv(...)` for a dataframe that was loaded from a parquet file with a timestamp(nanos) type column:

```
cfs@erke 16:55:20 ~/dh/oss1/deephaven-core/data
$ head -n 10 /a1/tmp/workqueue-no-nulls-100m-no-index.csv
workqueue_id,user_id,timestamp
1,1001,2021-11-07 14:00:00.011463807+00:00
2,1003,2021-11-07 14:00:00.080748962+00:00
3,1002,2021-11-07 14:00:00.114976256+00:00
4,1004,2021-11-07 14:00:00.118275772+00:00
5,1003,2021-11-07 14:00:00.131173174+00:00
6,1001,2021-11-07 14:00:00.174901899+00:00
7,1001,2021-11-07 14:00:00.194499326+00:00
8,1002,2021-11-07 14:00:00.201754097+00:00
9,1004,2021-11-07 14:00:00.237870788+00:00
```

The timestamp column formatted as above is not recognized by DHC when using `TableTools.readCsv`; the column is read as String.

More generally, we should accept valid ISO 8601 strings as timestamps, any of them.

**Comment by rcaudy** [comment]
@devinrsmith did add support for ISO 8601 timestamps. I think we're looking for 'T' as a separator. Wikipedia claims space is not an acceptable separator:
https://en.wikipedia.org/wiki/ISO_8601
>A single point in time can be represented by concatenating a complete date expression, the letter "T" as a delimiter, and a valid time expression. For example, "2007-04-05T14:30". In ISO 8601:2004 it was permitted to omit the "T" character by mutual agreement as in "200704051430",[33] but this provision was removed in ISO 8601-1:2019. Separating date and time parts with other characters such as space is not allowed in ISO 8601, but allowed in its profile RFC 3339.[34]

**Comment by rcaudy** [comment]
We should consider whether to be more permissive than the ISO standard.

**Comment by rcaudy** [comment]
Right now, the code is effectively using:
```
java.time.format.DateTimeFormatter#ISO_INSTANT
```
This loos like it's quite authoritatively parsing strict ISO 8601. We might be able to use `java.time.format.DateTimeFormatterBuilder` to build something more lenient.

@jcferretti Does Pandas publish a discussion for what kind of permissive formats they allow outside of the ISO standard?
