### ISSUE TITLE
Package JS API as a module

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#1582]
It would help the reusability of our components if the JS API was a module. Currently, we use a shim in the web client which just expects a global `dh` to exist in the browser.

Where this causes issues currently is on the docs, specifically plots right now. The constants used by our plotting rely on the JS API, and that means the API needs to be included in the docs manually (via script tag) to make the plot components work. I also have to do some ugly workarounds asynchronously loading the API from a docker endpoint to generate snapshots for the docs.

It would be easier if we had the API exposed as a module instead so it can be imported nicely. Bonus points if we can generate a .d.ts for the API so we can take advantage of the types in TypeScript

**Comment by mofojed** [comment]
This would also be nice to allow for autocomplete in IDE when developing (though perhaps can be accomplished another way), and for tests (we're just using mocks right now, which we could just reduce to a partial mock instead)

**Comment by mofojed** [comment]
First PR: https://github.com/deephaven/deephaven-core/pull/2733

**Comment by mofojed** [comment]
Closing in favour of #2735
