### ISSUE TITLE
Autoload layout.json

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#1588]
As a user, I want my layout.json to load (if it is present) and override any other layout currently cached so that I can more easily share dashboards and examples with other users.

**Comment by mofojed** [comment]
One complication is that we want the user to be able to make changes to the layout and have that stay for the next reload - they can reset their layout to default from the Panels->Reset Layout button.
Perhaps we can mark the date the layout we originally loaded is from, so we can tell if the layout on the server has been updated and we can then reset the layout.
