### ISSUE TITLE
Displaying a table with a BigDecimal column crashes the web UI

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#1607]
The following code crashes the web UI:

```
import deephaven.Types as dh
import jpy
jbigdecimal = jpy.get_type('java.math.BigDecimal')
t = dh.table_of([[jbigdecimal.valueOf(301, 2)], [jbigdecimal.valueOf(201,2)], [jbigdecimal.valueOf(101,2)]], [('decimal_value', dh.bigdecimal)])
```

Visually it looks like the two window captures below; the display stays for a few seconds as the first one, then chrome sees it crash as per the second one.

![Deephaven - Google Chrome_130](https://user-images.githubusercontent.com/37232625/143662361-b664fee7-c77b-4893-b35d-ce5620d444b9.png)

![Deephaven - Google Chrome_131](https://user-images.githubusercontent.com/37232625/143662365-d5a39f68-bd7d-4e11-a234-dc768e09d0da.png)

**Comment by niloc132** [comment]
Not sure specifically why you're getting a sigkill (linux killing the chrome process for oom?).

https://github.com/deephaven/deephaven-core/issues/513 is the issue to track the server implementing BigDecimal/BigInteger - the client has an attempt at reading it, but without the server speaking the same language, I didn't put any real effort into it.

However, if the server encounters a type that it can't send, it can turn it into a string and send that instead. We have support for that on the server, but in this case the client is incorrectly only reading the `deephaven:type` metadata and not checking the actual arrow type for the buffer. Right now this is unofficially part of https://github.com/deephaven/deephaven-core/issues/188, the rest of the js api's handling is "good enough".

Both of these should be resolve anyway, but handling either one will probably fix your issue. It would be worth trying to understand why chrome is getting its process killed though, to see if there is something else we can do to prevent it in general.

**Comment by jcferretti** [comment]
> Not sure specifically why you're getting a sigkill (linux killing the chrome process for oom?).

Note the signal is `SIGILL (Illegal Instruction)`, not `SIGKILL (Kill signal)`.  Which arguably makes it even weirder.

**Comment by niloc132** [comment]
Yikes you're right. And you were right, I should have waited until monday to look at this.

My brain replaced `IG` with somthing like `K`, while still leaving in the I and the G along the way. It would be nice to know what abuse of typedarrays is causing chrome to crash though, instead of a JS runtime error...

My best guess _was_ that by misreading the flight schema I was allocating too much space and the JS runtime was crashing out rather than listen to me, but I'm not so sure now.
