### ISSUE TITLE
AggSpecUnique is missing noValue and nonUniqueValue options

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#1661]
Needs to match the feature set of `io.deephaven.engine.table.impl.by.UniqueSpec`.

**Comment by devinrsmith** [comment]
One interesting part about this problem is serialization - how is a remote client expected to be able to configure these values? It's an "easy" answer for primitives, strings, and nulls.

**Comment by devinrsmith** [comment]
It may make sense to create a `Literal` interface as a subset of `io.deephaven.api.value.Value` (ie, everything that isn't a ColumnName).

**Comment by rcaudy** [comment]
As a wrapper for an `Object`?

**Comment by rcaudy** [comment]
Keeping "onlyNullsValue" (AKA "noKeyValue") out of AggSpecUnique for now.

**Comment by rcaudy** [comment]
Adding "nonUniqueSentinel" as an nullable `Object` param.
