### ISSUE TITLE
Remove deephaven/grpc-api image name

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1691]
As we build more images with more configuration options (netty, jetty), we'd like to be more descriptive than `deephaven/grpc-api`. Right now, this image is also built as `deephaven/server`. Once we can confirm that all external references to `deephaven/grpc-api` have been updated to a more appropriate reference, we can fully remove the deephaven/grpc-api image name from being built.

**Comment by pete-petey** [comment]
link to #1756
