### ISSUE TITLE
dh-defaults.prop either needs to be replaced by grpc-api.prop or cleaned up for DHC

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#1732]
dh-defaults.prop contains a lot of properties that don't apply to DHC and is used in certain projects and tests. grpc-api.prop is much cleaner and more relevant.

**Comment by rcaudy** [comment]
I'm not sure this is so, nor do I think we should strictly replace `dh-defaults.prop` with `grpc-api.prop`.
We absolutely should remove defunct properties, however.
