### ISSUE TITLE
RowSet find() performance regression (DHC and DHE)

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#1751]
**Description**

**Steps to reproduce**

**Expected results**

**Actual results**

A clear and concise description of what actually happened.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by jcferretti** [comment]
The regression does not exist in DHC thanks to the compiler in JDK > 8.
In DHE this was fixed, see https://deephaven.atlassian.net/browse/DH-12036
