### ISSUE TITLE
JS API Hierarchical Table support

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#1763]
Update the dh.TreeTable type to use the new gRPC services around hierarchical tables. These types behave largely like typical tables, with a few exceptions:
 * custom columns are not supported at this time
 * size is not available until a viewport has been set (due to the fact that "size" doesn't make sense without expand/collapse state), and will be reported as -1 until then

Typical tables can be transformed into hierarchical tables through the use of table.rollup() and table.treeTable(). Hierarchical tables in scope can also be fetched by name.

**Comment by niloc132** [comment]
This should be safe to close now.
