### ISSUE TITLE
Update demo branch to latest Deephaven-core release

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#1845]
The demo branch isn't up to date with the latest Deephaven release. For example, trying to use `DateTimeUtils` results in the following error

```
Type: <class 'ModuleNotFoundError'>
Value: No module named 'deephaven.DateTimeUtils'
```

**Comment by devinrsmith** [comment]
Note: the currently released demo branch does seem to have `deephaven.DateTimeUtils`, but no notebooks.

**Comment by mofojed** [comment]
The demo was updated a while ago, no need to keep this ticket open any longer.
