### ISSUE TITLE
Rename remaining classes that refer to Index instead of RowSet

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#1849]
io.deephaven.server.barrage.BarrageStreamGenerator.EmptyIndexGenerator
io.deephaven.server.barrage.BarrageStreamGenerator.IndexShiftDataGenerator
io.deephaven.server.barrage.BarrageStreamGenerator.IndexGenerator

**Comment by rcaudy** [comment]
`io.deephaven.extensions.barrage.util.BarrageProtoUtil#toIndex` too
