### ISSUE TITLE
Deephaven2 tables not populating UI

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#1891]
**Description**

Executing new_table and empty_table from deephaven2 does not populate the UI or have tables enter the panels tab.

**Steps to reproduce**
On new pull of edge docker containers (1/26/2022), in python run:
```
from deephaven2 import new_table
from deephaven2.column import string_col, double_col
test_table = new_table([
    string_col("StringColumn", ["Str1", "Str1", "Str2", "Str2"]),
    double_col("Decimals", [1.0, 2.0, 4.0, 8.0])
])
```
or
```
from deephaven2 import empty_table
test_table2 = empty_table(5)
```

**Expected results**

test_table and test_table2 should show up in the UI and Panels tab.

**Actual results**

No errors and no tables appear. 

https://user-images.githubusercontent.com/51727488/151236400-079283ae-9e3f-4b8a-90e8-c6d7073b5a34.mp4

**Comment by mofojed** [comment]
@devinrsmith it looks like this was introduced with your change: `9853bda66ccbd033304a28f65f2611bd4e5f83bb`
Can you take a look? Doesn't look like there's any noticeable errors in the log

**Comment by devinrsmith** [comment]
Will look, thanks.
