### ISSUE TITLE
web-plugin-packager releases

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#2033]
**Description**

docker/web-plugin-packager/README.md references `FROM ghcr.io/deephaven/web-plugin-packager:latest`

there is no latest release. 
need to create latests or change README to reference main

**Steps to reproduce**

**Expected results**

DCU to run after readme instructions

**Actual results**

container not found. switch to main to run.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by mofojed** [comment]
The `latest` tag should work now. https://github.com/deephaven/deephaven-core/pkgs/container/web-plugin-packager
