### ISSUE TITLE
[Groovy] groovy arrays don't show an expected type when stored in a deephaven table

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#2081]
**Description**

Given the following Groovy code

```groovy
numArr = [1, 2, 3] as int[]

arr_table = emptyTable(1).update("Array = numArr")
```

You'd expect the `Array` column in `array_table` to have a type of something like an array, but the following is displayed

![Screen Shot 2022-03-09 at 1 46 17 PM](https://user-images.githubusercontent.com/8659799/157510100-adf120fc-6b65-4d81-954b-33c5acad103e.png)

Even stranger, the meta data displayed gibberish as the column type

```
result = arr_table.getMeta()
```

![Screen Shot 2022-03-09 at 1 46 59 PM](https://user-images.githubusercontent.com/8659799/157510220-53b4a963-cabc-4c57-94ab-66aae180f0c9.png)

However, the following code does work, making me think this is a UI bug

```
arr_table_extracted = arr_table.update("Array0 = Array_[i][0]")
```

**Steps to reproduce**

Shown above

**Expected results**

The UI and table meta type would be something related to an array

**Actual results**

Unexpected values are displayed

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.10.0
 - OS: OSX
 - Browser: Chrome
 - Docker: Docker version 20.10.8, build 3967b7d

**Comment by nbauernfeind** [comment]
The `Preview of type` text was fixed in #2332. A fix is incoming for `getMeta()`.
