### ISSUE TITLE
Support > 4MB messages in the Java Barrage Client

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#2083]
As a user, I want to be able to snapshot or subscribe to large tables that exceed the standard 4MB limit of the Java gRPC client.  Currently can receive the following error when the data returned is too large:

`Error detected in subscription: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 289836370`

**Comment by niloc132** [comment]
Whoops we fixed the other half of this https://github.com/deephaven/deephaven-core/issues/1816 / https://github.com/deephaven/deephaven-core/pull/1817 - I guess we need to set the other side too?
