### ISSUE TITLE
Barrage: partial sub change may revert a previous sub change

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#2089]
**Description**

There is a race condition in `BarrageMessageProducer` regarding partial subscription changes. If only one of the viewport or column is changed, then it will copy/clone the un-changed portion of the subscription from the active subscription details. If there is currently an update propagation where a subscription is mid-viewport change it may copy the older subscription details.

1. set initial viewport and columns
2. update viewport and columns
3. while the update propagation is in the snapshot building phase, set just the columns
4. after the 2nd snapshot occurs, the client will be using the initial viewport

**Expected results**

The viewport client is using the viewport from step 2 and the columns from step 3.

**Actual results**

The viewport client is using the viewport from step 1 and the columns from step 3.

**Additional details and attachments**

Ryan suggested not allowing the user to change their subscription partially. This removes the need to copy/clone in `BarrageMessageProducer` and eliminates this race condition.

**Comment by niloc132** [comment]
FWIW, I had not interpreted this api call as allowing me to only send rows but not columns or vice versa when making a change to an existing viewport.
