### ISSUE TITLE
Deleting tables appears to decrease available memory

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#2129]
**Description**

Deleting tables in a Python session via either `del`, `gc`, or other methods appears to decrease the available memory.

**Steps to reproduce**

The following Python code reproduces this issue:

```
from deephaven.TableTools import emptyTable

runtime = jpy.get_type("java.lang.Runtime")

print("Total used memory in bytes (no table yet): ")
print(runtime.getRuntime().totalMemory() - runtime.getRuntime().freeMemory())

t = emptyTable(100000).update("X = i", "Y = 2 * i", "Z = 3 * i")

print("Total used memory in bytes (with table in memory): ")
print(runtime.getRuntime().totalMemory() - runtime.getRuntime().freeMemory())

del t

print("Total used memory in bytes (after table has been deleted): ")
print(runtime.getRuntime().totalMemory() - runtime.getRuntime().freeMemory())
```

**Expected results**

The amount of used memory should go *up* after creating the table `t`, but then should either go back *down* or stay the same after deleting it with `del`.

**Actual results**

The amount of used memory *increases* after calling `del` to delete the table.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.10.x
 - OS: OS X
 - Browser: Chrome
 - Docker: Docker Desktop 4.6.1

**Comment by devinrsmith** [comment]
After gc, I see the memory return to pre-table levels:

```python
runtime.getRuntime().gc()
print(runtime.getRuntime().totalMemory() - runtime.getRuntime().freeMemory())
```

Note: the call to `gc()` is not guaranteed to invoke GC (you may need to try multiple times, depending on JVM).

**Comment by devinrsmith** [comment]
Here's a quick, ad-hoc memory table:

```python
from deephaven.TableTools import timeTable
import jpy

runtime = jpy.get_type("java.lang.Runtime").getRuntime()
memory_table = timeTable("00:00:01")\
    .update("TotalMemory=runtime.totalMemory()", "FreeMemory=runtime.freeMemory()")\
    .updateView("AvailableMemory=TotalMemory-FreeMemory")
```

**Comment by devinrsmith** [comment]
See #2130
