### ISSUE TITLE
read_csv pulls doubles in as a string

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#2133]
**Description**

double in a csv is not parsing correctly. 

**Steps to reproduce**

in Version 0.10.1
```python
from deephaven import read_csv
from deephaven import Plot

# source the data
totalInsurance = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/Insurance/csv/insurance.csv")
```

**Expected results**

the column in table `expenses` is a double 

**Actual results**

the column in table `expenses` is a string 

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/51727488/160624899-acbed070-d3b7-4d0f-b26d-aecdcb1c7dc4.png">

**Comment by kosak** [comment]
Thank you very much for this bug report. I have reproduced the problem and we will have a fix soon.
