### ISSUE TITLE
`catErrorBar` is stuck as a constant spinner

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2156]
To reproduce in v0.11.2

```python
from deephaven import Plot
from deephaven.TableTools import newTable, intCol, stringCol

source = newTable([
    stringCol("Categories", ["A", "B", "C"]),
    intCol("Categories2", [1, 2, 3]),
    intCol("Values", [9, 10, 11]),
    intCol("LowerError", [8, 9, 10]),
    intCol("UpperError", [10, 11, 12])
])


v1_plot = Plot.catErrorBar("Categories Plot v1", source, "Categories2", "Values", "LowerError", "UpperError").show()
```

To reproduce in #2112 (python v2):
```python
from deephaven2.plot.figure import Figure
from deephaven2.plot import PlotStyle
from deephaven2 import new_table
from deephaven2.column import int_col, string_col

source = new_table([
    string_col("Categories", ["A", "B", "C"]),
    int_col("Categories2", [1, 2, 3]),
    int_col("Values", [9, 10, 11]),
    int_col("LowerError", [8, 9, 10]),
    int_col("UpperError", [10, 11, 12])
])

v2_plot = Figure().plot_cat("Categories Plot v2", source, "Categories2", "Values", "LowerError", "UpperError").show()

from deephaven import Plot

v1_plot = Figure(Plot.catErrorBar("Categories Plot v1", source.j_table, "Categories2", "Values", "LowerError", "UpperError").show()._figure)
```

**Comment by mofojed** [comment]
At a lower level, [CategoryErrorBarDataSeriesKernel](https://github.com/deephaven/deephaven-core/blob/3b68471b57977fe44fb77c87edcbb79d1fd2cc7c/Plot/src/main/java/io/deephaven/plot/datasets/categoryerrorbar/CategoryErrorBarDataSeriesKernel.java#L32) does not seem to have a complete implementation. Specifically, `errorBarLowColumn` does not appear to be wired up to anything.
Additionally, it is not handling this category and throwing an error correctly that it is currently unsupported: https://github.com/deephaven/deephaven-core/blob/3b68471b57977fe44fb77c87edcbb79d1fd2cc7c/plugin/figure/src/main/java/io/deephaven/figure/FigureWidgetTranslator.java#L409
I'll add a change to throw as the plot is unsupported at the very least.
