### ISSUE TITLE
Support `getMeta` in client APIs

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2243]
The client APIs do not currently support `getMeta`.  This is a very useful method when developing code.  To support the client APIs, `getMeta` must first be implemented in the gRPC layer.

**Comment by nbauernfeind** [comment]
Absolutely. This can easily be implemented as a GrpcTableOperation as it provides a Table -> Table transformation. If we also pull the Table method into TableOperations then it is easily integrated with the java client.
