### ISSUE TITLE
App mode library doesn't work with new python tables

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#2245]
**Description**

The following application mode code does not work with the new python library

```
import jpy
from deephaven import empty_table
from typing import Callable

ApplicationState = jpy.get_type("io.deephaven.appmode.ApplicationState")

#ApplicationState examples
def start(app: ApplicationState):
    table = empty_table(5)
    table = table.update(["Values = i"])

    app.setField("table", table)

def initialize(func: Callable[[ApplicationState], None]):
  app = jpy.get_type("io.deephaven.appmode.ApplicationContext").get()
  func(app)

initialize(start)
```

Error thrown
```
server_1      | Type: <class 'ValueError'>
server_1      | Value: cannot convert a Python 'Table' to a Java 'java.lang.Object'
```

Changing the setField call to `app.setField("table", table.j_object)` makes it work as expected

**Expected results**

The code above works

**Actual results**

The code above errors out

**Additional details and attachments**

**Versions**
 - Deephaven: edge
 - OS: osx
 - Browser: chrome
 - Docker: Docker version 20.10.8, build 3967b7d

**Comment by devinrsmith** [comment]
We need to have a python wrapper around `ApplicationState`. Any time we see non-pythonic code, ie camel-case method calls, `setField`, it's a place for improvement.
