### ISSUE TITLE
getColumn and getColumnSource for new python library tables

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#2246]
For the old python tables, equivalent functionality for `getColumn` and `getColumnSource` is not present in the new python tables. We should have equivalent methods for these in the new python table.

Example use cases for the old methods

```
timestamp = table.getColumnSource("Timestamp").get(0)
```

```
instrument_2nd = agg_by_instrument.getColumn("Instrument").get(1)
```

Current workaround involves using `table.j_object`

**Comment by jmao-denver** [comment]
@jakemulf from the example provided in the description, it seems you just need a way to access the value of a cell in a column. If so , wrapping getColumn is sufficient. Wrapping getColumnSource OTOH would require us explaining what a ColumnSource is and the nuances regarding performance, index etc.

**Comment by jakemulf** [comment]
> @jakemulf from the example provided in the description, it seems you just need a way to access the value of a cell in a column. If so , wrapping getColumn is sufficient. Wrapping getColumnSource OTOH would require us explaining what a ColumnSource is and the nuances regarding performance, index etc. Your thoughts?

`getColumnSource` seems to be the preferred method for getting items from a listener based on the enterprise docs, so unless we can replicate that functionality easily with `getColumn` I think we might need to have both. I can look into using `getColumn` for a listener though

**Comment by jakemulf** [comment]
So I tried the code at https://deephaven.io/core/docs/how-to-guides/table-listeners-python/#reading-table-data using `getColumn` instead of `getColumnSource` and it doesn't work

I'd be happy to make an action item to document https://deephaven.io/core/javadoc/io/deephaven/engine/table/DataColumn.html and https://deephaven.io/core/javadoc/io/deephaven/engine/table/ColumnSource.html in a how-to guide or something

**Comment by jmao-denver** [comment]
Thanks Jake. In today's Python Sync meeting, @rcaudy has expressed his rather strong opposition to wrapping ColumnSource and DataColumn and instead suggested either 1) we expose them as opaque JPY objects; 2) enhance the numpy and pandas module to support both the direct cell access and table listener use cases.  I have doubts about 2, but that's what we will be trying first. @chipkent please comment if I missed or misrepresented the discussion.

**Comment by chipkent** [comment]
Let me summarize my takeaways from the discussion.

1) Individual cell access has various problems in its current form using `getColumn` and `getColumnSource`.  If the API is used in subtly wrong ways, users can get incorrect or inefficient results.

2) There are basically two use cases: (a) access particular cells in a table after a query based upon position in the table (e.g. first cell or last cell) and (b) access ranges of cells based upon `k` index in listeners. 

3) For case (a), we think that our libraries for converting to numpy and pandas can be leveraged to allow users to access particular cells in a safe and efficient way.  @jmao-denver is assessing this, and I'm sure he wants feedback based on what he finds.

4) For case (b), we expect that it _may_ be possible to extend the numpy and/or pandas conversions to work with `k` values in a way that results in more simple, correct, and efficient code for listener writers.  @jmao-denver is going to explore ideas in this area, with @rcaudy, to see what looks possible.

**Comment by jakemulf** [comment]
As long as the numpy/pandas conversions are efficient enough to work in real-time both for speed and memory (ex: https://github.com/deephaven-examples/rss-podcasts/blob/main/python-scripts/slack-listener.py), then that will work for me. It's a bit cumbersome to migrate old code but it is what it is

**Comment by jmao-denver** [comment]
@hythloda the numpy.py should have the functionality you mentioned, I would like you to give it a try and let me know if it works for you.
