### ISSUE TITLE
lower_bin should return Instant type

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#2303]
Should be fixed by a solution to #2306 

**Description**

lower_bin returns a string and not a DateTime

**Steps to reproduce**

On edge using:

```python 
from deephaven.time import lower_bin


from deephaven import time_table
minute_in_nanos = 60 * 1000 * 1000 * 1000

source = time_table('00:00:01')\
    .update_view( ['received_at_minute = lower_bin(Timestamp, minute_in_nanos)'] )
```

**Expected results**

Expected new column to be a DateTime value without the extra casting
<img width="272" alt="image" src="https://user-images.githubusercontent.com/51727488/164255125-db1cf7db-951c-4e4e-96eb-ef2617b38fdf.png">

**Actual results**

Without casting it explicitly as a DateTime the column is a string.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/51727488/164254968-456788f0-44a6-40d0-9f2a-b88942cba7c8.png">
**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by jmao-denver** [comment]
the usage is no longer supported by changes in #4388
