### ISSUE TITLE
Python integration for Kafka should support specifying schema as a string

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2305]
As a user of our Kafka integration, I want to be able to use the Python wrappers when I have a schema as a string and no access to a schema registry server.

**Comment by rcaudy** [comment]
The following workaround seems to address the immediate need, although it's not pretty:
```
import jpy

json_schema_str = """
{ "type" : "record",
  "namespace" : "io.deephaven.examples",
  "name" : "share_price",
  "fields" : [
      { "name" : "Symbol", "type" : "string" },
      { "name" : "Side",   "type" : "string" },
      { "name" : "Qty",    "type" : "int"    },
      { "name" : "Price",  "type" : "double" }
  ]
}
"""

JSchemaParser = jpy.get_type('org.apache.avro.Schema$Parser')
j_avro_schema = JSchemaParser().parse(json_schema_str)

JConsume = jpy.get_type("io.deephaven.kafka.KafkaTools$Consume")
j_value_spec = JConsume.avroSpec(j_avro_schema)

from deephaven.stream.kafka.consumer import KeyValueSpec
value_spec = KeyValueSpec(j_value_spec)
```

**Comment by devinrsmith** [comment]
I'd like to have support for Java `org.apache.avro.Schema` types. I don't think we want/need a wrapper; just to pass it on through if the user specifies it.

As I see it, I think there are 3 *types*:

1. schema name (lookup in registry)
2. schema string
3. schema object
