### ISSUE TITLE
Python Wrapper Properties include Java static method 

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#2306]
As a python user, I want no confusion about which method does what. 

We should attach a property to every wrapper function to hold the name of the wrapped Java static method.

This will allows for no confusion for the user with the difference between `lower_bin` and `lowerBin` and having to know when to use which.

Something akin to an alias so `theMethod` in Java can be `the_method` when used from python.

This issue was highlighted with @jcferretti from the [Debezium Python V2 rewrite]( https://github.com/deephaven/deephaven-core/pull/2299). As there are two ways for the same task
`['received_at_minute = lowerBin(received_at, minute_in_nanos)']`

`['received_at_minute = (DateTime)lower_bin(received_at, minute_in_nanos)'] `

Linked to #2303

**Comment by jmao-denver** [comment]
A related but different issue is that when both Python and Java have symbols with the same name and both can be used in formula/filter evaluation.

**Comment by niloc132** [comment]
See https://github.com/deephaven/deephaven-core/issues/3830#issuecomment-1593674478

**Comment by jmao-denver** [comment]
made unnecessary by #4388
