### ISSUE TITLE
Vector columns in the console have a misleading preview type of "String".

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#2317]
![vector-column-type-preview-console](https://user-images.githubusercontent.com/37232625/164559838-1681286f-bf84-4e47-8c33-5909bd226734.png)

The explanation for why this happens has to do with the displayed table not being exactly the same as the source table, meaning, to get the rendering of values for the vector we generate a derived table with a string column for display purposes.

This seems to me to be a UI implementation detail tho, and saying "String" as the type of that column is confusing for users.

**Comment by rcaudy** [comment]
I don't think the UI is doing anything special, here. Just faithfully displaying type and description. We *could* do something special, I suppose, like parse description and replace type with that. But it might be misleading about whether the data is a preview.

**Comment by nbauernfeind** [comment]
A quick reproducer in groovy:
```groovy
import io.deephaven.engine.util.TableTools
import io.deephaven.vector.DoubleVectorDirect
import io.deephaven.engine.context.ExecutionContext
ExecutionContext.getContext().getQueryLibrary().importClass(DoubleVectorDirect.class)
t = TableTools.emptyTable(1).update("V = new DoubleVectorDirect(0.0, 1.0)")
```

I added Vector support to barrage in #1989, so we could send the entire vector directly to the UI. However, we apply an array preview to all array types including `int[]` as we assume that the user prefers a potentially truncated preview.
