### ISSUE TITLE
Column type previews in the console for array types show cryptic Java abbreviations.

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#2320]
eg, `double[]` is displayed as `[D`

![array_type_preview](https://user-images.githubusercontent.com/37232625/164570344-6caf0145-62dd-430e-89d1-4bbbeaedaefa.png)

**Comment by nbauernfeind** [comment]
The is the Java name for a double[]. The UI is likely using the `deephaven:type` metadata which is the `getCanonicalName` on the class object.

Maybe we should send a human readable type for `type` and `javaType` for the [existing] one we use to match up deserialization.

**Comment by nbauernfeind** [comment]
I was wrong; we are using `Class#getName` instead of `Class#getCanonicalName` -- which has pretty text for things like `double[]`. I've put up a PR that cleans up the preview name.
