### ISSUE TITLE
Consider aircompressor

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2355]
Investigate with https://github.com/airlift/aircompressor for improved compression performance, and the ability to get rid of liblzo dependency: https://github.com/deephaven/deephaven-base-images/blob/main/server/02-slim-base/install.sh#L8-L11

**Comment by niloc132** [comment]
Closed, was resolved in June 2022 release, most of the platform specific codecs are replaced with something more generic.
