### ISSUE TITLE
listFlights does not work against python session

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2360]
It seems like listFlight against a python session does not work (empty list returned). listFields *does* work. At least since 0.11.0.

Tested with a python console session and the java client examples io.deephaven.client.examples.ListTables and io.deephaven.client.examples.SubscribeToFields.

**Comment by nbauernfeind** [comment]
It looks like the `PythonDeephavenSession#getVariables()` needs to return a Map that unwraps the python variables.
