### ISSUE TITLE
Preserve stream semantics over barrage

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2377]
It would be nice if stream table semantics were preserved over barrage.

This would allow nice data-mesh applications where workers exporting stream tables could be purpose-built as ingress/egress points.

Discussed with @nbauernfeind and @rcaudy, the implementation would likely be easy.

**Comment by jcferretti** [comment]
To make this issue more self-container for people with less Streaming Table experience (eg, me).

This looks like the updates you could get from a streaming table today (4 UGP ticks):
* add 0-9,
* remove 0-9, add 10-19
* remove 10-19, add 20-29
* remove 20-29, add 30-39

Coalescing those 4 in barrage today (what you get today, with barrage not "streaming table aware" ):
* add 30-39

Coalescing those 4 in barrage, what "you would want":
( add 0-39

That is one possible way it could happen.  You might also get (for the same data):
* add 0-9,
* remove 0-9, add 10-19
* remove 10-19, add 0-9
* remove 0-9, add 30-39
Coalescing those 4 in barrage today (what you get today, with barrage not “streaming table aware” ):
* add 30-39
Coalescing those 4 in barrage, what “you would want”:
* add 0-39

Specifically, there is no assumption of an increasing index space; that is not required nor necessary.
the contract for the streaming table is:

```
update.removed = getPrevIndex()
update.added = getIndex()
update.modified = Index.EMPTY
update.modifiedColumnSet = MCS.EMPTY
update.shifted = IndexShiftData.EMPTY
```

**Comment by jcferretti** [comment]
Ref the previous comment, Charles believes in practice what we are doing is:

* add 0-9,
* remove 0-9, add 0-9
* remove 0-9, add 0-9
* remove 0-9, add 0-9
