### ISSUE TITLE
very large timeTable does not render

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2436]
```groovy
t = timeTable(new DateTime(0), "00:00:01")
```

works

```groovy
t = timeTable(new DateTime(0), "00:00:00.1")
```

does not. It renders as an empty table in the UI, and reports a negative number of rows. The underlying data structure appears to work `println(t.size())` appears correct.

**Comment by devinrsmith** [comment]
No indication from browser logs or server that things are wrong, just that the table is empty and hovering over the column indicates negative size.

**Comment by devinrsmith** [comment]
> It’s definitely client side. Worker to worker pulls the table in. (Though it is 16B rows… and after the client gets the initial snapshot the server runs out of memory constructing the second — 16B rows is 96GB of RAM which [naturally] exceeds the heap.)

> I traced the RangeSet deser and it seems to handle long values just fine. The error has got to be further down from the RowSet/RangeSet parser.

> the server side BarrageMessageProducer sees a VP request for rows 0-19. And appears to build a valid snapshot for them.
> And I see it write 500+ bytes… so I think it actually sent the VP for 0-19.
> Maybe it is getting confused between addedRows and includedRows? (but w.r.t. long vs int? or maybe limiting to table size which it has already truncated somehow)

**Comment by mofojed** [comment]
It may be client side API, but seems error seems to be lower than UI. Open up a JS API page like http://localhost:10000/jsapi/table_basic.html and then run this in the browser console:
```
var session = await connection.startSession('groovy');
var result = await session.runCode('tt = timeTable(new DateTime(0), "00:00:00.1")');
var tt = await session.getTable('tt')
var listener = tt.addEventListener(dh.Table.EVENT_UPDATED, event => {
    console.log('Received update', event.detail)
});
tt.setViewport(0, 20)
```
The viewport update that comes contains an offset of -1 and zero rows:
![image](https://user-images.githubusercontent.com/4505624/170494451-e4392190-bfd1-4acf-a73a-1e56dff0b337.png)

Digging into the API side a bit...

**Comment by jjbrosnan** [comment]
This happens in the Python API as well

**Comment by mofojed** [comment]
JS API is getting the snapshot, but the `snapshot.getTableSize()` is returning `-644146485`, causing it to break on this line without including any rows: https://github.com/deephaven/deephaven-core/blob/fb3a55cf6c75d4c176b51e06806dd58d7a06882d/web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java#L1115

![image](https://user-images.githubusercontent.com/4505624/170499350-9b70e5c7-7386-42c2-8356-b131e85f4ce7.png)

**Comment by mofojed** [comment]
Looks like the error is in BarrageUtils? Going to ask @nbauernfeind or @niloc132 to take a closer look.

I see the added RangeSet is created, and it has a fairly large range for some reason:
![image](https://user-images.githubusercontent.com/4505624/170500500-b93e17df-e2b9-4d39-ace7-59f37b399644.png)

But then added.size() produces the `-644146485` number. Easy to reproduce on the JS API page, can put a breakpoint in dh-core in the `createSnapshot` method to debug

**Comment by mofojed** [comment]
For some reason we're casting the size to an int when we're subtracting it, then converting back to long: https://github.com/deephaven/deephaven-core/blob/fb3a55cf6c75d4c176b51e06806dd58d7a06882d/web/shared-beans/src/main/java/io/deephaven/web/shared/data/Range.java#L113
This causes an overflow in this case:
```
this$static.last
09:57:33.306 16535734029
09:58:31.412 toInt_0(this$static.last)
09:58:31.444 -644135155
```
![image](https://user-images.githubusercontent.com/4505624/170503286-34bd4390-dde5-4a30-bb8c-293e9de9dfd3.png)
