### ISSUE TITLE
History panel not painting properly

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2450]
**Description**

Sometimes the `Command History` panel does not display any history when it should. Sometimes scrolling causes it to refresh.

**Steps to reproduce**
1. Start a worker and connect a web client GUI to it. Your history panel might or might not display.

**Expected results**

`Command History` shows

**Actual results**

Sometimes it doesn't.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: Head of main
 - OS: OSX
 - Browser: Chrome Version 101.0.4951.64 (Official Build) (arm64)
 - Docker: N/A

**Comment by mofojed** [comment]
This is related to https://github.com/deephaven/web-client-ui/issues/325, closing this ticket in favour of the web-client-ui ticket.
