### ISSUE TITLE
Web IDE Select Distinct Values results in "realized table is closed, expected status DONE, instead is ACTIVE"

### ISSUE THREAD

**Issue by SuperTails** [deephaven/deephaven-core#2452]
**Description**

Trying to Select Distinct Values using the Web IDE results in an AssertionError.

**Steps to reproduce**
1. `docker-compose up`
2. Open up the Web IDE (`http://localhost:10000/ide/`)
3. Run
```python
from deephaven_legacy.tutorials.crypto_trades import *

crypto_streaming = ticking_crypto_milliseconds(25)
```
4. In the top-right corner of the table, use the dropdown menu to Select Distinct Values
5. After selecting any column, the table immediately disappears with an AssertionError.

**Expected results**

I would expect to see a listing somewhere of the distinct values in the selected column.

**Actual results**

The table disappears immediately upon selecting any column, showing the following error:
`Error: java.lang.AssertionError: realized table is closed, expected status DONE, instead is ACTIVE`

**Additional details and attachments**

Doing the same operation programmatically using
`distinct = crypto_streaming.select_distinct(formulas=["Instrument"])`
works as expected.

**Versions**
 - Deephaven: Commit e46635e182cc396a1adf76867329ceed339443eb
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Docker: 20.10.12

**Comment by mofojed** [comment]
Closing in favour of https://github.com/deephaven/web-client-ui/issues/193
