### ISSUE TITLE
Python client and server have naming conflicts for `Table.snapshot`

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2454]
The python client and server both have `Table.snapshot` methods, but these methods are not the same.  This makes code developed for the client or server non-portable to the other.  This problem needs to be resolved by having distinct names for the distinct snapshot operations.

When this change is made, the `pyclient` `README.md` and the `pyclient/docs/source/examples.rst` must be changed to be consistent with the new naming.

**Comment by devinrsmith** [comment]
With recent development around https://github.com/deephaven/deephaven-core/pull/3092, may be a good time to fix this.
