### ISSUE TITLE
Select/Update do not propagate Blink Table attribute

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#2474]
While `Table.view` and `Table.updateView` do propagate the Blink Table attribute, `Table.select` and `Table.update` do not.

Even for a blink table there could be some performance improvements by using select/update over their lazy counterparts.

Is there a counter argument why they should not?

**Comment by rcaudy** [comment]
Right now, there's no attribute copying for select or update at all: 

`io.deephaven.engine.table.impl.MemoizedOperationKey.SelectUpdateViewOrUpdateView#copyType`:
```
                case Select:
                case Update:
                    // turns out select doesn't copy attributes, maybe we should more accurately codify that
                    return BaseTable.CopyAttributeOperation.None;
```

I have no philosophical objection to changing this.
