### ISSUE TITLE
Go client API tests should be run as part of CI

### ISSUE THREAD

**Issue by SuperTails** [deephaven/deephaven-core#2523]
In order to avoid silent breakage when the protocol is changed, tests for the new Go client should be run in CI.
The setup for the protobuf compiler for Go is already (somewhat) done, as well as some modifications to support the test environment. This needs CI support for:
1. Installing Go
2. Transferring over the generated files
3. Running `go test -v ./...`

**Comment by chipkent** [comment]
What exactly do you mean by "generated files"?  You potentially want to check in the generated go files.  I'm sure @niloc132 has an opinion.
