### ISSUE TITLE
Wrap python script session BindTableToVariableRequest

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2543]
There's a usability issue when a client binds a table to a variable (`BindTableToVariableRequest`) against a python script session, and later tries to interact with that variable with script code. The table is bound "raw" - ie, without the `deephaven.table.Table` wrapper.

From an implementation standpoint, we need to figure out whether we want to wrap all `io.deephaven.engine.util.ScriptSession#setVariable` in the language-appropriate wrappers, or we only want to do this for `BindTableToVariableRequest`.

**Comment by nbauernfeind** [comment]
Can the PythonDeephavenSession's setVariable wrap the few types that we care about as their PyObject equivalents? This feels like the place so that fixes extend to any kind of supported script session.

**Comment by jmao-denver** [comment]
@pete-petey ran into the exact same problem when he tried to run a query on a table imported from CSV through the WebUI. This could very well be a bad first-impression issue for us.
