### ISSUE TITLE
`replicateAllSafe` does not correctly regen license headers

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#2574]
**Description**

Calling `replicateAllSafe` does not regen license headers correctly.

**Steps to reproduce**
1. Checkout a clean branch
2. Execute `./gradlew :replication-static:replicateAllSafe`
3. Execute `git status` to view changed files

**Expected results**

No changes to generated files

**Actual results**

1000+ files changed after replication

**Comment by lbooker42** [comment]
One more thing, JavaPoet (used for OA hashing natural/asof joins and aggby) does not currently create license headers. So every call results in modifications to 500+ files.

**Comment by devinrsmith** [comment]
Ref https://github.com/deephaven/deephaven-core/pull/2516

**Comment by nbauernfeind** [comment]
This is fixed with #2664.
