### ISSUE TITLE
Ticking table join operations should raise an exception when invoked without holding a UGP lock

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#2596]
These join operations are considered to be unsafe, but an exception isn't guaranteed when they are performed without holding the UGP locks. This behavior isn't consistent with other unsafe Table operations.

When resolved, skipped test cases in py/server/test/test_ugp.py needs to be un-skipped.

**Comment by rcaudy** [comment]
This should generally be checked and enforced for methods that are not annotated `@ConcurrentMethod`.
