### ISSUE TITLE
EPIC: Refactor DB module into multiple engine modules

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#261]
This specifically includes our`com.fishlib.base.clock.Clock` implementations, per Chip, as they're all over the place.
We need to make some smart modular decisions, ideally separating types from the query engine, etc.

**Comment by pete-petey** [comment]
Might do some renaming in Aug.
The actual split will be Sept-2021 Milestone, not Aug.

**Comment by rcaudy** [comment]
This is as done as it's going to be for now. We can split engine-table further at low urgency as required.
