### ISSUE TITLE
I just wana ask is there some one still maintain https://github.com/deephaven/SuanShu ？？

### ISSUE THREAD

**Issue by oswardlx** [deephaven/deephaven-core#2646]
As a [user or stakeholder type], I want [some software feature] so that [some business value]

**Comment by chipkent** [comment]
Yes, we still do maintain `deephaven/SuanShu`.  If there is a feature you want included, please create a PR or feature request, and we can work on getting it into a release.

I will note that `deephaven/SuanShu` is based off of the last available Open Source release of SuanShu.  There are later closed releases that are available at https://nm.dev/ (I think).

**Comment by oswardlx** [comment]
thanks
