### ISSUE TITLE
Feature suggestion: Configuration gRPC service

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2668]
Subtask for #2564 

As a GUI client author/consumer, I would like to know what authentication methods are supported/suggested by the server, and any values to have suggested when trying to use them.

As stated, this will come in the form of "before I manage to authenticate, what should I know", but it might also make sense to provide a "after I have successfully authenticated, what should I know" to provide other details about the server and how it is set up. Script session language, runtime version of various tools are some examples that might be gated by authentication settings, DHE also includes features like enabled/deployed plugins, custom logo/docs/help info.

Example use cases for pre-auth config:
 * Server only has SAML enabled, user shouldn't first attempt anon access, then username/password, etc
 * Server has multiple SAML providers, user should pick from the list rather than guessing what IDP they need to visit for their own account
 * Server configuration is set to allow and prefer anon access, but permit some other authentication, to encourage quick conversion of users, but support richer experience for authenticated users
 * Server configuration is set to permit anon access, but always require them to click past the login prompt, so that they are first given shown that the experience will be better with an account

--

Proposed API would be a pair of unary gRPC calls, each of which returns a repeated pair of strings, for key and value. In time we could make value more generic, but we should probably map as closely as possible to DHE (for compat in deephaven/web-client-api), and as closely to the existing config system (to allow administrators so add their own configuration settings that will be accessible by clients. Could also offer a single method, and have it return different values pre- and post- authentication, but it might be clearer to explicitly provide two (as DHE does internally, so that the JS API can expose them differently to the API consumer).
```
service ConfigService {
  rpc GetAuthenticationConstants(AuthenticationConstantsRequest) returns (AuthenticationConstantsResponse) {}
  rpc GetConfigurationConstants(ConfigurationConstantsRequest) returns (ConfigurationConstantsResponse) {}
}

message AuthenticationConstantsRequest {}
message ConfigurationConstantsRequest {}
message AuthenticationConstantsResponse {
  repeated ConfigPair config_values = 1;
}
message ConfigurationConstantsResponse {
  repeated ConfigPair config_values = 1;
}
message ConfigPair {
  string key = 1;
  oneof value {//leave room for more types
    string string_value = 2;
  }
}
```

Server configuration then will have two new properties, one to list pre-auth config properties to provide to clients, and one for post-auth config properties.

**Comment by devinrsmith** [comment]
Related to https://github.com/deephaven/deephaven-core/issues/2390

**Comment by devinrsmith** [comment]
IMO, any values that come out of GetConfigurationConstants would need to be explicitly on an "allowed" list (ie, we can't just universally take system properties or Configuration properties). Otherwise, there is potential for secrets to be leaked. Most obvious are SSL passphrases; but 3rd party applications could be configuring any number of secrets.

**Comment by niloc132** [comment]
Yes - DHE solves with as you describe, with an explicit "allow" list for auth settings (admin configurable), and a hardcoded set of properties for general settings. I intend to offer an allow list for both in DHC, so they are managed in the same way, and more flexible for clients we don't directly manage.

**Comment by mofojed** [comment]
Should include the server version information when this is implemented.
