### ISSUE TITLE
TableReplayer fails if start_time is after the first Timestamp in the Table

### ISSUE THREAD

**Issue by JoshuaKoskie** [deephaven/deephaven-core#2740]
**Description**

can't start replaying a portion of a table. Have to set the table start time at or before the first Timestamp. 

**Steps to reproduce**
Run the following code in a web UI running python.
```python
from deephaven import empty_table
from deephaven.time import to_datetime
from deephaven.replay import TableReplayer

t = empty_table(100).update(["StartTime = '2022-08-16T11:23 NY'", "Timestamp = StartTime + i * SECOND"])

start_time = to_datetime('2022-08-16T11:24 NY')
end_time = to_datetime('2022-08-16T11:25 NY')

replayer = TableReplayer(start_time, end_time)
replayed_table = replayer.add_table(t, "Timestamp")
replayer.start()
```

**Expected results**

a replayed table starting at 11:24

**Actual results**

```
Value: failed to add a historical table. : RuntimeError: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < LogicalClock.DEFAULT.currentStep(), instead lastNotificationStep == 76, LogicalClock.DEFAULT.currentStep() == 76.
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/replay.py", line 60, in add_table
    replay_table = Table(j_table=self._j_replayer.replay(table.j_table, col))
RuntimeError: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < LogicalClock.DEFAULT.currentStep(), instead lastNotificationStep == 76, LogicalClock.DEFAULT.currentStep() == 76.
```
**Versions**
 - Deephaven: 0.14.1
 - OS: 12.2.1
 - Browser: Chrome 101.0.4951.64
 - Docker: 4.10.1

**Comment by jjbrosnan** [comment]
This issue was fixed in a previous update - I forget which, but I believe it was Ryan who fixed it. Now, the table will start replaying at the correct time. If the start time is after all times in the table, it instantly populates. If the start time is before that of the first row, it waits. And if it's part way through, it will populate with all rows up to and including the start time, and then replay normally.
