### ISSUE TITLE
Deephaven-server should support JS plugins included in python plugin modules

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#2771]
There is currently no way to install/register a JS plugin when using the `deephaven-server` python module.
As a developer, I want to be able to include a JS plugin from [deephaven-js-plugins](https://github.com/deephaven/deephaven-js-plugins) in a python module, such as [deephaven-plugin-matplotlib](https://github.com/deephaven/deephaven-plugin-matplotlib), [deephaven-plugin-plotly](https://github.com/deephaven/deephaven-plugin-plotly) and have it registered when the python module is imported.

**Comment by devinrsmith** [comment]
Duped by #2772
