### ISSUE TITLE
Improve hash function for `RowRedirection` implementations

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2784]
The default hash function results in significant collisions some row set patterns, including those built by partitioned tables. We should change it.

**Comment by rcaudy** [comment]
This is really about:
`io.deephaven.util.datastructures.hash.HashMapK1V1`

Which hashes using:
`gnu.trove.impl.HashFunctions.hash`

We should experiment with alternative hash codes.

**Comment by rcaudy** [comment]
We should also revisit uses of `TLongHashMap` and `TLongHashSet` for row key mapping/storage.

**Comment by devinrsmith** [comment]
I think we should split off a new ticket for transitioning other maps to KnVn maps.
