### ISSUE TITLE
Subplots not available when plotting OHLC plot

### ISSUE THREAD

**Issue by hhashim1** [deephaven/deephaven-core#2835]
Description:
An option to create subplots below the OHLC plot is needed to validate the data and calculations. While this can be accomplished by having separate charts, it saves a lot of time and much easier to have all the charts in one chart window. 

OHLC chart would have the OHLC data together with `plot_xy` plots and subplots would have other indicators and bar plots that cannot be charted over OHLC plot/pane. They share the same X axis which is time however they have a different Y axis.

Please see the below screenshot from tradingview. All stock trading softwares allow subplots as they are necessary to view all of the data together.

The below image has 6 subplots. They could be a bar, line, or any other type of plots. Tradingview would be a good tool to look at options when it comes to charting.

![image](https://user-images.githubusercontent.com/62855649/189680453-4cf2995e-ea7c-481b-b3c6-c458461d6f49.png)

**Comment by hhashim1** [comment]
I am unable to make my code work based on your suggestion.

```
figure = Figure(figure(2,1))
bar_chart = figure.figure_title("O:TSLA220902P00273330")\
        .new_chart(row=0,col=0) \
        .plot_ohlc(series_name="t4", t=t4.where(filters=["symbol = 'O:TSLA220902P00273330'"]), x="tdate", open="bar_open", high="bar_high", low="bar_low", close="bar_close")\
        .new_chart(row=1,col=0) \
        .plot_xy(series_name="BB_U_1_0", t=t4.where(filters=["symbol = 'O:TSLA220902P00273330'"]), x="tdate", y="BB_U_1_0")\
        .show()
```

Here is the error:
```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '0a850b56-f4ba-435a-9467-7229b65c814d' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'TypeError'>
Value: 'Figure' object is not callable
Line: 1
Namespace: <module>
File: <string>
Traceback (most recent call last):
  File "<string>", line 1, in <module>```

**Comment by mofojed** [comment]
Subplots are now available, but we still cannot mix OHLC plots and XY plots in the same chart. E.g. doing something like:
```
from deephaven import time_table
from deephaven.plot import Figure

tt = time_table("00:00:00.01").update(["X=0.01*ii", "Y=ii*ii", "S=sin(X)", "C=cos(X)", "T=tan(X)"]).tail(1000)

f = Figure() \
    .plot_xy("Y", t=tt, x="X", y="Y") \
    .plot_xy("S", t=tt, x="X", y="S") \
    .plot_xy("C", t=tt, x="X", y="C") \
    .plot_xy("T", t=tt, x="X", y="Y") \
    .plot_ohlc("T4", t=tt, x="X", open="Y", high="S", low="C", close="T") \
    .show()
```

**Comment by mofojed** [comment]
#2988 has merged ans this ticket should now be complete.
