### ISSUE TITLE
Session ordering to simulate a single bidi grpc stream

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#29]
This could let GRPC clients send commands before earlier ones have even been handled and not need to worry about them getting mis-ordered in the http2 proxy/server.

Instead, for now clients must wait until their previous command completed before starting the next one.

DoPut has out-of-band sequencing for BarrageMessage's. This logic should be lifted, and unit tested, for re-use by patterns like these. (See the usage of RAPriQueue in FlightServiceGrpcImpl.)

**Comment by nbauernfeind** [comment]
I updated the description to reflect work that was done for DoPut in #610. It can be lifted, and ought to be unit tested, for re-use in this case and all other out-of-band scenarios.

**Comment by nbauernfeind** [comment]
Closed by #412. See BrowserStream and the BrowserFlightServiceGrpcImpl for sample usage.

I edited the title to be clear. Script Sessions must use the serial queue for now as each script holds the exclusive lock when running. This idea was still useful in other contexts, however (such as the Flight client-streams that jsapi needs to send).
