### ISSUE TITLE
Connect to Deephaven worker from Python applications

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#292]
Either from the package or from cheese-shop I should be able to install a series of packages to allow me to connect to the Deephaven worker from my Python application(s).  From my external Python application I want to be able to inherit Deephaven data in any of the following forms:
- Pandas dataframes
- Arrays via getColumn() and getDirect[]
- Deephaven table objects

**Comment by pete-petey** [comment]
Link to Epic #659

**Comment by jmao-denver** [comment]
the new Python client prototype supports all the requested functions.
