### ISSUE TITLE
EPIC: Kafka support

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#293]
- I want to be able to easily connect to a single or multiple Kafka topic(s).  I want to support a happy path…. where I can provide 4-5 arguments like: schema-service url, topic-url, credentials, additional filtering information related to the topic, maybe a starting sequence number.  I will expect Deephaven to handle and fully relieve me of worrying about routing tables, in-worker ingestion services, and schema creation.  

_Revising the remainder of the description: the MVP version of community's Kafka support likely will *not* have any support to ease publication._
- I want to be able to publish streaming data to Kafka topics with a simple writeKafka() capability that writes to a Kafka-interface I control (outside of DH).  I want to be able to provide minimal configuration: Credentials, an interface-url, zookeeper broker endpoint.

**Comment by rcaudy** [comment]
I don't think this was closed intentionally.

**Comment by rcaudy** [comment]
Closing. We've met our "MVP" Kafka goals. We're planning a September 20201 epic for Kafka publishing.
