### ISSUE TITLE
`dh_args` parameter does nothing when using Deephaven as a Library

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#2964]
**Description**
There does not appear to be a way to set a configuration value when using Deephaven as a library. There is a parameter `dh_args` on the server.py object, but it does not appear to be meaningfully used at all.

**Steps to reproduce**
1. In a Google colab notebook ([example here](https://colab.research.google.com/drive/1Nz-ahfZQW7Hi3f7_X1LI12RTr50130Qv)), start a server up and pass in a configuration value:
```
from deephaven_server import Server
import portpicker
dh_port = portpicker.pick_unused_port()
# Don't require http2 in google colab setting
s = Server(port=dh_port, jvm_args=["-Xmx4g"], dh_args={'http.requireHttp2': False})
s.start()
```
2. Open the Deephaven IDE in an iframe:
```
from google.colab import output
output.serve_kernel_port_as_iframe(dh_port, '/ide/index.html')
```

**Expected results**
2. IDE starts up, and doesn't complain about HTTP2 not being available

**Actual results**
2. Error is shown, http2 is unavailable:
`Error: The server connection is not using http2, so streams and metadata may not behave as expected. The client may be connecting improperly, or a proxy may be interfering.`
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/4505624/194313807-1cf2bd3d-fe5d-42b6-8fcd-1cf9a3b64f0a.png">

**Additional details and attachments**
`dh_args` param gets passed into `EmbeddedServer` here: https://github.com/deephaven/deephaven-core/blob/362523fbd9afe661da0c5fdfa7b7e31e5c096894/py/embedded-server/deephaven_server/server.py#L44
However, in `EmbeddedServer`, that param `dict` never gets used: https://github.com/deephaven/deephaven-core/blob/362523fbd9afe661da0c5fdfa7b7e31e5c096894/py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java#L80

**Comment by devinrsmith** [comment]
So, I see the value in being able to set ad-hoc Deephaven configuration values _without_ washing them through system properties. The only mechanism we have for doing that today is a configuration file. The limitation is true with the native application as well: https://deephaven.io/core/docs/how-to-guides/configuration/native-application/.

It might be reasonable to consider an environment variable to serve such a purpose: `DEEPHAVEN_PROPERTIES`, or something similar. Of course, this assumes a specific language / parser, and I know Colin has designs on a toml-based configuration file in the future.

As a workaround, a library _could_ create a `<tmpDir>/my.prop` file with the contents `dh_args` and configure the server to point to it. Ideally, `<tmpDir>/my.prop` would also include `<configDir>/deephaven.prop`, although that is potentially messing with the server be the ground source of truth for bootstrapping. I also forget off the top of my head have includefiles + overwriting properties works (which one wins).

**Comment by devinrsmith** [comment]
As a specific workaround for this example, you _can_ wash through jvm_args:

```python
s = Server(port=dh_port, jvm_args=["-Xmx4g", "-Dhttp.requireHttp2=false"])
```
