### ISSUE TITLE
MicroTimer/DateTimeUtils.currentTime()/DateTime.now() can return wrong time 

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#2992]
The `io.deephaven.util.clock.MicroTimer` computes a fixed offset from System.nanoTime() so that it can return unix time that ticks based on nanoTime(), but this causes it to return inaccurate results when the clock jumps(/slews, probably), because there's no way to 

```
println(currentTime())
println(millisToTime(System.currentTimeMillis()))
2022-10-12T14:50:15.692889000 NY
2022-10-12T14:50:15.652000000 NY
```

After manually rolling my clock back a few minutes:
```
println(currentTime())
println(millisToTime(System.currentTimeMillis()))
2022-10-12T14:50:43.948189000 NY
2022-10-12T14:47:40.934000000 NY
```

As @devinrsmith noted there appear to be three reasonable ways to obtain the time, depending somewhat on the environment/application:

1. Use `System.currentTimeMillis()` (and multiply by 1000 to fake a currentTimeMicros)
2. Use `Instant.now()` — be aware of potential for extra GC
3. Use `jdk.internal.misc.VM` — extra setup involved for external consumption

**Comment by devinrsmith** [comment]
I think it may be worthwhile to plumb better abstractions

for example:

`io.deephaven.server.barrage.BarrageMessageProducer#schedulePropagation`:
```java
final long now = scheduler.currentTime().getMillis();
```
`io.deephaven.time.ClockTimeProvider`:
```java
    public DateTime currentTime() {
        // TODO: Consider adding last-value caching.
        return DateTimeUtils.microsToTime(clock.currentTimeMicros());
    }
```

also, it's reasonable to ask for `io.deephaven.engine.table.impl.select.ClockFilter`, do we really need microsecond precision?

**Comment by devinrsmith** [comment]
`io.deephaven.engine.table.impl.select.AutoTuningIncrementalReleaseFilter`:

```java
 final long cycleDuration = (cycleEnd.getNanos() - lastRefresh.getNanos());
```

We should likely use a different abstraction for calculating deltas, instead of `DateTime.getNanos() - DateTime.getNanos()`, we don't need epoch nanos.
