### ISSUE TITLE
Autocomplete suggestions make no sense

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3008]
**Description**

Autocomplete suggestions make no sense. Possibly because #479 was never completed.

**Steps to reproduce**
1. Open a console session
2. Type a snippet like `update().` and look at the autocomplete suggestions

**Expected results**
2. There should be no suggestions because the code `update().` doesn't really make sense. In other cases where there should be valid suggestions, it should suggest valid code.

**Actual results**
2. There's a lot of suggestions that appear to be Groovy autocomplete suggestions. In other cases where there should be valid suggestions, it doesn't suggest anything or suggests garbage

**Additional details and attachments**

![image](https://user-images.githubusercontent.com/4505624/196985859-f668c2b1-dea8-4db6-9258-e54dad5552cf.png)

**Versions**
 - Deephaven: 0.18.0
 - OS: Ubuntu
 - Browser: Chrome

**Comment by rcaudy** [comment]
Should we disable python autocomplete for now? I think that's the consensus opinion.

**Comment by mofojed** [comment]
Jedi Autocomplete has much improved python autocomplete, and this is no longer an issue: https://github.com/deephaven/deephaven-core/pull/3114
