### ISSUE TITLE
Standard non-compliant code in the query library

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#3021]
Commit feb6c8edab8459c393217dc11e7b14c6897d7a3a introduced a number of changes that do not comply with the standards of the query library.  This code should have been reviewed by @kosak and @chipkent before merging.  This is a user library, so the standard is higher than other parts of the code.

1. All methods should be fully documented and consistent with the other docs in the file.
2. All methods should be essentially 100% unit tested.
3. I think `public static <T> T[] forwardFill(final T[] values)` may cause us problems.  The generic stuff should go at the top of the file.  Most of the generic methods have Obj in the name to avoid nasty collisions.  This needs a very careful look to assess the likelihood of causing problems.  Full unit tests will help identify such collisions.
4. `cumMin` and `cumMax` don't match the naming conventions of similar funcs, e.g. `cumsum` and `cumprod`.

**Comment by lbooker42** [comment]
Closed by #3039
