### ISSUE TITLE
web UI not allowing panels to be resized

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3059]
PR #3049 seems to have broken my ability to resize panels in the web UI. web console logs showing "TouchEvent is not defined"

Easy to reproduce in main, `./gradlew server-jetty-app:run -Pgroovy`, open web ui, create notebook if none open, try to resize.

May also be able to reproduce like:

```
docker pull ghcr.io/deephaven/server:edge
docker run --rm -p 10000:10000 ghcr.io/deephaven/server:edge
```

**Comment by mofojed** [comment]
Reproducible in FireFox 106.0.3, not reproducible in Chrome. Almost certainly caused by converting golden-layout to TS: https://github.com/deephaven/web-client-ui/pull/796

```
Uncaught ReferenceError: TouchEvent is not defined
    _getCoordinates DragListener.ts:136
    onMouseDown DragListener.ts:66
    jQuery 2
DragListener.ts:136:6
```

**Comment by mofojed** [comment]
Before conversion the `_getCoordinates` function was:
```
  _getCoordinates: function (event) {
    event =
      event.originalEvent && event.originalEvent.touches
        ? event.originalEvent.touches[0]
        : event;
    return {
      x: event.pageX,
      y: event.pageY,
    };
  },
```

After conversion, it is:
```
  _getCoordinates(event: JQuery.TriggeredEvent) {
    const baseEvent =
      event.originalEvent instanceof TouchEvent
        ? event.originalEvent.touches[0]
        : event;
    return {
      x: baseEvent.pageX,
      y: baseEvent.pageY,
    };
  }
```

According to caniuse, `TouchEvent` _should_ be available in FireFox: https://caniuse.com/?search=touchevent
However, it looks like it's also not supported in Safari, so should rip it out anyway.

**Comment by mofojed** [comment]
Seems like `TouchEvent` may only be defined on FireFox mobile: https://bugzilla.mozilla.org/show_bug.cgi?id=1693172
Either way it's not defined, we only use it in two places so just fix that.
