### ISSUE TITLE
Broaden the types of indices that `Table.slice` supports

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#3130]
`Table.slice()` returns subsets of a table's rows based upon the `i` index of the rows.  Slicing is allowed from the beginning or the end of the table.

As discussed in https://github.com/deephaven/deephaven-core/pull/3110#discussion_r1033839549, we should be supporting slices of the form `x[-7:8]`, where the first slice index is negative, and the second slice index is positive (`irstPositionInclusive < 0 && lastPositionExclusive > 0`).

The documentation for the following need to be updated.
- [ ] Java
- [ ] Python

**Comment by malhotrashivam** [comment]
From what I understand, for the following input, 
```
source = emptyTable(10).update("X=i")  // source = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = source.slice(-5, 9)
```
We should get result as rows `[5, 6, 7, 8]`

How should we handle a scenario like the following
```
source = emptyTable(10).update("X=i")  // source = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = source.slice(-5, 2)
```
Should we return an empty set or an exception?

For reference, in the current code, if we run the following
```
source = emptyTable(10).update("X=i")  // source = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = source.slice(7, -5)
```
We get an empty set `[]`. So should we follow the same convention and return empty set in the slice(-5, 2) case?

**Comment by malhotrashivam** [comment]
Python also returns an empty set, as shown in the following example
```
>>> x = list(range(10))     # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> x[7: -5]                # Returns []
```
So I am keeping the same behavior in our code too.
