### ISSUE TITLE
DebugAwareFunctionalLock for SharedLock

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3137]
https://github.com/deephaven/deephaven-core/pull/3098 exposed that we weren't properly using DebugAwareFunctionalLock for SharedLock. It would be nice to have better debuggability for the shared lock.

**Comment by rcaudy** [comment]
The current implementation is a stack (stored in an `ArrayDeque`). That's not going to work with a shared lock. Maybe a map from `Thread` to stacks?
