### ISSUE TITLE
Increase scenario coverage for parallel update

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3198]
We would like to be able to parallelize `Table.update` and `Table.select` in more situations:
1. Intra-column: Reinterpreted writable sources should permit parallel population (`io.deephaven.engine.table.WritableSourceWithPrepareForParallelPopulation.supportsParallelPopulation`)
2. Inter-column: We could allow *one* stateful `SelectColumn` instead of zero

**Comment by nbauernfeind** [comment]
This is a duplicate-of/replaced-by the EPIC #4869.
