### ISSUE TITLE
Add `Table.slicePct`

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#3203]
The `Table.slice` operator is analogous to the `Table.head` and `Table.tail` operators.  The `Table.head` and `Table.tail` operators have `headPct` and `tailPct` methods.  `slice` should have `slicePct` to be complete and consistent with the other methods in the family.

**Comment by rcaudy** [comment]
This should take two non-negative `double` inputs. I think they should both be expressed relative to head.

**Comment by chipkent** [comment]
I don't think being relative to head is relevant in this operation.  Here `slicePct(0.25, 0.75)` would indicate the slice from the 25th to the 75th percentile.

**Comment by chipkent** [comment]
Linking:  https://github.com/deephaven/deephaven-core/issues/3130
