### ISSUE TITLE
QueryLanguageFunctionUtils cannot be regenerated (and currently contains manual modifications)

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#3262]
The `QueryLanguageFunctionUtils` class and its tests are historically generated by the QueryLanguageFunctionGenerator, but it not currently possible (or at least not straightforward) to run the generator, and manual changes have crept into `QueryLanguageFunctionUtils`.

We need to make the generator runnable again & update it so that its output includes the changes that were made manually.

**Comment by rcaudy** [comment]
Looks like the initial (and largest) divergence was in January 2022, when `BigInteger` and `BigDecimal` support were added.
