### ISSUE TITLE
BarrageTable to allow off-UGP ingestion in some use cases when not published

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3300]
We want this for `DoPut`, so we can deliver static data without involving the UGP or asking it to hurry up.

While we're at it, we should avoid the slightly-dirty fact that the (thankfully, not published) interim `BarrageTable` starts out refreshing, and enables previous tracking, etc.

**Comment by nbauernfeind** [comment]
This will also close out #803.
