### ISSUE TITLE
Python: Cannot apply both size and shape to points in a plot-by series

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3323]
**Description**

If you try and apply both a shape and a size to points in a plot-by series, only the shape is applied.

(Note: found this while implementing JS API/UI for plot shapes and sizes, https://github.com/deephaven/deephaven-core/pull/3246 and https://github.com/deephaven/web-client-ui/pull/981)

**Steps to reproduce**
1. Execute the following snippet:
```
from deephaven import empty_table
from deephaven.plot import Figure
import math

math_funcs = ["sin", "cos"]
shapes = ["SQUARE", "CIRCLE", "UP_TRIANGLE", "DOWN_TRIANGLE", "RIGHT_TRIANGLE", "LEFT_TRIANGLE", "DIAMOND"]
size = 50
# Unsupported shapes: ["ELLIPSE", "HORIZONTAL_RECTANGLE", "VERTICAL_RECTANGLE"]

# Create a generic table that has enough columns to display all the shapes
# Re-uses some of the funcs
t = empty_table(size).update([f"name=`` + shapes[(int)Math.floor(i / Math.ceil(size / {len(shapes)}))]", "x=i*0.1"])
for i in range(len(shapes)):
    t = t.update([f"y{i}=Math.{math_funcs[i % len(math_funcs)]}(x+{math.floor(i / len(math_funcs))})"])

# Create a plot by figure
p2 = Figure().plot_xy(series_name="Multi", t=t, by=["name"], x="x", y="y1").line(visible=True)
for i in range(len(shapes)):
    # apply both shapes and sizes to points
    p2 = p2.point(shape=shapes[i], multi_series_key=[shapes[i]], size=len(shapes) - i, visible=True)
p2 = p2.show()
```

**Expected results**
1. `p2` should appear, with each series having different shapes and sizes

**Actual results**
1. `p2` appears, but each series only has different shapes

**Additional details and attachments**

![image](https://user-images.githubusercontent.com/4505624/213205815-cd1dc055-1dd9-4112-a00a-d67044f7599c.png)

**Versions**
Engine Version: 0.20.0
Web UI Version: 0.23.0
Java Version: 11.0.16
Barrage Version: 0.5.0

**Comment by mofojed** [comment]
Debugging the problem a bit, it's because after processing the shape, it remove `multi_series_key` from the `non_null_args` array: https://github.dev/deephaven/deephaven-core/blob/09e43321b26e7b3417c4e55e39947f533387dff0/py/server/deephaven/plot/figure.py#L1637
Since `size` is processed afterward, it skips the ["size" and "multi_series_key" block](https://github.dev/deephaven/deephaven-core/blob/09e43321b26e7b3417c4e55e39947f533387dff0/py/server/deephaven/plot/figure.py#L1650) and only falls into the ["size" block](https://github.dev/deephaven/deephaven-core/blob/09e43321b26e7b3417c4e55e39947f533387dff0/py/server/deephaven/plot/figure.py#L1685). Since `multi_series_key` applies to multiple properties, it probably shouldn't be removed right away... need to update the generated code somehow.

**Comment by jnumainville** [comment]
@mofojed I see that multi_series_key is used similarly across several different plots. Is it safe to add some sort of multi_series_key removal prevention across all plots or does this fix need to be restricted to a subset of them?

**Comment by mofojed** [comment]
@jnumainville I think prevention across all plots is likely safe. By itself that param doesn't do anything, it basically only works with other params.
