### ISSUE TITLE
Feature request: Exponential Decaying Max UpdateBy operation

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3327]
Similar to #2760

This is an operation whose value is a decayed maximum. The maximum decays over time, until a new value bumps it back up to a higher value. You might want to answer the question "What is the maximum value we've seen in the last hour?" Of course, you could do that precisely with a windowed function, but by using a decayed construction with a stream table, we can compute it very efficiently (ie, no extra memory).

This sort of computation is commonly seen in various audio graphs - either frequency response graphs, or microphone input / speaker output; the graph will shoot up to the maximum, and then decay back down to 0.

**Comment by lbooker42** [comment]
Closed by #3671
