### ISSUE TITLE
Query cancellation not working

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#3345]
Query cancelation in consoles isn't working — there's no way to bail out of a query, whether relying on the engine or trying manually.

First, if I run the following two queries immediately after each other in a console, and press the "X" to cancel _both_ queries immediately afterward...

```groovy
myTable = emptyTable(125_000_000)
queryOpStart = System.currentTimeMillis()
myTableUpdated = myTable.update("Col1 = random()").update("Col2= random() * Col1").update("Col3=random() * Col2")
queryOpEnd = System.currentTimeMillis()

println "Query op completed after " + (queryOpEnd - queryOpStart) + "ms."
```
```groovy
println "Next query started " + (System.currentTimeMillis() - queryOpEnd) + "ms after the update() completed."
```

![image](https://user-images.githubusercontent.com/9516585/213840805-58a3b3c9-b750-41d8-ac97-ea329d9c9cc9.png)

...I get the following output, indicating (1) that the first query didn't abort early (between the `update()`s) and (2) that the second query still ran (even though I canceled it before it started).
```
Query op completed after 10350ms.
Next query started 348ms after the update() completed.
```
It's no different if all three formulas are collapsed into a single `update()` call.

The same thing also happens if I try a simple query (not involving the engine), and instead try manually checking for interrupts or hoping that `Thread.sleep()` throws an exception:

```groovy
loopStart = System.currentTimeMillis()
maxSleepMs = 20_000l

while(System.currentTimeMillis() - loopStart < maxSleepMs) {
    if(Thread.interrupted()) {
        println "Interruped; breaking"
        break;
    }
    Thread.sleep(1000)
}

println "Out of loop after " + (System.currentTimeMillis() - loopStart) + "ms."
```
```groovy
println "Next query started " + (System.currentTimeMillis() - loopStart) + "ms after the loop started."
```
```
Out of loop after 20005ms.
Next query started 20182ms after the loop started.
```

**Comment by rcaudy** [comment]
This duplicates #53, at this time we don't support query cancellation. I need to remind myself why that is, and see what we can do about it.

**Comment by rcaudy** [comment]
This is duplicative of https://github.com/deephaven/deephaven-core/issues/53
