### ISSUE TITLE
AggWAvg support for rollup()

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3350]
We currently have AggWSum support for rollup(), but not AggWAvg.

**Comment by kzk2000** [comment]
Ideally, everything under https://deephaven.io/core/docs/how-to-guides/combined-aggregations/ just works for rollups as well

**Comment by devinrsmith** [comment]
I'm not sure if we should create a ticket for each unsupported method, or maintain a single ticket.

For reference, here are the unsupported rollup ops:

* AggSpecApproximatePercentile
* AggSpecFreeze
* AggSpecGroup
* AggSpecFormula
* AggSpecMedian
* AggSpecPercentile
* AggSpecTDigest
* AggSpecWAvg

**Comment by kzk2000** [comment]
@rcaudy @devinrsmith do you have an ETA when **AggSpecWAvg** will be supported?
it would be great to have to compute things like avg fill price of an order from raw fill events
