### ISSUE TITLE
Go client unit test failures in CI

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3490]
We had failures reported on Sunday, March 5 and Monday, March 6's CI runs:

* https://github.com/deephaven/deephaven-core/actions/runs/4334668409/jobs/7568712072
* https://scans.gradle.com/s/ggv7pf7ctrjhe/console-log?task=:go:testGoClient
```
  === RUN   TestCrossJoin
      tablehandle_test.go:353: resultRec1 was too large
  --- FAIL: TestCrossJoin (0.06s)
```

* https://github.com/deephaven/deephaven-core/actions/runs/4340451456/jobs/7578994817
* https://scans.gradle.com/s/jns5nkasva3ho/console-log?task=:go:testGoClient
```
  === RUN   TestCrossJoinQuerySerial
      query_test.go:875: result1 was too large
  --- FAIL: TestCrossJoinQuerySerial (0.08s)
```

These seems to be somewhat random. A single failure each night, once for JDK 11, once for JDK 17.

**Comment by rcaudy** [comment]
I'm a little suspicious that this isn't testing a guaranteed condition, but I'd need to dig further into the test harness to be sure.

**Comment by chipkent** [comment]
The failures:
```
tablehandle_test.go:353: resultRec1 was too large
```
and
```
query_test.go:875: result1 was too large
```

The inputs to these are static but non-deterministic, which looks like the root of the problem.
