### ISSUE TITLE
Wrap `RingTableTools` in Python

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#3492]
**Description**

`io.deephaven.engine.table.impl.sources.ring.RingTableTools` is not wrapped in Python. It should be so that Python users can leverage it.

**Comment by supernomad** [comment]
fwiw in the mean time if you want to take say a `stream` table and push it into a ring table you can use this: 

```python
import jpy

from deephaven import DHError
from deephaven.table import Table

_JRingTableTools = jpy.get_type("io.deephaven.engine.table.impl.sources.ring.RingTableTools")

def stream_to_ring(table: Table, capacity: int) -> Table:
    try:
        return Table(j_table=_JRingTableTools.of(table.j_table, capacity))
    except Exception as e:
        raise DHError(e, "failed to create a ring table.") from e
```

as a quick and dirty hack to get this working for testing purposes 🙂
