### ISSUE TITLE
`coreClient.login` rejects with a "" error on failed auth

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#3498]
When trying to log in anonymously with anon auth disabled, `coreClient.login` rejects with an empty string error and doesn't trigger the `HACK_CONNECTION_FAILURE` event.

Expected:
Either reject with a proper error or trigger the `HACK_CONNECTION_FAILURE` with failure details.

**Comment by niloc132** [comment]
This is a bug in 0.21, and is already fixed in 0.22 and beyond - the server doesn't always send back an error message when authentication fails. Fixed in #3410, can be partially backported.

In 0.21 and beyond, the client also fails to notice that and give some better error message.
