### ISSUE TITLE
Backslash Crashes Console

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#3561]
**Description**

**Steps to reproduce**
1. Run Deephaven 0.20.1.
2. Type "println("Yo")" into a groovy console. It works.  
3. Type "\println("Yo")" and the console crashes with the message below and errors in the logs.
 
**Expected results**

I get a syntax error or something aside from a crash.

**Actual results**

![image](https://user-images.githubusercontent.com/29706529/225915791-2b7d1ff0-72ff-4b09-9419-e3b70293b130.png)

server_1  | 2023-03-17T13:16:51.144Z | orinmemory://model/1 |  WARN | i.d.l.parse.PendingParse  | Parser for inmemory://model/1: Encountered parse exception io.deephaven.lang.generated.TokenMgrException: Lexical error at line 1, column 2.  Encountered: <EOF> after : ""
server_1  |         at io.deephaven.lang.generated.ChunkerTokenManager.getNextToken(ChunkerTokenManager.java:2377)
server_1  |         at io.deephaven.lang.generated.Chunker.getToken(Chunker.java:4363)
server_1  |         at io.deephaven.lang.generated.Chunker.Document(Chunker.java:156)
server_1  |         at io.deephaven.lang.parse.PendingParse$ParseJob.parse(PendingParse.java:72)
server_1  |         at io.deephaven.lang.parse.PendingParse.parse(PendingParse.java:162)
server_1  |         at java.lang.Thread.run(Thread.java:829)
server_1  |  while parsing \
server_1  | 2023-03-17T13:16:51.966Z | EFAULT.refreshThread |  INFO | .e.u.UpdateGraphProcessor | Minimal Update Graph Processor cycle times: 25.756ms / 17 cycles = 1.515ms/cycle average), safePointTime=0ms
server_1  | 2023-03-17T13:17:16.003Z | EFAULT.refreshThread |  INFO | .e.u.UpdateGraphProcessor | Minimal Update Graph Processor cycle times: 32.279ms / 24 cycles = 1.345ms/cycle average), safePointTime=0ms
server_1  | 2023-03-17T13:17:36.020Z | EFAULT.refreshThread |  INFO | .e.u.UpdateGraphProcessor | Minimal Update Graph Processor cycle times: 25.087ms / 20 cycles = 1.254ms/cycle average), safePointTime=1ms
server_1  | 2023-03-17T13:17:49.233Z | rStateTracker.Driver |  INFO | i.d.e.t.i.u.RuntimeMemory | Jvm Heap: 612,328,784 Free / 868,220,928 Total (4,294,967,296 Max)
server_1  | 2023-03-17T13:18:05.041Z | EFAULT.refreshThread |  INFO | .e.u.UpdateGraphProcessor | Minimal Update Graph Processor cycle times: 25.515ms / 29 cycles = 0.880ms/cycle average), safePointTime=0ms
server_1  | 2023-03-17T13:18:25.146Z | qtp1687087217-28     |  INFO | i.d.s.s.SessionState      | SessionState{aaef9c75-57f4-45c9-a24e-0ae41c691312}: session initialized
server_1  | 2023-03-17T13:18:25.146Z | qtp1687087217-28     |  INFO | i.d.s.s.SessionState      | SessionState{aaef9c75-57f4-45c9-a24e-0ae41c691312}: token initialized to '56702ac3-ebd4-418d-93e3-0ca0ab1f929a' which expires at 2023-03-17T13:23:25.146Z.
server_1  | 2023-03-17T13:18:25.152Z | qtp1687087217-27     |  INFO | i.d.s.s.SessionState      | SessionState{aaef9c75-57f4-45c9-a24e-0ae41c691312}: refreshing listener 26549481
server_1  | 2023-03-17T13:18:25.152Z | qtp1687087217-27     |  INFO | i.d.s.s.SessionState      | SessionState{aaef9c75-57f4-45c9-a24e-0ae41c691312}: run complete for listener 26549481
server_1  | 2023-03-17T13:18:26.552Z | orinmemory://model/1 |  WARN | i.d.l.parse.PendingParse  | Parser for inmemory://model/1: Encountered parse exception io.deephaven.lang.generated.TokenMgrException: Lexical error at line 1, column 2.  Encountered: <EOF> after : ""
server_1  |         at io.deephaven.lang.generated.ChunkerTokenManager.getNextToken(ChunkerTokenManager.java:2377)
server_1  |         at io.deephaven.lang.generated.Chunker.getToken(Chunker.java:4363)
server_1  |         at io.deephaven.lang.generated.Chunker.Document(Chunker.java:156)
server_1  |         at io.deephaven.lang.parse.PendingParse$ParseJob.parse(PendingParse.java:72)
server_1  |         at io.deephaven.lang.parse.PendingParse.parse(PendingParse.java:162)
server_1  |         at java.lang.Thread.run(Thread.java:829)
server_1  |  while parsing \
server_1  | 2023-03-17T13:18:27.557Z | orinmemory://model/1 |  WARN | i.d.l.parse.PendingParse  | Parser for inmemory://model/1: Encountered parse exception io.deephaven.lang.generated.TokenMgrException: Lexical error at line 1, column 3.  Encountered: <EOF> after : "\\a"
server_1  |         at io.deephaven.lang.generated.ChunkerTokenManager.getNextToken(ChunkerTokenManager.java:2377)
server_1  |         at io.deephaven.lang.generated.Chunker.getToken(Chunker.java:4363)
server_1  |         at io.deephaven.lang.generated.Chunker.Document(Chunker.java:156)
server_1  |         at io.deephaven.lang.parse.PendingParse$ParseJob.parse(PendingParse.java:72)
server_1  |         at io.deephaven.lang.parse.PendingParse.parse(PendingParse.java:162)
server_1  |         at java.lang.Thread.run(Thread.java:829)
server_1  |  while parsing \a

**Versions**
 - Deephaven: 0.20.1
 - Browser: Chrome

**Comment by niloc132** [comment]
Closing as dup from inactivity, as this is almost certainly fixed.
