### ISSUE TITLE
Merging of Stream Tables should not generate shifts.

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#3594]
The merging of stream tables is still a stream:
```groovy
import io.deephaven.engine.util.TableTools

t1 = TableTools.timeTableBuilder().period("00:00:01").streamTable(true).build()
t2 = TableTools.timeTableBuilder().period("00:00:00.1").streamTable(true).build()
t3 = TableTools.timeTableBuilder().period("00:00:00.01").streamTable(true).build()
r1 = TableTools.merge(t1, t2, t3)
println(r1.isStream())
```

However, the merge still produces shifts if any of the tables exceed their "max size". These shifts move empty tables (because they are stream tables) and should be omitted. I suspect that the added rows is also not flat as expected for a stream table.

A good work-around is to `flatten()` the merged stream. The result is a stream, and the upstream shifts will disappear as flatten will squish the stream tables.

**Comment by rcaudy** [comment]
Stream tables need not be flat, and we should not change UnionSourceManager to flatten. I do think we should make it so we never communicate shifts that don't actually encompass any current rows.
