### ISSUE TITLE
Support getting meta table in the Python client

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#3620]
Since there is not a gRPC call for that, here is an expensive way to achieve it:

1. bind the table to a non-conflicting name in the global scope
2. run a console script to assign the meta table to the chosen name in 1.
3. open the table through the fetch table call
4. run another console script to set the name to None

Since every table in the Python client already has a Arrow schema associated with it, it is not clear whether what this meta table feature brings to the users is truly needed.

**Comment by nbauernfeind** [comment]
Chip asked to add `getMeta` to the gRPC Table API. This seems like a reasonable request as it is a `Table -> Table` operation. See #2243.

**Comment by jmao-denver** [comment]
closed by #3649
