### ISSUE TITLE
Rename "stream table" to "blink table"

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3694]
It's been determined that "stream table" is a potentially confusing name now that we have begun to call our tables "streaming tables" generally. "Blink table" is the new consensus name. This requires updating the attribute name, accessor names, method names, Kafka ingest code in Java and Python, and ensuring a documentation task is addressed in time for month end.

**Comment by jcferretti** [comment]
There are a couple of places in our docs where "stream tables" are mentioned.  They are never defined in detail or explained, so perhaps it would be a good time to add a page for that.  But at least we need to change the documentation to match the new name.
https://deephaven.io/core/docs/how-to-guides/data-import-export/kafka-stream/#ring-and-stream-tables
https://deephaven.io/core/docs/how-to-guides/data-import-export/kafka-stream/#table-types

It probably makes sense to mention the rename explicitly in the new doc, meaning, to mention that they used to be called stream tables or streaming tables but we decided to rename them.  The reason being, it doesn't make sense to change announcements form the past like this one:

https://deephaven.io/blog/2022/10/07/release-notes-17/#the-c-client-api-now-supports-streaming-table-updates

but it makes sense for somebody from the future to be able to understand the past.

I found these by searching for "stream" and then Ctrl-F table on the results.
https://deephaven.io/search/?q=stream
