### ISSUE TITLE
Implement PartitionedTable, delete TableMap

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#37]
Applies to aggregation, treetables, rollups.

**Comment by mofojed** [comment]
@niloc132 Is this expected for August? Wondering if UI should disable some of the aggregation features that don't work.

**Comment by niloc132** [comment]
No, it is not expected to work by then.

**Comment by rcaudy** [comment]
I'm going to hijack this issue under a new name, since it documents the design that was pursued. We will not actually need a gRPC API for SmartKeys.
Part of #1762
