### ISSUE TITLE
JSAPI should handle the base URL with a trailing slash correctly when creating the websocket URL

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#3703]
**Description**

When connecting a remote worker from a local dev environment, the API is making a call to an incorrect URL with an extra slash:
```
const worker = await ideClient.startWorker(config);
console.log(worker.baseUrl); // url with a trailing slash
// i.e. https://<domain.name>:<port>/worker/e8b01a725fc7e4f385fb5c89efc8a9b364fd793f/
...
const coreClient = new dh.CoreClient(worker.baseUrl, clientOptions);
...
await coreClient.login(loginOptions);
```
throws this error, note the double slash before `arrow.flight`:
```
dh-core.js:19454 WebSocket connection to 'wss://<domain.name>:<port>/worker/e8b01a725fc7e4f385fb5c89efc8a9b364fd793f//arrow.flight.protocol.FlightService/Handshake' failed: 
```

If I strip the trailing slash from the `baseUrl` when creating new `dh.CoreClient`, the wss URL created by the API doesn't have the double slash and the login call succeeds without errors.

**Expected results**
Web socket url created by the API doesn't have the double slash.

**Comment by niloc132** [comment]
It should be noted that the url provided to a grpc client _shouldn't_ have a path component, but this is worth checking - I'll bet this happens even without a path provided.
