### ISSUE TITLE
Support flexible header row placement in CSV files

### ISSUE THREAD

**Issue by lzwaan** [deephaven/deephaven-core#3801]
**Description**
Read CSV skip first line (headers are on the second line) in python not working, while using pandas is working fine

**Steps to reproduce**

**Expected results**
Just like pandas.. but i like to use deephaven's read csv

**Comment by rcaudy** [comment]
@lzwaan Can you update this ticket with the Deephaven call you're making, with arguments, etc? Maybe provide a sample of your input data if appropriate?

**Comment by jmao-denver** [comment]
deephaven.read_csv() doesn't offer an option to specify which row to use as the header row. The skip_row parameter only applies to data rows.

```
df = pandas.read_csv("tests/data/skip-1st-row.csv", header=1)
print(df)
t = read_csv("tests/data/skip-1st-row.csv", skip_rows=1)
print("")
print(t.to_string())
```
```
     a    b    c    d    e
0  435    4  371  937  111
1  860  118  934  444   56

column_102|column_876|column_989|column_240| column_21
----------+----------+----------+----------+----------
       435|         4|       371|       937|       111
       860|       118|       934|       444|        56
```

**Comment by rcaudy** [comment]
If so, we'll need a change (from @corey) to update our CSV library, followed by a change (from @devinrsmith, @kosak, or @jmao-denver to update the Java wrapper in `CsvTools`) and another (from @jmao-denver) to the Python wrapper to use it.

**Comment by jmao-denver** [comment]
> So, @jmao-denver, you're saying we're just missing a `header_row` argument feature?
yes.

**Comment by rcaudy** [comment]
"The algorithm":
```
if (hasHeaderRow) {
    if (header_row < 0) {
        // Complain about invalid input
    }
    skipNLines(header_row);
} else if (header_row != 0) {
    // Complain about other invalid input
}
skipNLines(skip_rows);
```

**Comment by lzwaan** [comment]
Hi ryan,Yes i will update it these weekend.Thanks for your replies!Op 9 mei 2023 om 10:50 heeft Ryan Caudy ***@***.***> het volgende geschreven:﻿
@lzwaan Can you update this ticket with the Deephaven call you're making, with arguments, etc? Maybe provide a sample of your input data if appropriate?

**Comment by lzwaan** [comment]
I'm able to get it read by pandas but then again, the dataframe  datatypes fwhen exporting via kafka avro producer, are very difficult to handle and to create correct avro schema's. **While using deephaven tables with a correct csv headers is working really nice!** Also the automatically create datatypes inside tables are one to one related to avro schema, super cool!

The first line should be skipped, as already mentiod, skip_rows only applies to data rows as you can see in the error message: "_Value: read csv failed : io.deephaven.csv.util.CsvReaderException: Row 2 has too many columns (expected 4)_"

```
Uplink Ethernet Port Performance Statistics,Uplink Ethernet Port Performance Statistics,2023-04-25 02:00:00,45393     
DeviceID,DeviceName,ResourceName,CollectionTime,GranularityPeriod,Received packets for ETH,Total Number of discarded Received Packets,Discarded Yellow Packets,Transmitted packets  for ETH,Transmitted Yellow Octets for ETH,Discarded Green Packets,Transmitted Green Octets for ETH,Total Number of discarded Transimittal Packets,Received Octets for ETH,Transmitted Octets for ETH
167773126,device/0/3/1,2023-04-25 02:00:00,15,,,,,,,,,,
167773126,device/0/3/2,2023-04-25 02:00:00,15,,,,,,,,,,
167773126,device/0/3/3,2023-04-25 02:00:00,15,,,,,,,,,,
7340790,device1/0/8/0,2023-04-25 02:00:00,15,5088651,0,,2097623,,,,0,6806743984,363933086
7340790,device1/0/8/1,2023-04-25 02:00:00,15,6380733,0,,3086106,,,,0,8845357252,730202319
167773108,device2/0/1/0,2023-04-25 02:00:00,15,1751,49,0,1929,0,0,1009825,0,478291,1009825
```

Tried to manualy creating headers and use headless, hoping it will at least skip first line bij headless=True but it doesn't work:
```
header = {  "DeviceID": dht.int_, "DeviceName": dht.string, "ResourceName": dht.string, \
            "CollectionTime": dht.string, "GranularityPeriod": dht.int_, "Received_packets_for_ETH": dht.long, \
            "Total_Number_of_discarded_Received_Packets": dht.int_, "Discarded_Yellow_Packets": dht.int_, "Transmitted_packets_for_ETH": dht.int_, \
            "Transmitted_Yellow_Octets_for_ETH": dht.int_, "Discarded_Green_Packets": dht.int_, "Transmitted_Green_Octets_for_ETH": dht.long, \
            "Total_Number_of_discarded_Transimittal_Packets": dht.int_, "Received_Octets_for_ETH": dht.long, "Transmitted_Octets_for_ETH": dht.long }

source = read_csv('/data/PM_IG80311_15_202304251215_01.csv',header=header, headless=True, skip_rows=1)
```

**Comment by lzwaan** [comment]
It looks like it is working now with the addition of header_row (int): the header row number, all the rows before it will be skipped. I can confirm it is working with DH_VERSION="0.25.2"
