### ISSUE TITLE
Expose SNI Configuration in JettyConfig

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#3837]
As a systems integrator, I want to have the SNI Host Check SSL Parameter exposed so that I have more control over the integrated DHC web server in some environments.  See the todo in JettyBackedGrpcServer.

```
+++ b/server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
@@ -291,9 +291,10 @@ public class JettyBackedGrpcServer implements GrpcServer {
         final HttpConnectionFactory http11 = config.http1OrDefault() ? new HttpConnectionFactory(httpConfig) : null;
         final ServerConnector serverConnector;
         if (config.ssl().isPresent()) {
-            // Consider allowing configuration of sniHostCheck
-            final boolean sniHostCheck = true;
-            httpConfig.addCustomizer(new SecureRequestCustomizer(sniHostCheck));
+            final Boolean sniHostCheck = config.sniHostCheck();
+            if (sniHostCheck != null) {
+                httpConfig.addCustomizer(new SecureRequestCustomizer(sniHostCheck));
+            }
             final HTTP2ServerConnectionFactory h2 = new HTTP2ServerConnectionFactory(httpConfig);
             h2.setRateControlFactory(new RateControl.Factory() {});
```

**Comment by devinrsmith** [comment]
Earlier, I wanted to universally disable it (see https://github.com/deephaven/deephaven-core/pull/2727), but I think it should be really easy to extend based on how our config works now (and as you suggested).

**Comment by cpwright** [comment]
The reason I choose Boolean is that we could default to the current behavior, or turn it off by setting it to false.  I think the null behavior matches the http1 argument of the builder; and allows you to skip the customizer.  I haven't used that setting, but could change this to just a boolean if you would like.
