### ISSUE TITLE
Vector/Formula Aggregation Inconsistency

### ISSUE THREAD

**Issue by stanbrub** [deephaven/deephaven-core#4023]
The behavior of vector aggregations compared to in-line formulas or agg_by aggregations that do the same thing is wildly different in the handling of return types and type overflows.

Here are some observations:
- For integer overflows, no error is thrown to alert the user  (Assume savvy users to avoid performance hit of checks?)
- Summing 2 billion and 1 billion
    - Vector Sum: Returns max signed 32 bit integer value
    - In-line Formula Sum: Returns a negative integer
    - AggBy Sum: Returns a long with the correct value

This could be confusing users.  Fixing the Inline Formula is simple; just cast the operands to long.  But even if there are workarounds for all scenarios, is it not possible to handle overflows consistently?

[vector_function_inconsistency.py.txt](https://github.com/deephaven/deephaven-core/files/11793860/vector_function_inconsistency.py.txt)

**Comment by rcaudy** [comment]
Some of these differences or issues are indeed deliberate. Others are worth discussing.

**Comment by chipkent** [comment]
Contents of the example file:
```python
from deephaven.column import int_col, long_col, double_col, float_col, string_col
from deephaven import agg, new_table

tbl = new_table([
    string_col('group', ['1B', '1B']),
    int_col('values', [1_000_000_000, 2_000_000_000])
])
grouped = tbl.group_by(['group'])
results = grouped.update([
    'int_vector_sum = sum(values)',
    'int_formula_sum = values[0] + values[1]',
    'long_formula_sum = (long)values[0] + values[1]',
    'int_vector_avg = avg(values)',
    'int_formula_avg = (values[0] + values[1]) / 2',
    'long_formula_avg = ((long)values[0] + values[1]) / 2'
])

results2 = tbl.agg_by([
    agg.avg('int_aggby_avg=values'), agg.sum_('int_aggby_sum=values')], 
    ['group'])
```

**Comment by chipkent** [comment]
More ... 
```python
from deephaven.column import int_col, long_col, double_col, float_col, string_col
from deephaven import agg, new_table

tbl = new_table([
    string_col('group', ['1B', '1B']),
    int_col('values', [1_000_000_000, 2_000_000_000])
])
grouped = tbl.group_by(['group'])
results = grouped.update([
    'int_vector_sum = sum(values)',
    'int_formula_sum = values[0] + values[1]',
    'long_formula_sum = (long)values[0] + values[1]',
    'int_vector_avg = avg(values)',
    'int_formula_avg = (values[0] + values[1]) / 2',
    'long_formula_avg = ((long)values[0] + values[1]) / 2'
])

results2 = tbl.agg_by([
    agg.avg('int_aggby_avg=values'), agg.sum_('int_aggby_sum=values')], 
    ['group'])

m = results.meta_table
m2 = results2.meta_table
```

![image](https://github.com/deephaven/deephaven-core/assets/5250374/d7723762-122a-46dc-adf4-9e2a20c7ee67)

**Comment by chipkent** [comment]
Changing to a `long` column results in consistent results:

![image](https://github.com/deephaven/deephaven-core/assets/5250374/c27c6198-e7e3-4555-9a00-74ed5d9faeec)

Going to `short` also results in overflow.

![image](https://github.com/deephaven/deephaven-core/assets/5250374/a43134a0-a378-44f1-8501-6702ce06c4c8)

**Comment by chipkent** [comment]
This illustrates the "weird" `wsum` case:
```python

from deephaven import empty_table
from deephaven import agg, new_table, updateby as uby

t = empty_table(3).update(["X = i", "Y=2*i"])

results = t.group_by().update(["ws = wsum(X,Y)"])

results2 = t.agg_by([agg.weighted_sum("X", "ws=Y")])

m = results.meta_table
m2 = results2.meta_table
```
<img width="487" alt="image" src="https://github.com/deephaven/deephaven-core/assets/5250374/acb2f994-2cff-4e0e-b67a-5ae30e4af8ee">
<img width="619" alt="image" src="https://github.com/deephaven/deephaven-core/assets/5250374/47a806dd-3913-4c21-af20-d4691115562f">

Here the aggregator is using `long` while the query library is using `double`.

**Comment by lbooker42** [comment]
Regarding:
> Widen return type because of overflow to be consistent with other aggs:
> 
> - sum
> - product
> - cumsum
> - cumprod

I encountered the type-preserving behavior in these numeric functions when using them to verify `UpdateBy` operations, but assumed intention and the users would manually widen if overflow was undesirable. I support the idea of default-widening the return types.

Pointing out more inconsistencies, `update_by` is consistent in widening integral primitives to `long` but handles `float` input types variously. Some examples:

- `ema(float)` => `double` 
- `cum_sum(float)` => `float` 
- `cum_prod(float)` => `float` 
- `rolling_sum(float)` => `float` 
- `rolling_prod(float)` => `double`

**Comment by lbooker42** [comment]
> This illustrates the "weird" wsum case:

`agg.weighted_sum` adaptively returns a `long` or `double` based on the input type.  Is that the behavior we'd like in the library functions?
