### ISSUE TITLE
CI Failures due to OOM

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4030]
We are routinely getting random-ish failures in CI caused by OutOfMemoryErrors. For example:
https://github.com/deephaven/deephaven-core/actions/runs/5319076205/jobs/9631170540

This seems to have begun with a recent change to tighten heap provisions to various test components. Perhaps we need to revisit the sizing, and/or change something about the tests themselveS?

**Comment by devinrsmith** [comment]
It might also be somewhat related to gradle (potentially) taking up more memory:

https://github.com/gradle/gradle/issues/23215
