### ISSUE TITLE
Add `RollingFormula` operator to `UpdateBy`

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#4052]
Similar to `AggFormula`, add a `RollingFormula` operator to `UpdateBy` allowing a user to supply a user-defined-function to be applied to a window of values for a column (or list of columns). 

See #4195
See #4194

**Comment by rcaudy** [comment]
This is potentially a rather large optimization, *if* we make the assumption that users are going to read *every* cell value in their vectors via the formula. We can roll through the window of responsive rows, reading all values and supplying direct vectors that wrap a slice of an array.
