### ISSUE TITLE
Share export tickets

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4070]
As a client, it would be nice to be able to share the object behind an export ticket with other clients (ie, "share an export ticket").

To accomplish something like this right now, the only real option is to use the RPC `ConsoleService.BindTableToVariable` to add a *table* to the *global query scope*. This is less than ideal in both that it is limited to tables and it "pollutes" the global query scope.

Depending on implementation, there are still a lot of questions regarding "who is permissioned to get the ticket?" and "are the shared exports listable?".

One implementation might be that a user can mark certain exports as "public", and anybody who has the corresponding export id can get at it through a routable ticket that looks like `u/<user-id>/e/<export-id>`. This might encourage clients to use non-guessable export-ids to as a means of "who is permissioned".

Another implementation might involve adding an RPC equivalent to `io.deephaven.appmode.ApplicationState#setField(java.lang.String, T)` (and potentially the idea of a "dynamic" application, or maybe per-user scoped application).

Right now, a jupyter integration is the driving this feature request - a pydeephaven client creates a table, and a js client wants to display the table, and to share the table, the clients need to wash through the global query scope with a randomly assigned variable name:

```python
from pydeephaven import Session

session = Session()
my_table = session.time_table(period=1000000000)

# Jupyter JS widget, display my_table
DeephavenWidget(my_table)

# DeephavenWidget is essentially calling
# session.bind_table("__t_some_random_name", my_table)
# to ensure the jsclient has a name it can use to reference my_table
```

**Comment by rcaudy** [comment]
We're still working on the spec for this.
