### ISSUE TITLE
Some Types Cause jpy.get_type to Crash

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#4072]
**Description**

We have a type that when called with jpy.get_type causes a hotspot (probably NPE) error in the C++ code.  If we call get_type on one of the parent interfaces, it does not crash.

Details of the classes available in the Deephaven JIRA tracker at DH-15061

The workaround we have is to load the parent class, so this is not a high priority.

**Comment by devinrsmith** [comment]
Filed https://github.com/jpy-consortium/jpy/issues/142 as well.

**Comment by jmao-denver** [comment]
fixed by https://github.com/jpy-consortium/jpy/pull/146
