### ISSUE TITLE
testCoalescingLargeUpdates OutOfMemoryError

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4079]
Nightly CI occasionally fails with:

```
...
> Task :server:testOutOfBand
1 compiler directives added

io.deephaven.server.barrage.BarrageMessageRoundTripTest > testCoalescingLargeUpdates FAILED
    java.lang.OutOfMemoryError at BarrageMessageRoundTripTest.java:1259
...
```

This has been happening for a while. Recent changes to CI should not have changed the amount of memory available to the tests (6GiB) - I suspect that these errors may have been happening for a longer time, but resulted in hard CI crashes due to daemon + test worker heaps exceeding the amount of memory on the machine (which should be less likely to happen now), and these real errors are now actually surfacing.

I'm not sure if there are ultimately leaking tests, or if testCoalescingLargeUpdates is non-deterministic w/ memory usage and needs >6GiB sometimes.

**Comment by rcaudy** [comment]
Happened again today: https://scans.gradle.com/s/idsi25mhps5ki/tests/task/:server:testOutOfBand/details/io.deephaven.server.barrage.BarrageMessageRoundTripTest/testCoalescingLargeUpdates?top-execution=1
