### ISSUE TITLE
No way for UI to specify skipping a column in aggregations

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#4182]
Related to Web UI issue: https://github.com/deephaven/web-client-ui/issues/1355

UI is unable to specify columns to ignore in aggregations, as the default operation is `Sum`, and `Skip` was removed.

**Steps to Reproduce:**
1. Open up http://localhost:10000/jsapi/rollup.html, and set a breakpoint in the `displayTableDetails` function at the top using the developer tools.
2. Refresh the page. When the breakpoint is hit, highlight the `table` variable and assign it to a global variable, then resume operation
3. In the developer console, execute the following snippet:
```
// `temp1` should be the name of your global variable the table is assigned to
var totalsTable = await temp1.getTotalsTable({ operationMap: { I: ['Sum', 'Count'] } })
console.log('totals columns: ', totalsTable.columns.map(c => c.name))
```

**Expected Results:**
3. Only two columns `I__Sum` and `I__Count` should exist in the output, since aggregations were only specified for `I`

**Actual Results:**
3. There are three columns, `['I__Sum', 'K', 'I__Count']`. `K` should not be in the totals output as the column was not specified

There is no `Skip` operation that can be used either, so there does not appear to be a way to _not_ aggregate a specific column.

**Comment by niloc132** [comment]
There is a bug here, but the sample is wrong too - if not set, `TotalsTableConfig.defaultOperation` defaults to `dh.AggregationOperation.SUM`. 

Corrected:
```javascript
 // `temp1` should be the name of your global variable the table is assigned to
var totalsTable = await temp1.getTotalsTable({ operationMap: { I: ['Sum', 'Count'] } , defaultOperation: 'Skip'})
console.log('totals columns: ', totalsTable.columns.map(c => c.name)) 
```
