### ISSUE TITLE
Column with list in parquet file can not be displayed and gives error in ide

### ISSUE THREAD

**Issue by nconsulting** [deephaven/deephaven-core#4270]
The ide can not display parquet columns that have a list in them. You get an error "Unable to open table. Error: Error displaying table: Details Logged w/ID '0e68cb47-1c18-4b07-8bcf-13e29227c7ae'" in the table viewer. I have attached a file that gives this error. You can open it on https://www.parquet-viewer.com/ to see the contents, 3 columns - last column is a list with doubles.

**Versions**
 - Deephaven: 0.26.1
 - OS: Windows 10

[test.zip](https://github.com/deephaven/deephaven-core/files/12261176/test.zip)

**Comment by malhotrashivam** [comment]
There seems to be a bug in the reader code for lists. 
I am working on the fix here #4275

**Comment by malhotrashivam** [comment]
The fix has been merged in main branch and will be released very soon. 
Thanks @nconsulting for raising the issue.
