### ISSUE TITLE
Aggregations on blink tables don't work as expected on in-memory columns

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#4385]
**Description**

According to our [table types conceptual guide](https://deephaven.io/core/docs/conceptual/table-types/#blink):

```
Aggregation operations such as [agg_by](https://deephaven.io/core/docs/reference/table-operations/group-and-aggregate/aggBy/) and [count_by](https://deephaven.io/core/docs/reference/table-operations/group-and-aggregate/countBy/) operate with special semantics on blink tables, allowing the result to aggregate over the entire observed stream of rows from the time the operation is initiated. That means, for example, that a [sum_by](https://deephaven.io/core/docs/reference/table-operations/group-and-aggregate/sumBy/) on a blink table will contain the result sums for each aggregation group over all observed rows since the [sum_by](https://deephaven.io/core/docs/reference/table-operations/group-and-aggregate/sumBy/) was applied, rather than just the sums for the current update cycle. This allows for aggregations over the full history of a stream to be performed with greatly reduced memory costs when compared to the alternative strategy of holding the entirety of the stream as an in-memory table.
```

This is not true for in-memory columns at the moment. It is true for formula columns (I haven't tested memoized columns).

**Steps to reproduce**

Two scripts will exhibit the behavior.

The first works as expected because it uses `view`. However, you shouldn't use a formula column for non-deterministic operations, so this isn't something we should encourage. The `result` table contains a running sum of the `X` column, where the history is captured.

```python
from deephaven import time_table

source = time_table(
    period="PT00:00:01",
    blink_table=True
).view(
    ["X = randomInt(1, 11)"]
)

result = source.sum_by()
```

The second does not work as expected. It uses `select` instead. The aggregation does _not_ capture any history, so the `result` table looks identical to the `source` table.

```python
from deephaven import time_table

source = time_table(
    period="PT00:00:01",
    blink_table=True
).select(
    ["X = randomInt(1, 11)"]
)

result = source.sum_by()
```

**Expected results**

A running sum of the values produced in the source table, regardless of the column type.

**Actual results**

In the case of an in-memory column, the running sum was not captured. It's only the sum of the values _currently_ in the table. In this case, that's a single value per update cycle, so the `result` table looks identical to the `source` table.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.27.1
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jjbrosnan** [comment]
I've also only tested this in the Python API, though I'd expect the same results in the Groovy API. I'll test that now, and add a follow-up comment if that's **not** the case.

**Comment by rcaudy** [comment]
This issue is operating under an incorrect premise. `select` does not currently propagate "blink-ness". See https://github.com/deephaven/deephaven-core/issues/2474 to address this.
