### ISSUE TITLE
JS API getViewportData does not cleanup websocket listeners on table close

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#4410]
**Description**

When using the JS API, if I have a table and do `table.setViewport(0, 1)` followed by `const data = await table.getViewportData()` then the event listeners attached by `setViewport` do not get cleaned up when the table is closed.

**Steps to reproduce**
1. `table.setViewport(0, 1)`
2. `const data = await table.getViewportData()`
3. `table.close()`

**Expected results**

Table and viewport listeners are removed from the multiplexed websocket.

**Actual results**

Table listeners are removed, viewport listeners remain on multiplexed websocket.

**Additional details and attachments**

If I assign a variable to the `setViewport` call I can then close that viewport explicitly.

If I listen on table updated events instead of calling `getViewportData` then the listeners cleanup after themselves.

**Comment by niloc132** [comment]
Other leaks to address:

When a `dh.IdeConnection` instance is closed, server calls will keep running. Several calls need to be closed automatically, including the termination notifications, export notifications, and the logging stream.
