### ISSUE TITLE
Clean up FishUtil

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#4460]
The top-level project FishUtil has a lot of code that appears to be dead:
 * `cpp/` appears to be entirely unused - the MicroTimer java code no longer exists, and the SignalUtils java classes are unused
 * `src/main/java/io/deephaven/util/`
     * `formatters/ISO8601.java` is only used by StatsDriver, and then only to access `ISO8601.serverTimeZone()`, so need not exist any more, could be moved and reduced or just inlined.
     * `signals/` appears entirely unused
     * `threads/ThreadDump.java` is used in `process.ShutdownManagerImpl`, but only the `ThreadDump.threadDump() method ` is used, could be moved/inlined.
     * `OSUtil` is used only by StatsCPUCollector, and then only to see if mac or windows is being used.
     * DateUtil, ExceptionUtil, Mailer, ThreadSafeDateFormat, Validate classes are not used.
     * The `process` package is still used, perhaps should live somewhere else.

**Comment by niloc132** [comment]
Looking at some other downstream work that might need cleanup...

IO:
 * `io.deephaven.io.NioUtil#reduceSelectorGarbage` looks like it was implemented backwards - it is intended to guard against JVMs less than 1.8, but currently prevents using the "reduced garbage" implementation on 11, 17, etc.
 * `io.deephaven.io.CompressedFileUtil` is unused (bz2 impl is provided, but `io.deephaven.engine.util.PathUtil` uses apache commons-compress, etc. PathUtils is in turn used by CsvTools, which then still uses `BzipFileOutputStream` instead of commons-compress...)
 * `streams` - most of this package is only lightly used, or can potentially be replaced by something we depend on
     * `BufferedChannelReader` is unused
     * `MultiFileInputStream` is unused
     * `NullByteBufferSink` is unused
     * `ZipInputStream`/`ZipOutputStream` is unused

Util:
 * `io.deephaven.util.text.ScriptSanitizer` is unused
 * `io.deephaven.util.referencecounting.ProceduralReferenceCounted` is unused
 * `io.deephaven.util.PropertiesUtil` is unused
 * `io.deephaven.util.GrpcLogging` is unused
 * `io.deephaven.util.FindExceptionCause` only `shortCauses` is used
 * `io.deephaven.util.EncodingUtil` is only used by `io.deephaven.util.codec.StringKeyedMapCodec`, which has 6 subclasses, but are never used. Is it possible we want to use this for some parquet reading? They seem to be in the same packages as other classes used by some parquet readers, but don't appear to be directly used. I'm not sure about the rest of the codec package.
 * `io.deephaven.util.BufferUtil` is unused
 * `io.deephaven.util.BridgingLogHandler` is unused
 * `io.deephaven.util.datastructures.RandomAccessDeque` is unused
 * `io.deephaven.util.datastructures.cache.SoftArrayBackedOffsetLookupCache` is unused
 * All of `io.deephaven.util.datastructures.cache.*` is unused
 * All of `io.deephaven.util.datastructures.files.*` is unused

**Comment by rcaudy** [comment]
We should rename `FishUtil` in the process.
