### ISSUE TITLE
Allow `agg.count_` to take a single-element list as input

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#4519]
As a user, I perform aggregations often. I've mistakenly passed a single-element list to `agg.count_` several times, and gotten a somewhat confusing error saying "No matching Java overloads found" as a result. The fix is simple (remove square brackets). However, I often use square brackets out of habit from my other queries. It would be nice if I could do that for agg.count_ as well, just because I do so for many other operations including aggregations.

**Comment by rcaudy** [comment]
I don't really think we should do this. Making the input type a union of string and list effectively "documents" that we might take multiple inputs, and that teaches the user the wrong way to think about count as an aggregation.

**Comment by chipkent** [comment]
I'm also not convinced that we should make this change, but I understand the problem being described.

**Comment by jjbrosnan** [comment]
I'm ok with keeping the usage as-is, but the error message isn't helpful. `No matching Java overloads found` led me to think there was a bug in the underlying Java before I realized my mistake.
