### ISSUE TITLE
Python functions in the query strings create native ungroupable Java arrays directly from numpy arrays 

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#4557]
Users have reported that they want to write general-purpose functions that
1) do not rely on dh-server-specific `dephaven.dtypes`
2) produce arrays that can be efficiently ungrouped.

It seems like this can be accomplished by using the new `numpy.typing` module (https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray) along with `jpy`'s ability to work with raw byte arrays.

I think the following can be made to "just work".  The `npt.NDArray[<type>]` hint should allow the query engine to recognize that the numpy array can be converted by `jpy` to a Java array, which can then automatically infer the proper java primitive array type so that ungrouping works.

```python
from deephaven import empty_table
import numpy as np
import numpy.typing as npt

def func() -> npt.NDArray[np.int32]:
    return np.array([1,2,3], dtype=np.int32)

t = empty_table(10).update(["A = func()"])
m = t.meta_table
t2 = t.ungroup()
```

**Comment by chipkent** [comment]
This should be resolved by #4579, but there are bugs reported in #4631.

**Comment by chipkent** [comment]
Code that should run is:
```python
from deephaven import empty_table
import numpy as np

def func() -> np.ndarray[np.int32]:
    return np.array([1,2,3], dtype=np.int32)

t = empty_table(10).update(["A = func()"])
m = t.meta_table
t2 = t.ungroup()
```

**Comment by chipkent** [comment]
I think this is resolved.

**Comment by jmao-denver** [comment]
@chipkent We might have to support the use of `npt.NDArray` depending on the answers to:
1. is Belmont on Python 3.8 and would not want to upgrade anytime soon?
2. technically the return type can be annotated with Sequence despite that fact that the function returns a np array. Could this be an acceptable workaround for the current limitation?

**Comment by chipkent** [comment]
Currently, the client is on DHE Vermillion, which only supports Python 3.8.  It may be possible for the user to create a virtual environment to run a more recent Python.  In Jan/Feb, the client is expected to upgrade to DHE Vermilion+, which supports Python 3.10.

Annotating with `Sequence` is not a great solution, since:
1. The user wants to create code that works with DH and without DH.  This yields an inaccurate type hint, which is not great for their development in other cases.
2. This would require the user to change code after they upgrade to have correct types.

I suggest testing against 3.8 before deciding that we need to do more work.
