### ISSUE TITLE
Python type inference is not working

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#4569]
Type inference in python with type hints is not working:

```python
from deephaven import time_table

t = time_table("PT1s").update(["X=i%3","Y=i"]).group_by("X")

import numpy as np

def numpy_func(y) -> int:
    return int(np.sum(y))

t2 = t.update("Z=numpy_func(Y)")
```

This returns java.lang.Object for Z.

**Comment by jmao-denver** [comment]
Python function return type inference is only supported by vectorizable calls which have a set of limiting requirements, one of them is that the input parameter can't be a Java vector.
