### ISSUE TITLE
Kafka ingestion of Cap'n Proto data

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#4584]
We should add support for the [Cap'n Proto](https://en.wikipedia.org/wiki/Cap'n_Proto) serialization format in the Kafka ingester.

**Comment by devinrsmith** [comment]
At this time, DHC is not planning to have a native integration for Cap'n Proto. That said, we've got the tooling to allow DHE or 3rd parties to self-service in these regards. https://github.com/deephaven/deephaven-core/pull/4648.

Some research / tooling notes for Cap'n Proto captured here: https://gist.github.com/devinrsmith/74e0a9b230f6bb3975beebed3ec8c253
