### ISSUE TITLE
Performance logging from Java client splits up queries by operation

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#4696]
If you run a query from a client, such as the following, the individual table operations get broken up into separate "queries" in the performance logging (with distinct EvaluationNumbers and separate lines in the query performance log). This makes it impossible to measure the overall performance of a query.

Everything submitted as part of the same query should have the same EvaluationNumber (and just different OperatinNumbers).

```
query = session.scopeTable("LatestSnapshot").where("Key != null").view("ASIACalcSnapTime").maxBy()

result = session.snapshotOf(query)

session.closeTable(result)
```

![image](https://github.com/deephaven/deephaven-core/assets/9516585/2f8f537c-e682-4f78-821f-d27ad6aaff81)

The lines with EvaluationNumbers 256-258 should really all be one evaluation. (Possibly the flatten() too, if it's related to the `snapshotOf()`.)

**Comment by rcaudy** [comment]
We should consider whether we want to add a "serial mode" or "batchier batch" execution strategy. @rbasralian would like us to execute the whole batch as one logical query.

**Comment by nbauernfeind** [comment]
@rbasralian and I discussed this offline as well.

Some low hanging fruit impl-ideas that would enable him to have usable results would be:
1) Add a `batch id` to each `ExportBuilder`/`ExportObject` and populate a new PQL column with this value.
or
2) Introduce a variant of `QueryPerformanceRecorder#startQuery` that takes a `QueryPerformanceNugget` as an argument. We could create one of these for an entire batch, attach to the `ExportBuilder`/`ExportObject` and install during `ExportObject#doWork`. 

Neither of these ideas address the desire to potentially run the operations serially - but would enable us to tackle the two suggestions orthogonally from one another.
