### ISSUE TITLE
java-client Should Support `ColumnHeader` of any Primitive Array Type

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#4721]
Currently the java-client only supports `byte[]` in the category of primitive arrays. This was implemented by a user in #4507.

The server-side, barrage-java-client, and flight-only client, each support arrays of all primitive types. They support arbitrarily nested arrays of primitives (e.g. `int[][][]`).

The java-client should support all primitive array types and nested primitive arrays. See the `UnsupportedOperationException` from here: https://github.com/deephaven/deephaven-core/blob/main/java-client/flight/src/main/java/io/deephaven/client/impl/FieldAdapter.java#L135

**Comment by rbasralian** [comment]
We should also support String arrays, and ideally any other serializable type.

**Comment by devinrsmith** [comment]
Potentially useful to have APIs where `VectorSchemaRoot` is exposed.

**Comment by devinrsmith** [comment]
https://arrow.apache.org/cookbook/java/create.html#array-of-list shows an example of how to create these sorts of structures with Arrow Java

**Comment by devinrsmith** [comment]
https://github.com/apache/arrow/blob/apache-arrow-16.1.0/java/vector/src/test/java/org/apache/arrow/vector/complex/writer/TestComplexWriter.java#L547-L593 shows an example of recursive list writing
