### ISSUE TITLE
`to_j_time_zone()` does not support common aliases and thus fails on some `pd.Timestamp` calls

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#4723]
**Description**

While the [docs](https://deephaven.io/core/pydoc/code/deephaven.time.html#deephaven.time.to_j_time_zone) for `to_j_time_zone()` claim that the method can accept `pd.Timestamp` types and extract their timezone information, this does not always work if the `pd.Timestamp` object (call it `ts`) has a time zone alias via `ts.tzname()` that is not present in our [aliases](https://github.com/deephaven/deephaven-core/blob/main/props/configs/src/main/resources/default_time_zone_aliases.csv).

**Steps to reproduce**

In the IDE, execute the following code:
```
from deephaven.time import to_j_time_zone
import pandas as pd

ts = pd.Timestamp("2022-07-07", tz="America/New_York")
tz = to_j_time_zone(ts)
```

**Expected results**

I would like this to give me a `Java.ZoneId` object equivalent to
```
from deephaven.time import to_j_time_zone
tz = to_j_time_zone("America/New_York")
```

**Actual results**

The code fails with the following error:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value:  : RuntimeError: io.deephaven.time.DateTimeUtils$DateTimeParseException: Cannot parse time zone: EDT
```

**Investigation**

The underlying reason for this has nothing to do with the logic of the [`to_j_time_zone()`](https://github.com/deephaven/deephaven-core/blob/f6dc16c76a3d2a2aea04845a747390b9df5521d2/py/server/deephaven/time.py#L170C8-L170C8) function. In that function, the time zone is retrieved from the pandas object by evaluating `ts.tzname()` at line [201](https://github.com/deephaven/deephaven-core/blob/f6dc16c76a3d2a2aea04845a747390b9df5521d2/py/server/deephaven/time.py#L201). If we evaluate that ourselves in the IDE:
```
import pandas as pd
print(pd.Timestamp("2022-07-07", tz="America/New_York").tzname())
```

we get `EDT`. It's then no surprise that this fails, because this:
```
from deephaven.time import to_j_time_zone
to_j_time_zone("EDT")
```

also fails, with the same error.

The underlying problem is that `ts.tzname()` can return something that isn't included in our [aliases](https://github.com/deephaven/deephaven-core/blob/main/props/configs/src/main/resources/default_time_zone_aliases.csv). Without a careful investigation, it appears that we _claimed_ to support `pd.Timestamp`, and we actually do not. We could solve this problem by adding `EDT` as a time zone alias (must remove the existing alias for some reason?):
```
from deephaven.time import to_j_time_zone, time_zone_alias_rm, time_zone_alias_add
import pandas as pd

ts = pd.Timestamp("2022-07-07", tz="America/New_York")
time_zone_alias_rm("ET")
time_zone_alias_add("EDT", "America/New_York")
tz = to_j_time_zone(ts)
```

but this does not seem like a likely solution a user will stumble on unless they take a bit of careful time to figure out the real source of the error. I would argue that they should not have to do this. As it stands, the appearance is that we cannot do what we claim to be able to do.

We could add a band-aid by sticking something like
```
elif(isinstance(tz, pd.Timestamp)):
    if not tz.tz:
        return _JDateTimeUtils.parseTimeZone(tz.astimezone().tz)

    return _JDateTimeUtils.parseTimeZone(tz.tz)
```

between lines 196 and 197 of [`time.py`](https://github.com/deephaven/deephaven-core/blob/main/py/server/deephaven/time.py), but that does not really solve the problem of needing to support multiple aliases for a time zone. We should at least have aliases for anything that `str(datetime.tzinfo)`, `datetime.datetime.astimezone().tzname()`, `datetime.datetime.tzname()`, `pd.Timestamp.astimezone().tzname()`, or `pd.Timestamp.tzname()` could throw at us. Otherwise, our stuff looks weak and buggy, when the underlying problem is not our logic, but our accepted aliases.

This problem may persist outside of the pandas types. I have not tried.

**Versions**
 - Deephaven: 0.30.0
 - OS: MacOS
 - Browser: Safari

**Comment by alexpeters1208** [comment]
Same issue with `datetime`. Here's an example of the same problem occuring, where I really think this should work:

```
from deephaven.time import to_j_instant, to_j_zdt
import datetime as dt

test1 = to_j_instant(dt.datetime(2022, 7, 7, 5, 24 , 36, 780000, tzinfo=dt.timezone(offset=-dt.timedelta(hours=4), name="NY")))
test2 = to_j_zdt(dt.datetime(2022, 7, 7, 5, 24 , 36, 780000, tzinfo=dt.timezone(offset=-dt.timedelta(hours=4), name="NY")))
```

The first line is successful, while the second fails.

**Comment by chipkent** [comment]
```python
from deephaven.time import to_j_time_zone
import pandas as pd

ts = pd.Timestamp("2022-07-07", tz="America/New_York")
# tz = to_j_time_zone(ts)

print(ts.tzname())

tzi = ts.tzinfo
print(tzi)
print(str(tzi))
```

**Comment by chipkent** [comment]
```python
from deephaven.time import to_j_instant, to_j_zdt
import datetime as datetime

ny_tz = dt.timezone(offset=-dt.timedelta(hours=4), name="NY")
ts = datetime.datetime(2022, 7, 7, 5, 24 , 36, 780000, tzinfo=ny_tz)
# test1 = to_j_instant(some_date)
# test2 = to_j_zdt(some_date)

print(dir(ny_tz))
print(ny_tz.dst)
print(ny_tz.fromutc)
print(ny_tz.max)
print(ny_tz.min)
print(ny_tz.tzname)
print(ny_tz.utc)
print(ny_tz.utcoffset(None))

print(ts.tzname())

tzi = ts.tzinfo
print(tzi)
print(str(tzi))

ts = datetime.datetime(2022, 7, 7, 5, 24 , 36, 780000, tzinfo="America/NewYork")

z = to_j_time_zone("UTC+04:00")
print(z)
```
