### ISSUE TITLE
In Python deephaven.dtypes.array should handle conversions to Instants

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#4728]
In the following code, `datetime_col` seamlessly handles the conversion of various types to column values.  On the other hand, `deephaven.dtypes.array` does not.  `deephaven.dtypes.array` should support the same conversions as `datetime_col`.

```python
from deephaven.column import datetime_col
import deephaven.dtypes as dht
from datetime import datetime

data = [1, datetime.now()]

ok = datetime_col("DateTimes", data)

fail = dht.array(dht.Instant, data)
```

**Comment by jmao-denver** [comment]
The use case is already supported in the latest version.

**Comment by alexpeters1208** [comment]
Is it fair to say that the `to_j_*` set of functions is essentially a set of scalar versions of `dht.array(dht.*, ...)`? As in:

`to_j_instant(data[0])` is the scalar equivalent of `dht.array(dht.Instant, data)`
`to_j_period(data[0])` is the scalar equivalent of `dht.array(dht.Period, data)`
etc.

**Comment by jmao-denver** [comment]
Yes, except that `dht.array` doesn't support `Period`, 'ZonedDatetime` as nicely as `Instant` yet.
