### ISSUE TITLE
tablehandle_test.TestAsOfJoin is a random failer due to racy assertions

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4741]
See `core/go/pkg/client/tablehandle_test.go:372`

This caused a nightly failure:
```
  === RUN   TestAsOfJoin
      tablehandle_test.go:425: record had wrong size
```

There are two things wrong with this test:
1. It is reversing the sense of "as of join" and "reverse as of join", thus providing a poor example for users to learn from
2. It is asserting incorrect things about the relationship between the sizes of independent snapshots

**Comment by rcaudy** [comment]
```
	ttRec, err := tt1.Snapshot(ctx)
	test_tools.CheckError(t, "Snapshot", err)
	defer ttRec.Release()

	normalRec, err := normalTbl.Snapshot(ctx)
	test_tools.CheckError(t, "Snapshot", err)
	defer normalRec.Release()

	reverseRec, err := reverseTbl.Snapshot(ctx)
	test_tools.CheckError(t, "Snapshot", err)
	defer reverseRec.Release()

	if normalRec.NumRows() == 0 || normalRec.NumRows() > ttRec.NumRows() {
		t.Error("record had wrong size")
		return
	}

	if reverseRec.NumRows() == 0 || reverseRec.NumRows() > ttRec.NumRows() {
		t.Error("record had wrong size")
		return
	}
```

If you were to hold a lock that prevented the update graph from progressing while you took all three snapshots, these assertions would be valid. Without that, they are invalid.

**Comment by kosak** [comment]
Fixed by https://github.com/deephaven/deephaven-core/pull/4971
