### ISSUE TITLE
Support kafka publishing into specific partition on row-by-row basis

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4767]
There is not currently an easy way for users to publish a Deephaven table row into a specific Kafka topic partition. Right now, users can set a kafka-specific strategy to choose the correct partition for a record [partitioner.class](https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#partitioner-class), but that's a layer of indirection the user shouldn't typically need to interact with. Alternatively, the user can create N kafka publishers (still setting `partition.class`) and partition their tables accordingly, but that is also less-than-ideal.

It should be relatively easy to add a feature where the user specifies a source column as a "partition" column, and for the record to be published with that partition as appropriate.

We could also consider adding support for a row-by-row topic instead of requiring a fixed topic up front as this could be similarly useful depending on kafka architectures. (Trying to create a different _payload_ depending on topic would be out-of-scope for this issue.)

**Comment by rcaudy** [comment]
If we're embedding a topic column, we should be sure to offer a mechanism for dropping that column, etc.

**Comment by devinrsmith** [comment]
Explicit timestamp column is another potential.
