### ISSUE TITLE
EPIC: "Decent" autocomplete integrations in a Python console session

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#479]
As a user, I want autocomplete in my console Python/Groovy sessions so that I can be more confident in the code I'm writing.

Related to #101

**Comment by pete-petey** [comment]
This will be Python only.  Groovy is a separate EPIC and is secondary.

**Comment by JamesXNelson** [comment]
Just FYI pete, the current parser + autocomplete functionality we're reviving is actually agnostic w.r.t. python v. groovy.  There will be no special work done for groovy, but, atm, there's also no special work being done for python. Our completer understands both w/ the same code.

**Comment by niloc132** [comment]
"True" and "False" and "None" should be suggested matches in python, rather than correcting True to being something else.
