### ISSUE TITLE
Investigate Whether `QueryCompiler` Can Reuse `JavaFileManager` for Server Duration

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#4814]
While working on #4808, I discovered that there is potential to cut formula compile time by ~50% if the `JavaFileManager` is reused across all calls to `QueryCompiler#maybeCreateClassHelper`. See the test, the test results, and accompanying image below.

The concerns / things that need follow up validation:
- Does this prevent us from overriding classes / jars mid-day through the filesystem?
- Does this prevent us from redefining classes in groovy?
- The zulu-17 implementation of `JavaFileManager` is certainly not thread safe. Is it sufficient to implement a delegating implementation that synchronizes all public methods?
- We should have a unit test of some sort that attempts to stress parallel compilation (only the go client caught this via check-ci).

The Test:
- first query shown in the table is the REPL command to construct the tree table and should be ignored.
- then three batches of 10 batch queries of 100 operations that run serially and guarantee the need to compile a single formula.
-- the first batch is run sharing a single, initial, `JavaFileManager` (`JFM`) that was also used in the first query.
-- the second batch disables sharing the `JFM` and instead creates a new one that it closes at the end of the compilation (engine behavior as of #4808).
-- the third batch goes back to sharing a single `JFM` but creates a new instance first.

The first batch of group 1 has an average operation time of 48ms. (shared JFM)
The first batch of group 2 has an average operation time of 113ms. (new JFM per compilation)
The first batch of group 3 has an average operation time of 58ms. (shared JFM, but validating that the JFM is not responsible for the time creep)

Note that over time the simple formula compilation time creeps from 48ms to 69ms over ~3k formulas. This is possibly due to the temp dir that we write formula results into - I couldn't put my finger on the time creep except to eliminate blame on the `JFM`.

![Screenshot 2023-11-10 at 2 36 51 PM](https://github.com/deephaven/deephaven-core/assets/1030443/d78a698c-f1ca-42dc-a5b8-c9f002c113c5)

**Comment by nbauernfeind** [comment]
Future follow-up:
```java
    public static TreeTable queryOperationPerformanceAsTreeTable(
            @NotNull final Table qpl, @NotNull final Table qopl) {
        // TODO (https://github.com/deephaven/deephaven-core/issues/4814): use NULL_INT for ParentOperationNumber and
        //  Depth once we can prevent any compilation or at least reduce multiple usages to a single formula
        Table mergeWithAggKeys = TableTools.merge(
                qpl.updateView(
                        "EvalKey = Long.toString(EvaluationNumber)",
                        "ParentEvalKey = ParentEvaluationNumber == null ? null : (long.toString(ParentEvaluationNumber))",
                        "OperationNumber = NULL_INT",
                        "ParentOperationNumber = OperationNumber",
                        "Depth = OperationNumber",
                        "CallerLine = (String) null",
                        "IsCompilation = NULL_BOOLEAN",
                        "InputSizeLong = NULL_LONG"), 
```

Currently if all three columns were `NULL_INT` we get separate compilation lines for each as the formula includes the destination name in the generated formula. Even better (and maybe this becomes a separate issue) these could probably return a null column (or constant value column) without any compilation at all.

**Comment by rcaudy** [comment]
Next steps:

First, answer these questions:
* Does this prevent us from overriding classes / jars mid-day through the filesystem?
* Does this prevent us from redefining classes in groovy?
If re-use doesn't cause issues with the above, we should at a minimum begin *pooling* re-usable JFMs

Second, answer this question:
* The zulu-17 implementation of JavaFileManager is certainly not thread safe. Is it sufficient to implement a delegating implementation that synchronizes all public methods?
If that approach works, is it better than pooling?
