### ISSUE TITLE
Sufficiently large numbers in long columns aren't displayed properly

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#4818]
**Description**

See steps to reproduce.

**Steps to reproduce**

From the Python server-side API (this has been repro'd in both 0.28.1 and 0.30.0):

```python
from deephaven.column import long_col
from deephaven import new_table

t = new_table([
    long_col("X", [511784170666917894])
])
```

**Expected results**

A one row table with a single column with the specified value.

**Actual results**

A one row table with a single column with the number `511784170666917888`. Copying the cell and pasting it gives the correct value, but it's not displaying in the UI properly.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.28.1, 0.30.0
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by niloc132** [comment]
There is also a bug in the JS API here - the provided dh.NumberFormat tool has a regression in this area. I found it last week as part of getting DHE tests for the JS API running in DHC, but haven't filed/merged it yet.
