### ISSUE TITLE
`UpdateBy` `em` time operators not handling out-of-order timestamps properly

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#4848]
**Description**
The operators for `update_by` `em*_time` expect non-descending timestamps but will treat negative time deltas as valid deltas.  This results in data corruption and invalid results.  

**Steps to reproduce**
Run the following code:
```
from deephaven.updateby import ema_time
from deephaven.plot import Figure
from deephaven import time_table
import random

def random_char() -> str:
    return random.choice(['A', 'B'])

result = time_table("PT1S").update(formulas=["Sym = random_char()", "Numbers = randomInt(0, 100)"]).reverse()

result_w_ema = result.update_by([ema_time("Timestamp", "PT1S", "NumbersEMA = Numbers")], by=["Sym"])

ema_A = result_w_ema.where(["Sym == `A`"])

ema_fig = Figure()
ema_plot = ema_fig\
    .plot_xy(series_name="Numbers", t=ema_A, x="Timestamp", y="Numbers")\
    .plot_xy(series_name="EMA", t=ema_A, x="Timestamp", y="NumbersEMA")\
    .show()
```

**Expected results**

A clear exception explaining the need for ordered timestamps.

**Actual results**

Obviously incorrect data (negative EMA from all positive values).

**Versions**
 - Deephaven: <= 0.31.1

**Comment by rcaudy** [comment]
What's the expected behavior? Exception?

**Comment by lbooker42** [comment]
Yes, we initially threw an exception but that was inexplicably removed... by me...
