### ISSUE TITLE
Something is terribly bad with aggregation hash performance in this test case

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4960]
Trove hashing:
```
io.deephaven.engine.table.impl.QueryTable.DISABLE_PARALLEL_WHERE=true
hash=new gnu.trove.set.hash.TIntHashSet()
long start = System.nanoTime(); t=emptyTable(30_000_000).view("someIntColumn=i%10_000").where("hash.add(someIntColumn)"); long end = System.nanoTime(); println ("Time=" + ((end-start)/1_000_000_000D) + " seconds")
Time=0.190421208 seconds
```

Our hashing:
```
long start = System.nanoTime(); t=emptyTable(30_000_000).view("someIntColumn=i%10_000").countBy("Count", "someIntColumn"); long end = System.nanoTime(); println ("Time=" + ((end-start)/1_000_000_000D) + " seconds")
Time=9.652281667 seconds
```

Just crashing through the data:
```
long start = System.nanoTime(); t=emptyTable(30_000_000).view("someIntColumn=i%10_000").sumBy(); long end = System.nanoTime(); println ("Time=" + ((end-start)/1_000_000_000D) + " seconds")
Time=0.169933084 seconds
```

We should understand why this particular aggregation is so bad, and try to fix it. It's counter-intuitively terrible.

**Comment by rcaudy** [comment]
It doesn't look like our hash function is colliding. We need to profile as a next step.

**Comment by lbooker42** [comment]
I repro'd these findings and profiled the slow hashing call.  Here is the JMC method profiling:
![image](https://github.com/deephaven/deephaven-core/assets/4204632/2ac52e27-a0fc-46e5-831b-4853b1172cca)

Setting `ChunkedOperatorAggregationHelper#HASHED_RUN_FIND` reduced the time from ~9 seconds to 0.3 seconds so the `HashedRunFinder#findRunsHashed` needs further review.  Of note, this sample case is pathological with zero runs in each chunk.
