### ISSUE TITLE
Display Unique Values in Column Statistics

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#5031]
**Description**

When hovering over the Column A, I expect to see a count of "a" and "b":

```
from deephaven import empty_table
et=empty_table(100).update("A=i%2==1?`b`:`a`")

```

Instead I just see the unique count.
![image](https://github.com/deephaven/deephaven-core/assets/29706529/2f31c133-6b28-4ece-b171-ca292a5a9f9a)

But I would expect something like this:
![image](https://github.com/deephaven/deephaven-core/assets/29706529/deead868-d9c3-4362-8bd2-776e487095c2)

**Versions**
 - Deephaven: f4f1d2b8e77e233a41baffb094e1e19259582e47

**Comment by niloc132** [comment]
This is dependent on #188 to get proper deserialization of the values that the server wants to be able to send.
