### ISSUE TITLE
Barrage Client Leaks Memory with Some Index Patterns

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#5035]
**Description**

Produce the following table:
```
sourceTable = timeTable("PT0.001s").tail(1000)
st = new Table[64]
for (int ii = 0; ii < st.length; ++ii) {
    st[ii] = sourceTable
}
m = merge(st)
```

Subscribe to it.  The redirection index in the barrage client table grows because we cycle through the indices; and the SparseArraySource backing it does not know that the block is now null and meaningless.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by rcaudy** [comment]
Looks like this may be a poor choice, unless we check attributes and verify that we have an append-only or flat table.
```
            final WritableRowRedirection rowRedirection =
                    new LongColumnSourceWritableRowRedirection(new LongSparseArraySource());
```
We should probably use a `io.deephaven.engine.table.impl.util.WritableRowRedirectionLockFree` for general workloads.
