### ISSUE TITLE
updateBy: Delta operator uses `getLong()` on un-reinterpreted input source for `Instant` input columns

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#5040]
See https://github.com/deephaven/deephaven-core/issues/5040#issuecomment-1894410191 for a succinct description of the actual issue @abaranec dug into. The table is becoming un-live for valid reasons: an update is failing, due to a bug in the implementation.

**Description**

for the ~given query;

from deephaven.updateby import delta

t1 = db.live_table(ns, tbl).where(["date = today()", "ticker=`SPY`"])
t2 = t1.update_by(ops=[delta(cols=["Duration = publish_time"])], by=["ticker"]).reverse()

we get the following in the (interactive) console (sometimes, but not always?). the t2 table never ticks.
![image](https://github.com/deephaven/deephaven-core/assets/29706529/928aa8f4-2b1b-4ada-a4d1-6cd21336c823)

**Versions**
 - Deephaven: 0.30.4

**Comment by rcaudy** [comment]
Here is an attempt at a core reproducer. I cannot reproduce the reported issue.
```
from deephaven.table_factory import time_table
from deephaven.updateby import delta

tt=time_table("PT00:00:01")
st=tt.update(["Nanos=epochNanos(Timestamp)", "Minutes=(long)(Nanos/60_000_000_000)"])
utr=st.update_by(ops=[delta(cols=["NanosDelta = Nanos"])], by=["Minutes"]).reverse()
```

**Comment by rcaudy** [comment]
Ignore the stack traces above. No reproducer forthcoming for now.
The culprit is this method:
```
    @Override
    public void initializeCumulative(@NotNull final UpdateByOperator.Context context,
                                     final long firstUnmodifiedKey,
                                     final long firstUnmodifiedTimestamp,
                                     @NotNull final RowSet bucketRowSet) {
        Context ctx = (Context) context;
        ctx.reset();
        if (firstUnmodifiedKey != NULL_ROW_KEY) {
            // Retrieve the value from the input column.
            ctx.lastVal = inputSource.getLong(firstUnmodifiedKey);
        } else {
            ctx.lastVal = NULL_LONG;
        }
    }
```
Because the `LongDeltaOperator` is constructed with an un-reinterpreted input source, `getLong()` support is not guaranteed. Probably the operator factory needs to have the reinterpreted input sources in addition to the source table.

**Comment by rcaudy** [comment]
Here is a core-only reproducer with the actual issue:
```
from deephaven.query_library import import_static
from deephaven.execution_context import make_user_exec_ctx
from deephaven.table_factory import time_table
from deephaven.column import Column
from deephaven import dtypes
from deephaven.table import PartitionedTable
from deephaven.updateby import delta

import_static("io.deephaven.engine.util.TableTools")
exec_ctx = make_user_exec_ctx()

with exec_ctx:
    st = time_table("PT00:00:01").update([ \
            "Minutes=(long)(epochNanos(Timestamp)/60_000_000_000)", \
            "TimestampTable=newTable(longCol(`Minutes`, Minutes), instantCol(`Timestamp2`, Timestamp)).updateView(`Timestamp2=Timestamp2+1`)" \
        ]).drop_columns("Timestamp")

pt = PartitionedTable.from_partitioned_table(st, ["Minutes"], False, "TimestampTable", [Column("Minutes", dtypes.long), Column("Timestamp2", dtypes.Instant)], True)
mt = pt.merge()
ut = mt.update_by(ops=[delta(cols=["NanosDelta = Timestamp2"])], by=["Minutes"])
```
