### ISSUE TITLE
System using GMT time for now

### ISSUE THREAD

**Issue by hhashim1** [deephaven/deephaven-core#5090]
The below code produces the date using GMT timezone even though I have set the timezone to my local timezone in the Web UI Panel on the top right. This is in version `0.32.0` I don't think this behavior was present in the previous versions, but I may be wrong. The system needs to use the local timezone and not GMT. Use the below code to test and reproduce the results.

```
from deephaven.time import to_j_instant, to_j_time_zone
from datetime import date, datetime, timedelta

today = to_j_instant((date.today()).strftime("%Y-%m-%d") + "T00:00:00 CT")
yesterday = to_j_instant((date.today() - timedelta(days=1)).strftime("%Y-%m-%d") + "T00:00:00 CT")

print("today =", today)
print("yesterday=", yesterday)
```

**Comment by hhashim1** [comment]
Even though I have set a time zone in the web UI, when I run my processes at night using today's date, they don't run correctly and I have to use yesterday's date. This is because the system is using GMT datetime to evaluate the code. It's an issue when coding/testing in the evening (after 6 pm CST), and the dates need to be changed which isn't much of a problem, but I may forget to revert back to today's date and the next day I am having issues because the dates didn't get set correctly. I hope that makes sense.

**Comment by hhashim1** [comment]
When checking for the timezone, the system produces the results below, which are correct; however, when the system calculates the time, it does not use the set timezone. It uses GMT to calculate the time. The local time was `1:02 pm CST`. However, the system said `19:02` instead.

```print(dh_now())
print(dh_time_zone())
2024-01-31T19:02:02.938345383Z
America/Chicago```

When I check the timezone in Python, it is reported as `UTC`. There needs to be a way to set it to local, and the system keeps it that way. When I run the code below on my local machine, I get my local timezone; however, in Deephaven, I get `UTC`.

```import time
print(time.tzname)
('UTC', 'UTC')```

**Comment by jjbrosnan** [comment]
To set the default timezone used by the Deephaven engine, add the following configuration parameter to you docker-compose file:

```
-Duser.timezone=...
```
