### ISSUE TITLE
Reading a directory in Parquet hangs forever in edge

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#5097]
**Description**

When attempting to read data from a directory via Deephaven's Parquet reader, it hangs forever with the spinning wheel in the table display. Doing the same operation in 0.32.0 works as expected.

**Steps to reproduce**

Build Deephaven Core with example data mounted to `/data/examples`, or just copy the [following directory](https://github.com/deephaven/examples/tree/main/Pems/parquet/pems) into your Deephaven installation at `/data/examples`.

Then, run the following code:

```python
from deephaven.parquet import read

source = read("/data/examples/Pems/parquet/pems")
```

**Expected results**

The code to complete running, rendering a table in the UI.

**Actual results**

The code appears to run fine, but the table never renders in the UI. The "processing" spinning wheel just goes on forever.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: edge (later than 0.32.0)
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by malhotrashivam** [comment]
The bug highlighted in this issue got introduced in this [commit](https://github.com/deephaven/deephaven-core/commit/2e747b4ed055754b365510b386d7bcc13150e9d6) titled `Update web version 0.60.0`.

While debugging, I did find a bug that my change introduced and I have pushed a fix [here](https://github.com/deephaven/deephaven-core/pull/5103). When I apply my fix and drop the above web version upgrade commit, the use case mentioned in the issue gets resolved. But if I apply my fix on top of the web version upgrade commit, the system still hangs. So it looks like there is some issue in the web version upgrade.

@rcaudy who should I tag for the web version issue?

**Comment by malhotrashivam** [comment]
@rcaudy mentioned that the rendering issue is being tracked [here](https://github.com/deephaven/web-client-ui/issues/1763).

```
from deephaven.parquet import read

source = read("/data/examples/Pems/parquet/pems")                 # Hangs as highlighted by JJ
source = read("/data/examples/Pems/parquet/pems").coalesce()      # This works fine
```
