### ISSUE TITLE
diff() function for calculating differences between values within an array

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#5101]
There should be a `diff(Vector)` function that returns a vector of differences between the values.

For example:

`diff(5, 3, 4, 1, 2)`

should return:

`[ NULL_INT, -2, 1, -3, 1 ]`

or possibly skip the obvious null and just return `[ -2, 1, -3, 1 ]`.

It should take a `io.deephaven.api.updateby.BadDataBehavior` as an argument (or have an overload that does, and do whatever we decide is reasonable/safe if you don't specify the arugment).

(This is kind of related to #3413.)

**Comment by chipkent** [comment]
Possibly this should take a difference size.  e.g. `diff(stride, Vector)`.

**Comment by rbasralian** [comment]
As in `diff(2, [ 5, 3, 4, 1, 2 ])` would return `null, null, -1, -2, -2` (or `-1, -2, -2`)?  Sounds reasonable to me...

not directly related, but maybe we should have a `lag()` function too? could be helpful for autocorrelation
