### ISSUE TITLE
Update github gradle action to something well supported

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#5161]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: burrunan/gradle-cache-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

This warning is logged on all builds now, apparently since sept of last year. [The action](https://github.com/burrunan/gradle-cache-action) doesn't appear to be getting new updates.

In the meantime, https://docs.gradle.org/current/userguide/github-actions.html shows that Gradle has released their own setup action, and the plain https://github.com/actions/setup-java action has had support for gradle caching as well for quite some time.

**Comment by devinrsmith** [comment]
Given https://github.com/deephaven/deephaven-core/pull/5086, I think it makes sense to investigate the gradle action tooling around this. https://github.com/gradle/actions

**Comment by devinrsmith** [comment]
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
