### ISSUE TITLE
Native data iteration from python

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#5186]
I'd like a native way to iterate over Table data from python. I think it can be efficient and batching behind the scenes. Feature wise, I think it needs to ability to iterate all the columns implicitly, or just a subset (without the need to create a view).

```python
# iterate over all columns
for x, y, z in my_table:
  ...
  
# iterate over some columns
for foo, bar in my_table.iter(["Foo", "Bar"]):
   ...
```

Maybe the interface would need to be context manager based though? If so, then maybe something like:

```python
with my_table.data() as data:
  for x, y, z in data:
    ...

with my_table.data(["Foo", "Bar"]) as data:
  for foo, bar in data:
    ...
```

I'm not picky about the naming.

As a workaround, I can currently do something like this:

```python
for x, y, z in to_numpy(my_table):
    ...

for foo, bar in to_numpy(my_table, ["Foo", "Bar"]):
    ...
```

but this is an all-at-once approach that is only to be used with "small" tables.

**Comment by devinrsmith** [comment]
Potential code in `deephaven.table_listener._changes_to_numpy`

**Comment by chipkent** [comment]
How would this work with ticking tables?  The iterator could change under you?

**Comment by jjbrosnan** [comment]
It would be pretty awesome to enable the use of `enumerate` with something like this as well.
