### ISSUE TITLE
Parquet should encode RowSets more natively

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#5262]
Right now, we encode and decode `RowSets` using `RowSetCodec`, delegating to `ExternalizableRowSetUtils`. We should consider whether we can replace this with an array-formatted column of longs (following the same strategy for representing individual row keys and row key ranges as we currently employ) and a new `ColumnTypeInfo.SpecialType`.  This might produce comparable compression while allowing the column data to at least make some sense to external tools.

Note that we should still preserve `RowSetCodec` for backwards-compatibility purposes.

**Comment by malhotrashivam** [comment]
Moved to https://deephaven.atlassian.net/browse/DH-18268
