### ISSUE TITLE
Python APIs for `table.where`, `table.update`, ...etc should accept `*args` instead of requiring you to wrap in a list

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#5297]
Currently when using the table APIs, if you want to provide multiple expressions, you need to provide it as a list, e.g.:
```
table.where(["X>5", "X<10"])
```

Ideally, we could just pass it in without having to wrap in a list:
```
table.where("X>5", "X<10")
```
This would match how the APIs are defined/used in Java/Groovy as well.

You should be able to do this without making a breaking change, e.g.
```python
def where(formula: Union[str, Sequence[str]], *args: str):
    result = [formula] if isinstance(formula, str) else formula
    if args is not None:
        result += args
            
    print(f"{len(result)} args are {result}")
```
```
> where("x>5")
- 1 args are ['x>5']
> where("x>5", "x<10")
- 2 args are ['x>5', 'x<10']
> where(["x>5", "x<10"])
- 2 args are ['x>5', 'x<10']
> where(formula=["x>5", "x<10"])
- 2 args are ['x>5', 'x<10']
```

**Comment by rcaudy** [comment]
Consensus amongst @chipkent , @jmao-denver , and myself is that we should not make this change.

Similar APIs have taken the same approach we have, and we think this approach preserves flexibility for future API expansions.
