### ISSUE TITLE
Publish utilities to assist in writing unit tests

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#5341]
Helpful utilities for writing tests, like [DeephavenSessionTestBase](https://github.com/deephaven/deephaven-core/blob/main/java-client/session-dagger/src/test/java/io/deephaven/client/DeephavenSessionTestBase.java), should be in published jars that customers can use.

(They should be documented as well.)

**Comment by devinrsmith** [comment]
Any of the test code that we want to make public will probably need to be "promoted" from a test source to a new subproject with a main source and configured with `io.deephaven.project.ProjectType=JAVA_PUBLIC_TESTING`. This is how `deephaven-base-test-utils`, `deephaven-engine-rowset-test-utils`, `deephaven-engine-test-utils` are constructed. Every transitive project dependency for the new subproject will need to be public (either `JAVA_PUBLIC`, `JAVA_PUBLIC_SHADOW`, `JAVA_PUBLIC_TESTING`, `JAVA_EXTERNAL`, or `BOM_PUBLIC`). Essentially, everything that is currently sourced via something like `testImplementation TestTools.projectDependency(project, "...")` will need to be promoted in a similar fashion.

Tracing `DeephavenSessionTestBase`:

* New subproject for `server` test sources (_may_ be able to migrate to existing `server-test` project and upgrade to `JAVA_PUBLIC_TESTING` from `JAVA_LOCAL`, TBD)
  * New subproject for `engine-context` test sources
    * New subproject for `Base` test sources
  * New subproject for `Util` test sources
    * Potential elevation of `test-configs` to `JAVA_PUBLIC_TESTING`
    
There are likely some gradle massaging that will need to be done along the way, or other issues that pop up along the way that need re-working.

It's worth noting that we don't currently use https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures; I'd say using java text fixtures may be an aspirational long-term goal, but practically, `JAVA_PUBLIC_TESTING` is the fastest way to get this done today.

**Comment by devinrsmith** [comment]
Related to #116
