### ISSUE TITLE
Update GWT to 2.11

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#5350]
We're currently on 2.9, and the latest release is at 2.11.

One issue of note is related to tests for promises, if we wanted to use HtmlUnit: https://github.com/deephaven/deephaven-core/pull/5004
2.10 added support for promises:
> Updated to HtmlUnit 2.55.0 and Jetty 9.4.44. With this newer HtmlUnit build comes support for Promise in unit tests, and the browser strings that can be specified when running tests are “FF”, “Chrome”, “IE” (for IE11), “Edge”, and “Safari”.

Otherwise we need to run those tests using Selenium (similar to our integration tests).

**Comment by niloc132** [comment]
Fixed by https://github.com/deephaven/deephaven-core/pull/5576
