### ISSUE TITLE
Expand the table listener interface to support listening on multiple source tables

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#5366]
@rcaudy thought this might be an useful improvement based on some user questions asked in the community slack workspace.

**Comment by rcaudy** [comment]
So, there's two things to consider:
1. Do we want a `MergedListener` equivalent?
2. Do we want to allow extra dependencies, to ensure that a listener doesn't fire until some other table(s) have been satisfied?

**Comment by rcaudy** [comment]
We have a very clear design for part 2.
We're not sure how part 1 should look from the Python side.
