### ISSUE TITLE
JSAPI returns `undefined` for a `null` value in table data

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#5400]
**Description**

The value retrieved from a table via the JSAPI doesn't match the value shown in the console.

**Steps to reproduce**

- On a DHE VM, run this snippet in a Core+ groovy console:
```
ts = emptyTable(1).update("X=(String)null")
println ts.getColumnSource("X").get(0)
// Prints "null"
```

- Create a Core+ Groovy PQ with the snippet above, save it as `TestPQ`
- Open `https://<vm>/irisapi/table_viewport.html`
- Run this snippet in the browser console:
```
var { default: getObject } = await import('./get_object.js')
async function getValue(queryName, tableName, colName, rowIndex) {
    var q = c.getKnownConfigs().find(q => q.name === queryName)
    var t = await getObject(c, q, tableName)
    console.log('size:', t.size)
    t.setViewport(rowIndex, rowIndex)
    var v = await t.getViewportData()
    var column = t.findColumn(colName)
    console.log('viewport, column:', v, column)
    return v.rows[0].get(column);
}
var value = await getValue('TestPQ', 'ts', 'X', 0)
console.log('value, type:', value, typeof value)
// Prints "value, type: undefined undefined"
```

**Expected results**

Value retrieved via JSAPI matches the value returned by `ts.getColumnSource("X").get(0)` in the Code Studio

**Actual results**

JSAPI returns `undefined` when the actual value in the table is `null`

**Versions**
- Core+:  0.33.3

**Comment by niloc132** [comment]
We may categorize this as a "known issue, not planned", this happens in a few places, and always has done so. 

Will investigate briefly as part of #188.

**Comment by mofojed** [comment]
To test in JSAPI page (e.g. from http://localhost:10000/jsapi/table_basic.html), enter this in the browser console:
```javascript
var dh = (await import('./dh-core.js')).default
var client = new dh.CoreClient(window.location.protocol + "//" + window.location.host);
await client.login({type: 'io.deephaven.authentication.psk.PskAuthenticationHandler', token: 'iris'});
var connection = await client.getAsIdeConnection();
var ide = await connection.startSession("python");
await ide.runCode(`
from deephaven import empty_table

x = empty_table(1).update("X=(String)null")
`)


var x = await connection.getObject({ type: 'Table', name: 'x' })
x.setViewport(0, 0)
var data = await x.getViewportData()
var value = data.get(0).get(x.columns[0])
console.log('Value is', value, ', isUndefined?=', value === undefined)
```

We should expect the value to be `null`, not `undefined`.

**Comment by niloc132** [comment]
PR up is, tested in plain DHC:
 * edit table_viewport.html to instead run this simple script:
 ```python
from deephaven import time_table, empty_table
remoteTable = empty_table(1).update("X=(String)null")
```
 * added a breakpoint in table_viewport.html on line 144, inside the loop:
 https://github.com/deephaven/deephaven-core/blob/77cb7ea547a30b3e401a395edc8ec9212d49f6ac/web/client-api/src/main/java/io/deephaven/web/public/table_viewport.html#L114
* eval'd `rows[i].get(table.columns[j])` in the browser console

When this bug is happening, the result should be `undefined` - after the fix, the expected result instead is `null`.
