### ISSUE TITLE
Server crashes on data replay with assertion lastNotificationStep < updateGraph.clock().currentStep()

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#5422]
**Description**

Server crashes with the following when replaying table data:

```
Server shutdown: Exception while processing UpdateGraph notification

io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 10551, updateGraph.clock().currentStep() == 10551.
```

**Steps to reproduce**

I don't have a reproducer on hand.

**Expected results**

Either the table to fail to replay with an exception, or the table to just stop replaying.

**Actual results**

A server crash.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.33.3
 - OS: OS X
 - Browser: Unsure
 - Docker: Unsure

This is the (image of) the exception the user provided:
![image (21)](https://github.com/deephaven/deephaven-core/assets/5342661/09bb87b3-9136-4e18-a8a7-4cc609afeb1f)

**Comment by rcaudy** [comment]
Added the user's exception screenshot to the description.

This looks like the `ReplayTable` somehow double-notified, where the second notification was an error. This doesn't present like a satisfaction bug causing a downstream listener to double notify.

I cannot find anything in the `ReplayTable.run()` code that would suggest that a double-notify is possible, unless the `Replayer` was started twice.

Without more to go on (e.g. the exception that triggered the notification), it's hard to know what happened here.

**Comment by rcaudy** [comment]
I've merged a PR to try to get more error logging next time.
