### ISSUE TITLE
Parquet Errors Have Too Little Context

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#5429]
As an adminstrator, I want the errors from reading Parquet files to include the file name, so that it is easier to understand why things are broken.

This error being a Requirement failure, without providing any context for which file is broken makes it very difficult to understand the root cause of errors.
![image](https://github.com/deephaven/deephaven-core/assets/29706529/93bc6758-6e15-4065-ba20-f7f2f63ff6e7)

**Comment by rcaudy** [comment]
I think the ask here is to catch and wrap the error at a higher level that can decorate the message with source info.
