### ISSUE TITLE
Arrow ingest handles TimeUnit conversion incorrectly

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#5470]
`io.deephaven.extensions.barrage.chunk.ChunkInputStreamGenerator#extractChunkFromInputStream(io.deephaven.extensions.barrage.util.StreamReaderOptions, int, io.deephaven.chunk.ChunkType, java.lang.Class<?>, java.lang.Class<?>, java.util.Iterator<io.deephaven.extensions.barrage.chunk.ChunkInputStreamGenerator.FieldNodeInfo>, java.util.PrimitiveIterator.OfLong, java.io.DataInput, io.deephaven.chunk.WritableChunk<io.deephaven.chunk.attributes.Values>, int, int)`

Seems to have correct logic for `long`:
```
            case Long:
                if (factor == 1) {
                    return LongChunkInputStreamGenerator.extractChunkFromInputStream(
                            Long.BYTES, options,
                            fieldNodeIter, bufferInfoIter, is, outChunk, outOffset, totalRows);
                }
                return LongChunkInputStreamGenerator.extractChunkFromInputStreamWithConversion(
                        Long.BYTES, options,
                        (long v) -> (v * factor),
                        fieldNodeIter, bufferInfoIter, is, outChunk, outOffset, totalRows);
```
, but not for `Instant`:
```
                if (type == Instant.class) {
                    return FixedWidthChunkInputStreamGenerator.extractChunkFromInputStreamWithTypeConversion(
                            Long.BYTES, options, io -> DateTimeUtils.epochNanosToInstant(io.readLong()),
                            fieldNodeIter, bufferInfoIter, is, outChunk, outOffset, totalRows);
                }
```

**Comment by supernomad** [comment]
fwiw I have a hard requirement to support microsecond resolution timestamps in arrow, which is what caused us to stumble on to this situation. The requirement is unfortunately upstream of us in the BQ storage read API, and lets face it google won't be changing that any time soon heh heh. Just wanted to give some context on what happened here and why this popped up.
