### ISSUE TITLE
CSV Read Fails on dtypes.int32 After Recent int_ Removal

### ISSUE THREAD

**Issue by stanbrub** [deephaven/deephaven-core#5601]
The recent removal of `dtypes.int_` caused an error in a benchmark.  When switching to `dtypes.int32` instead, the benchmark still fails but with a different error. I've attached the stack trace.  

It looks like the CSV read does not support all the scalar dtypes.  I'm looking for a true 32 bit int, not a 64 bit one, for my test.  (Though I'm not sure that's doable from the python side.  Maybe np.int32?)  Exception is raised from `/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/csv.py`.

[csv-read-datatype-exception.txt](https://github.com/user-attachments/files/15792949/csv-read-datatype-exception.txt)

**Comment by devinrsmith** [comment]
`dtypes.int_` was `dtypes.int64` not `dtypes.int32`; try with `dtypes.int64` to see if it works.

**Comment by stanbrub** [comment]
Here's an example of using int32 in the console that fails.
```
from deephaven import dtypes as dht, empty_table
from deephaven.csv import read, write

source = empty_table(10).update(['col1=i'])
write(source, '/data/dtypes.bug.csv')
result = read('/data/dtypes.bug.csv',{'int32':dht.int32})
```
If I read with int64, it works.  With int32, it does not.  With no types specified, the result column is a 32 bit int.

**Comment by devinrsmith** [comment]
I noticed that there is a mis-mapping to parsers in csv.py, but it seems like there is a more fundamental issue (even after fixing the mappings):

```python
from deephaven import read_csv, dtypes

actual = read_csv('primitive_types.csv', {
    'bool_': dtypes.bool_,
    'byte': dtypes.byte,
    'char': dtypes.char,
    'short': dtypes.short,
    'int32': dtypes.int32,
    'long': dtypes.long,
    'float32': dtypes.float32,
    'double': dtypes.double,
})
```

```csv
bool_,byte,char,short,int32,long,float32,double
true,42,a,42,42,42,42.42,42.42
```

The specs look correct:

![image](https://github.com/deephaven/deephaven-core/assets/6764691/c3d79998-048a-4859-be36-1c97b4a103f2)

The results wrong:

![image](https://github.com/deephaven/deephaven-core/assets/6764691/d984b3bf-4ffa-42ef-8203-c1860b80fb47)

May need to file issue in https://github.com/deephaven/deephaven-csv
