### ISSUE TITLE
S3 readahead can lead to extra memory pressure and delays in certain cases

### ISSUE THREAD

**Issue by malhotrashivam** [deephaven/deephaven-core#5649]
Consider the following experiment,
- Parquet file size: 20 GB
- Memory size: 8 GB
- Time to do `select`: 
        - Fragment size = 5 MB, Read ahead = 0      : 35 seconds
        - Fragment size = 5 MB, Read ahead = 32    : 212 seconds
       
This shows that in certain situations, read ahead can actually lead to additional delays and more timeouts.

As part of this issue, we should investigate it further and experiment with some heuristic approach, like, turning off read ahead when we have already used 90% of the memory.

Detected during #5613

**Comment by devinrsmith** [comment]
Some potential ideas would be to develop heuristics around `com.sun.management.GarbageCollectionNotificationInfo` and package it in a common library that others could easily poll. Or, some sort of gauge on how many read ahead requests are created, but unable to be fulfilled later bc GC freed the SoftReference.

**Comment by malhotrashivam** [comment]
Moved to: https://deephaven.atlassian.net/browse/DH-18262
