### ISSUE TITLE
Improve automated testing for Iceberg Java and Python libraries

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#5656]
We support creation of Iceberg catalog adapters from RESTCatalog and AWS Glue Iceberg tables, but testing these interfaces requires complex back-end components to be available.  These methods are being tested manually, but CI testing is desired and should be implemented for all user-facing functions.

**Comment by malhotrashivam** [comment]
Moved to https://deephaven.atlassian.net/browse/DH-18261
