### ISSUE TITLE
Combine multiple formatRowWhere/format_row_where calls

### ISSUE THREAD

**Issue by devonpallison** [deephaven/deephaven-core#5817]
As a user, I want to be able to call formatRowWhere more than once/have a method to pass in more than one condition/color pair so that I can easily color my rows using different conditions. For example:

`from deephaven import empty_table
t = empty_table(10).update(["X = i", "A = `A`"])
t2 = t.format_row_where("X % 2 == 0", "BLUE")
t3 = t2.format_row_where("X % 2 == 1", "GREEN")`

Wanted result: a table where rows alternate between blue and green.
Current result: a table where every other row is green, and the other rows are not formatted.

Possible bonus: apply the formats incrementally, with later calls taking precedent, e.g.

`from deephaven import empty_table
t = empty_table(10).update(["X = i", "A = `A`"])
t2 = t.format_row_where("X % 3 == 0", "BLUE")
t3 = t2.format_row_where("X % 2 == 0", "GREEN")`

Would result in some blue and green rows, with green overriding the blue when the condition is true for both.

**Comment by mofojed** [comment]
We'll incorporate this into ui.table: https://github.com/deephaven/deephaven-plugins/issues/596

**Comment by rcaudy** [comment]
I don't think we want to make further changes to this functionality. I anticipate that ui.table will address formatting use cases.

**Comment by rcaudy** [comment]
Never mind, Mike beat me to the comment.
