### ISSUE TITLE
0.35.1 web UI version incompatible with JS API

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#5825]
Upon upgrading from 0.35.0 to 0.35.1, I was unable to view a partitioned table in the web UI:

```
TypeError: e.partitionedTable.getBaseTable is not a function
```

Can be reproduced with

```python
from deephaven import new_table

x = new_table({
    "Foo": [0, 1, 2, 0, 1, 2],
    "Bar": [4, 5, 6, 7, 8, 9]}
).partition_by(["Foo"])
```

We do not currently have web client UI integration tests on the deephaven-core side; and the cherry-picks to the latest web UI version for the 0.35.1 release depend on JS API changes that will only be present in 0.36.0

**Comment by pete-petey** [comment]
Devin said I can close this.
