### ISSUE TITLE
We need a documented way for contributors to create test cases runnable by CI

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#583]
I have created a few Python/Groovy scripts to test the changes I made to improve how Python/Groovy objects and callables are used in Query Strings. I run them in the Web UI but would like to have a way to add them to the test suite to prevent regression in the future.

**Comment by rcaudy** [comment]
The documented way right now is to write unit tests. Are you asking for automated integration tests? I certainly think we want to add this capability in the long run.

**Comment by rcaudy** [comment]
Conferred with Jianfeng. Dev rel will have a ticket for documenting unit testing best practices.
