### ISSUE TITLE
Embedded Server - Add flag to prevent auto opening of browser

### ISSUE THREAD

**Issue by bmingles** [deephaven/deephaven-core#5838]
When running deephaven via pip, the browser opens automatically when the server is started. It would be nice to have a flag to disable this.

Maybe something like:
```sh
pip install deephaven_server
deephaven server \
  --no-browser \
  --jvm-args "-DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler
```

We probably want to keep the default behavior to still open the browser to avoid this being a breaking change.

Relevant code location:
https://github.com/deephaven/deephaven-core/blob/main/py%2Fembedded-server%2Fdeephaven_server%2Fcli.py#L49

**Comment by mofojed** [comment]
Just listing what a few others do:
- Jupyter has a `--no-browser` flag, might be : https://docs.jupyter.org/en/latest/running.html#how-do-i-start-the-notebook-server-without-opening-a-browser
- Streamlit has a `headless` option: https://docs.streamlit.io/develop/api-reference/configuration/config.toml#server
Which appears to be accessed be adding the `--server.headless` flag.
- Vite has a `--open` flag you can set: https://vitejs.dev/guide/cli

I personally would prefer a `--no-open` or `--no-browser` option similar to Jupyter, but maybe @chipkent has a preference

**Comment by devinrsmith** [comment]
On Linux, we could also detect if the user is running without a graphical desktop. Streamlit specifically mentions this:

```toml
# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or
# (2) we are running in the Streamlit Atom plugin.
headless = false
```

I might prefer to use the jupyter `--no-browser` flag, but it's a mild preference.

**Comment by bmingles** [comment]
I think I like the `--no-browser` option defaulted to `false`
