### ISSUE TITLE
Allow table definition to upgrade column types when reading parquet file

### ISSUE THREAD

**Issue by malhotrashivam** [deephaven/deephaven-core#5870]
Currently, when reading a parquet file, user can specify a table definition, but the main purpose of that is to either skip some columns or to add some new null columns. We do not support modifying a column type, like from short to an int, using table definition.

Now iceberg does not a short [primitive type](https://iceberg.apache.org/spec/#primitive-types). So it will upgrade a `short` to an `int`, and use `int` type in the schema. This leads to failure because our parquet reading code assume no change in types.

```
Caused by: java.lang.IllegalArgumentException: The native type for a Short column is int
	at io.deephaven.parquet.table.pagestore.topage.ToShortPage.create(ToShortPage.java:29)
	at io.deephaven.parquet.table.location.ParquetColumnLocation$LogicalTypeVisitor.visit(ParquetColumnLocation.java:499)
	at org.apache.parquet.schema.LogicalTypeAnnotation$IntLogicalTypeAnnotation.accept(LogicalTypeAnnotation.java:800)
	at io.deephaven.parquet.table.location.ParquetColumnLocation.makeToPage(ParquetColumnLocation.java:364)
	... 30 more
```

As part of this issue, when we pass a TableDefinition to parquet read, it should try to adapt the underlying data to match the definition.

**Comment by devinrsmith** [comment]
At a minimum, we should support the safe implicit "upcasting" of primitive types, the same as java would allow.

As a more complex case, one we may or may not want to solve right now, consider a physical `short[]` (parquet type `LIST<INT(16, true)>`). In iceberg, this wild be represented as iceberg schema `list<int>`. 

So, we _could_ safely upcast from `short[]` -> `int[]` (and similarly for other nested types).

**Comment by devinrsmith** [comment]
Here's a reproducer:

```python
from deephaven import parquet, new_table, dtypes
from deephaven.column import InputColumn

source = new_table([InputColumn("Foo", dtypes.short, input_data=[1, 2, 3])])

parquet.write(source, "/tmp/test.parquet")

foo = parquet.read("/tmp/test.parquet", table_definition={"Foo": dtypes.int32})
```
