### ISSUE TITLE
`help()` hangs indefinitely in the IDE for pip-installed DH

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#5917]
Running `help("jpy")` or something of that sort in the Deephaven IDE hangs forever. The desired text output is actually present in the terminal logs, but the IDE itself does not render the text and becomes unusable. This does not happen with Docker-run DH.
<img width="1728" alt="Screenshot 2024-08-07 at 2 54 07 PM" src="https://github.com/user-attachments/assets/e65292b4-ff4c-4a6f-a517-dbe856df722a">

**Comment by niloc132** [comment]
This is tricky - in this case `help()` is blocking the python program's stdin - if we do the same trick that we use when starting from java, the python terminal won't accept input any more.

See `deephaven_internal.jvm`:
https://github.com/deephaven/deephaven-core/blob/3bd5587310b73c9e81bb8b53a55c96aa2a34db06/py/server/deephaven_internal/jvm/__init__.py#L73-L85

To see this in action, run python and then start the server:
```python
from deephaven_server import Server
Server(...).start()
```

Then run the help command in the web IDE, but switch back to the terminal where you ran the above commands. That terminal is then waiting for input and will correctly accept it there.

**Comment by rcaudy** [comment]
So what do we want to do? Detect if someone uses stdin and blow up?

**Comment by niloc132** [comment]
I'm not sure what we think is best - "fix" this, by "breaking" the python console? Take an exciting/dangerous approach by temporarily replacing (globally! can't do this per thread) the stdin reference above? I don't know how we can safely support both.

What does jupyter do here, if you run an interactive command that should read from stdin?

**Comment by alexpeters1208** [comment]
When running `help("numpy")` from Jupyter (assuming that's a valid example of what you're talking about), it does the same thing we do in Docker - just print the whole thing and don't ask for any input at all.

**Comment by niloc132** [comment]
It looks like doing the same experiment from DH-in-jupyter also results in the expected experience - we're going to close this as not planned until we have a pressing need for this.

For anyone who has a specific case where they need this to work, try adding this to your startup/notebook code:
```python
import os
 os.dup2(os.open("/dev/null", os.O_RDONLY), 0) 
```
