### ISSUE TITLE
Bump to latest arrow release

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#5947]
We are currently on arrow version 13.0.0; the latest is 17.0.0. https://arrow.apache.org/release/

During a quick test to see if 17.0.0 arrow FlightSql JDBC drivers fixed an issue, the server was unable to compile, I think due to flight-grpc version not available. (Note: I _could_ create a new project to test the client in isolation, so bumping arrow versions on the server is not a technical blocker to getting a newer standalone client up... it just takes a bit more work to stand up that client.) Something may need changing wrt https://repo.maven.apache.org/maven2/org/apache/arrow/flight-grpc/; it seems to either have a different release cadence than arrow, or it has changed to a new groupId or name, or is no longer necessary.

Trying 15.0.2 (the last version where arrow flight-grpc was "in-sync") resulted in compiler errors, potentially related to the gRPC version. As such, this issue _may_ be dependent on https://github.com/deephaven/deephaven-core/pull/5299.

**Comment by devinrsmith** [comment]
From the perspective of FlightSQL JDBC testing, it would also be nice to bump to pick up the logging fix https://github.com/apache/arrow/pull/40908

**Comment by nbauernfeind** [comment]
Be sure to ping me to add a commit either to the upgrade PR or a follow up after the upgrade, to finish the ListView support I've added in my barrage type-mapping refactorings (PR not yet uploaded). I have everything except to check for the ArrowTypeID which doesn't exist in our current version.

**Comment by devinrsmith** [comment]
It's also more than a logging fix; it looks like older versions of the FlightSQL JDBC driver treat `executeQuery("SELECT 1")` as an _UPDATE_... which is pretty preposterous, but that seems to have been fixed in newer versions.

**Comment by devinrsmith** [comment]
Fixed as part of #6347
