### ISSUE TITLE
JSAPI duplicates authentication header in Open/Next handshake requests

### ISSUE THREAD

**Issue by abaranec** [deephaven/deephaven-core#5955]
**Description**

When the browser issues an OpenHandshake followed by a NextHandshake for  flight authentication it sends identical authentication headers.  This causes Core+ to reject the Next and fail to establish connections properly.

**Additional details and attachments**

![Screenshot 2024-08-19 at 12 42 32 PM](https://github.com/user-attachments/assets/9414808b-7016-4a73-9c7e-8fe3d18e7b19)
![Screenshot 2024-08-19 at 12 42 23 PM](https://github.com/user-attachments/assets/1b725787-c27d-44c8-b9a5-997f245a5a81)

**Versions**
 - Deephaven: 0.36.0
 - OS: MacOS
 - Browser: Chrome Version 126.0.6478.127 (Official Build) (arm64)

**Comment by niloc132** [comment]
Long term, we could have DHC integration tests that use one-time keys, but that would require custom client and server code and custom test setups to leverage them.

The best fix right now is to stop using Handshake to make the initial auth call - as Handshake is bidi, we need to emulate it with two calls, "open" and "next". We technically only need the "open" call for this to work, but to fully emulate a well behaved flight v2 auth client, we send an empty payload on the Next unary.

It seems like we could disregard auth headers for Next calls.. but Next calls use exports to signal which Open call they are connected to, and exports require a session. Basically, we either need to stop using exports entirely for this purpose or stop using a bidi streaming call for a purpose that only needs a unary.

It would make more sense to behave like other clients and call ConfigService/GetConfigurationConstants, so we get in one step our session created and learn what interval we should refresh at. This also has a hiccup - the TypeScript library we are using for grpc-web does not support Interceptors/middleware/etc, and only provides headers/trailers to the caller in the case where the call fails. So, we need a custom implementation of this gRPC call, which provides headers in the case of successful calls.
