### ISSUE TITLE
`to_pandas` creates an empty dataframe if table is a downstream blink aggregation

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#5957]
When aggregations are applied to blink tables, converting the resulting tables to Pandas dataframes results in empty dataframes.
```
from deephaven import time_table
from deephaven.agg import count_distinct, sum_, last
from deephaven.pandas import to_pandas
import time

t = time_table("PT1s", blink_table=True).update("Val = secondOfDay(Timestamp, 'UTC', false)")

t_unique = t.agg_by(count_distinct("NumUnique=Timestamp"))
t_sum = t.agg_by(sum_("SumVal=Val"))
t_last = t.agg_by(last(["LastTimestamp=Timestamp", "LastVal=Val"]))

time.sleep(5)

df1 = to_pandas(t_unique)
df2 = to_pandas(t_sum)
df3 = to_pandas(t_last)
```

Here, `df1`, `df2`, and `df3` all have the correct schema, but are empty.

If you convert the upstream blink table directly, there is no problem:
```
df4 = to_pandas(t)
```
Here, `df4` is correctly non-empty.

**Comment by rcaudy** [comment]
It seems very unlikely there's a bug here. More likely that there was no data in the blink table yet, and thus none in the aggregation, when to_pandas read a snapshot of it. When you ran it on the raw data, you happened to catch some.

**Comment by rcaudy** [comment]
Note, sleeping in the same script execution as the creating the (initially-empty) time table and instantiating your aggregations is probably the issue. Scripts run under the exclusive lock, nothing can tick during the execution unless you use a condition to release the lock.

**Comment by jmao-denver** [comment]
@alexpeters1208 As @rcaudy mentioned, `time.sleep` isn't going to achieve what you intended. Please replace it with `t.await_update`.  If it works for you as it has for me, please close the ticket. Maybe we need to highlight this common user mistake in the doc somewhere.

**Comment by alexpeters1208** [comment]
Yep, this seems to have the effect that I'm after:
```
from deephaven import time_table
from deephaven.agg import count_distinct, sum_, last
from deephaven.pandas import to_pandas
import time

t = time_table("PT1s", blink_table=True).update("Val = secondOfDay(Timestamp, 'UTC', false)")

t.await_update(5_000)

t_unique = t.agg_by(count_distinct("NumUnique=Timestamp"))
t_sum = t.agg_by(sum_("SumVal=Val"))
t_last = t.agg_by(last(["LastTimestamp=Timestamp", "LastVal=Val"]))

df1 = to_pandas(t_unique)
df2 = to_pandas(t_sum)
df3 = to_pandas(t_last)
```
