### ISSUE TITLE
Configurable maximum allowed size of http requests

### ISSUE THREAD

**Issue by voytektr** [deephaven/deephaven-core#6021]
As an engineer developing system using deephaven, I want configure the maximum allowed size in bytes for the http request line and http request headers so that the deephaven ide can process larger requests.

Currently the limit is set to 8kB. Some users may need to enlarge this limit in order to support large http requests, for example, requests containing larger cookies.

cc: @niloc132

**Comment by niloc132** [comment]
Will fix with #5934, as both are jetty config related. The default will be unchanged (very large headers can offer avenues for DoS attacks), but this ticket will let us configure the limit in bytes that can be supported.
