### ISSUE TITLE
Improve Iceberg CI testing by leveraging standard catalogs

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#6029]
Our Iceberg implementation uses a custom-implemented `Catalog` to perform testing.

Since our implementation is catalog-agnostic, we can likely leverage an Iceberg API catalog provider (such as JDBC + Sqlite) to act as the test catalog. This would reduce maintenance and provide a more accurate testing environment locally and in CI.

**Comment by chipkent** [comment]
This should also allow Python methods to be unit tested.

**Comment by devinrsmith** [comment]
I've used https://github.com/xerial/sqlite-jdbc with success before.
