### ISSUE TITLE
Number formatting not working

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#6120]
**Description**

Looks like number formatting rules aren't working. Likely a side effect from the JS API refactor

**Steps to reproduce**
Run this Python
```py
from deephaven import new_table
from deephaven.column import double_col

t = new_table([double_col("A", [0.5, 0.66, 0.777, 0.888])]).format_columns(
    ["A = Decimal(`0.00%`)"]
)
```

**Expected results**

Column formatted as a percentage

**Actual results**

No formatting applied

**Versions**
 - Deephaven: 0.37.0-SNAPSHOT (edge as of 9/24/24)

**Comment by nbauernfeind** [comment]
I've confirmed it was introduced in #5890.
