### ISSUE TITLE
Iceberg reading with explicit Schema support

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#6124]
I believe we need to offer Iceberg reading support based on a user-specified Schema (likely a Schema that was sourced from some history in the Table, or some subset); in the context where a user is passing in String column renames, the keys of that map are tied to a specific Schema (in this way also, it can internally be converted into a field-id rename, which can be used across column renaming). It may also be important in an enterprise for them to establish and record the specific Schema a table was initially ingested as (for example, they may want to enforce that `db.t("MyNamespace", "MyTable")` produces the same exact output today as it did yesterday). It is not enough to simply record the latest, or even a specific, Snapshot because the schema of the Table may change without a new Snapshot - for example, when a column is renamed, the Table's Schema will be updated, but no new Snapshots will be created.

As a point of convention, it probably makes sense to assume these defaults (in order):

1. If a schema is provided, use that schema
2. If a snapshot is provided, use schema `table.schemas().get(snapshot.schemaId())`
3. Otherwise, use schema `table.schema()`; note, this is _not_ equivalent to `table.schemas().get(table.currentSnapshot().schemaId())` for reasons mentioned above.

**Comment by devinrsmith** [comment]
The `table.schema()` regime by default also allows the current constructors from `io.deephaven.iceberg.layout.IcebergBaseLayout` (and derived) to still be valid; while we should be _okay_ breaking these, we eventually need to get into state where we aren't breaking them.

**Comment by devinrsmith** [comment]
Q: does `PartitionSpec` come into play, and if yes, is it always the case that the schema is equal to `PartitionSpec#schema`?

**Comment by malhotrashivam** [comment]
The same should also be applicable on iceberg writing side.
Discussion here: https://github.com/deephaven/deephaven-core/pull/5989#discussion_r1791065313, https://github.com/deephaven/deephaven-core/pull/5989#discussion_r1791069848, and https://github.com/deephaven/deephaven-core/pull/5989#discussion_r1791071072

**Comment by malhotrashivam** [comment]
Moved to https://deephaven.atlassian.net/browse/DH-18256
