### ISSUE TITLE
jsapi: Web-Client Quick Filter Sees Null Values

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#6138]
This is not a web-client issue, I've confirmed that it was introduced in #5890.

Run this query:
```groovy
t = timeTable("PT1s").update("Timestamp = Timestamp.toString()")
```

Then try to quick filter from the UI on any row after the first two. (which happen to work 🤷)

<img width="470" alt="Screenshot 2024-09-25 at 11 07 02 PM" src="https://github.com/user-attachments/assets/d7d8defb-5ae5-471f-ae96-20386e8a8386">
<img width="384" alt="Screenshot 2024-09-25 at 11 07 07 PM" src="https://github.com/user-attachments/assets/d4dea4fd-81ac-47fb-8137-a2e789706c2c">

**Comment by mofojed** [comment]
Seems to be UI is getting an empty snapshot. Can reproduce with an empty_table, and in the JSAPI page browser console (http://localhost:10000/jsapi/):
```
console.log('Creating connection....')
var dh = (await import('./dh-core.js')).default
var client = new dh.CoreClient(window.location.protocol + "//" + window.location.host);
await client.login({ type: dh.CoreClient.LOGIN_TYPE_ANONYMOUS });
var connection = await client.getAsIdeConnection();
var ide = await connection.startSession('python')
await ide.runCode(`
from deephaven import time_table
t = empty_table(100).update("x=\`\`+i")
`)
var t = await ide.getTable('t')
var subscription = t.setViewport(0, 100, t.columns)
console.log('t.size=', t.size);
var snapshot0 = await subscription.snapshot(dh.RangeSet.ofRange(0,0), t.columns);
console.log('snapshot0.rows=', snapshot0.rows)
var snapshot2 = await subscription.snapshot(dh.RangeSet.ofRange(2,2), t.columns);
console.log('snapshot2.rows=', snapshot2.rows)
```
