### ISSUE TITLE
grpc auth token refresh advice

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#63]
via @kosak 

Avoid giving the client too much freedom on its suggested deadline, but instead say "this is when you should reply" so that the only "default" implementation lives on the server, and can change as we see fit.

Clients can renew more frequently (or less frequently...) if they desire, but this should avoid a particular implementation being copied around client impls without understanding it.

**Comment by nbauernfeind** [comment]
closing as this is irrelevant with the move to flight's auth scheme (which is going to be merged as part of #412)
