### ISSUE TITLE
EPIC: UX of "Application mode" (relates to seeing Dashboards)

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#695]
As a user that wrote a script and can run it as a program, I want to be able to change my UI to see a blank dashboard and be able to pull the named tables from that Deephaven-based program onto the dashboard.

I want to be able to close the browser and easily reopen teh configured dashboard.

Unrelated to saving the workspace....
I want to support people other than me pointing to my server resources and inheriting a blank dashboard in their browser, whereby they could then choose tables (from my program) and create their own layout.  And save theirs for themselves.

**Comment by mofojed** [comment]
Breaking down this problem into a few pieces:
1) Connecting to the server resource - this will require some sort of tunnel or proxy to the resource you want to connect to, and (I think) out of scope for this ticket (though we could links to some instructions).
2) Client needs to be able to get the current tables that are available on the server. Right now with the JS API it only gets the changes after a command is run, but it will need to be able to get the tables when connecting to an existing session. @niloc132 / @nbauernfeind may have some input on how best to achieve this.
3) Need a way to specify "Application Mode" - do we specify a startup script? Or do we just specify another server to connect to and don't worry about how code is ran on the server? How do we specify it - a flag in a docker script, some UI element?
4) The current dashboard layout is already saved in the latest version of the code studio, shouldn't need any extra changes there.

**Comment by mofojed** [comment]
Some notes from our Application Mode meeting (@mofojed , @rcaudy , @nbauernfeind , @niloc132 , @devinrsmith , @dsmmcken ):
- Connecting to a session - it would be connecting to a new session, but within the shared query scope.
- Sorts/filters can be stored as part of the layout
- Startup script is added as an argument when starting the worker (may not allow REPLs). Java, Python, Groovy, or QST something
- Server side will need to add some wiring to list all the objects/widgets that are available within that query scope
- May have explicit exporting for objects that should be exposed
- Seed a layout file with JSON using the existing Web U persistent format. Where to seed? Could use WebDAV storage.
- If no seeded layout file, show empty dashboard, with a button to add "all" objects
- Need some way to export dashboard... save to WebDAV storage?
- Support for multiple dashboards saved?
- Have a boolean flag for if users are allowed to view the source script or not, save/view all dashboard files etc, or a lockdown mode and you are just given one dashboard. 
- -> For first pass, just have one json seeded layout
- Could have it look for a seed script/layout file to determine when to start up in application mode
- If there's an error in the startup script, just log the errors and bail out

To address some points in the previous comment:
1. Documentation will be needed to say how to spin it up, or expose ports, or deploy to AWS and share it
2. Server to add wiring to list existing objects and subscribe the new items (@niloc132 , @nbauernfeind )
3. It's a command line argument, passing in the file. @devinrsmith / @nbauernfeind will probably provide this plumbing
4. We'll need a way for the UI to save a script/layout for serving up in application mode

Action Items:
- @devinrsmith Providing a command line argument to a seed file
- @nbauernfeind Allow the client to retrieve a list of objects available in the current session when connecting to an existing session
- @mofojed figure out how to export dashboard layout

**Comment by dsmmcken** [comment]
Export/Import buttons can go at the bottom of the panels menu for dumping or importing json layouts. Icon is preview stacked with small directional arrow.

![image](https://user-images.githubusercontent.com/1576283/127672526-54d95469-760f-44d2-8684-b9adc461709e.png)

And something like this for the blank state, when no default layout is supplied. A future improvement could have the export button launch a modal if we need to add additional options to the json to support lockdown or optional features, but initially just trigger a .json file download.
![image](https://user-images.githubusercontent.com/1576283/127673458-8c629d23-bae5-4a13-8075-c3283805a47a.png)

Auto-fill should grab all objects and drop them into the dashboard, an group stacks by object type.
