### ISSUE TITLE
Column statistics

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#697]
@niloc132 Do note: Robb made these faster on Enterprise side.  I assume that is irrelevant... just noting it though.  (Perhaps worthy of a chat with him.)

**Comment by mattrunyon** [comment]
To make searching this ticket easier, here is the web-UI error hovering on a table column name.
Error: java.lang.UnsupportedOperationException: getColumnStatistics

**Comment by mofojed** [comment]
@niloc132 is Column Statistic support possible now/is it blocked on anything else?
