### ISSUE TITLE
RESEARCH TASK: Contemplate a more native Python solution than simply "wrapping Java classes"

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#699]
@rcaudy  watching

There is a suggestion that perhaps we need to hand-craft in Python some of the core engine capabilities instead of simply wrapping the Java classes.

Defining "DONE" for this ticket:  Have a meeting with Ryan, Charles, Corey, Pete, Devin, Chip and maybe others where you present your considerations and preferences.

**Comment by jmao-denver** [comment]
### The current Deephaven python package is a mix of thinly wrapping some of the JPY mapped Java classes in Python code (e.g. TableTools.readCsv() )  and direct exposure of JPY mapped Java classes or interfaces (e.g. <lass 'io.deephaven.db.tables.Table'> ). 

```
Pros:
  - less coding work, as long as JPY behaves as expected
  - less documentation, auto-translation of Java Doc to Python Doc has been working well so far

Cons:
  - not pythonic in terms of naming conventions
  - not taking advantage of Python arguments parsing and checking
  - too exposed to the underlying Java code
  - mixing manual written Python code with 'generated/wrapped/mapped' Java code makes the code less readable, the structure less clean
```


### Doing a fully hand-crafted Python wrapper on top of JPY,  on the other hand, means:

```
Pros:
  - a more Pythonic interface and doc/help
  - more meaning built-in help/doc
  - better Exception handling, early input check
  - cleaner code layers

Cons:
  - more dev work on the API
  - some server/engine change is needed
  - if the new API is added instead of replacing the existing one, it could lead to maintenance nightmare
  - if the new API replaces the existing one, a lot of doc/example rewrite will be needed much sooner and people need to get  trained
``` 

### Conclusion:
The benefits of a fully hand-crafted Python API on top of JPY on the server side are quite compelling. But it is a fairly big undertaking. Combined with the fact that we want the future client-side Python API and the server side one mirror each other as much as possible, it makes a lot of sense to work on the client Python API first. It will be brand new and not legacy-burdened. Once it is done, then we can move to the server side and craft a new server Python API by reusing the design and code of the client one as much as we can. This approach would also buy us more time to iron out some of the gaps and problems in the underlying technologies (grp, arrow, barrage, ...) which apply to both client/server and server/server architectures.

**Comment by jmao-denver** [comment]
@devinrsmith @rcaudy @chipkent @pete-petey, this is a very short attempt to have a clear idea of what's a good, realistic approach to beef up DH's Python support for the near future, despite that I don't have a full picture of everything involved and that I certainly lack the historical perspective and relevant user experiences. Your review are both needed and appreciated.

**Comment by devinrsmith** [comment]
There has been a desire in the past to have the "same" apis, so that code could be easily ported between languages; and that documentation and examples would be easily translatable. For example, `left.naturalJoin(right, "Id", "Value")` could be written verbatim in groovy + python. The pythonic way is to do `lowercase_with_underscores` though, so `left.natural_join(right, "Id", "Value")`. I'm not morally opposed to a purpose built python api, one which doesn't strive to have method by method compatibility - it would likely be a good exercise in api layer visibility, and allow us to focus on the important parts of the api. There's definitely some crossover w/ the java-client / QST stuff I'm working on now.

**Comment by jmao-denver** [comment]
@devinrsmith thanks for the background info for the current state of things. will definitely consult on QST/java client when the time comes to do the client Python api.
