### ISSUE TITLE
[Java API] Break up Table API

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#706]
The Table.java API needs to split into two, TableData and TableOperations (to be named?). The TableOperations will drive things that can be done without having a table on-hand (aka QST), while TableData drives data that exists client-side.

EPIC: Java API #257

**Comment by nbauernfeind** [comment]
TableOperations is take care of via #762.

The TableData API remains.

**Comment by rcaudy** [comment]
Devin delivered on `TableOperations`. As of now, I don't think we need a separate `TableData`.
