### ISSUE TITLE
Move format-specific fields out of TableDefinition and ColumnDefinition.

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#713]
Codec and encoding are part of ColumnDefinition; move them out with reasonable defaults and also allow read and write operations to take an additional argument to specify them on a per-column-name basis.

**Comment by rcaudy** [comment]
Part of #294

**Comment by jcferretti** [comment]
Fixed by https://github.com/deephaven/deephaven-core/pull/819
