### ISSUE TITLE
Complete, test JS API reconnects

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#730]
Since replacing the websocket and gwt-rpc serialization with http2/grpc/protobuf, we haven't had an actual server deployed suitable for testing reconnecting a session after some kind of network loss, so the work is incomplete still. Presently we only are testing with the websocket proxy transport (so as to be useful on localhost or in other ssl-less environments, since http2 can't be used in the browser without ssl).

While we're probably interested in websocket proxy reconnects working correctly, it isn't as much of a priority as actual http2 reconnects, so the first step of this task is to get the stack running on a server with ssl and no websockets, then bounce envoy or the network connection to periodically break the streams and make sure that we are able to restore the session, or in cases where the session cannot correctly come back, restore tables which can be re-fetched.

**Comment by devinrsmith** [comment]
My setup is:

crypto -> kafka -> grpc-api.

Restarting just the crypto service container causes the web ui message to display 

```
"Unable to connect: Response closed without grpc-status (Headers only)"
```

a few seconds *after* crypto restarts (and I notice that *new* data *is* coming in to tables for those few seconds). It's followed by messages on the server of the form 

```
ERROR c-nio-worker-ELG-3-1 | i.d.g.a.ArrowFlightUtil   | DoExchangeMarshaller{4e942be2}: unexpected error; force closing subscription: caused by io.grpc.StatusRuntimeException: CANCELLED: client cancelled
```

but, probably harmless according to https://github.com/deephaven/deephaven-core/issues/1205.
