### ISSUE TITLE
Fix DB-test python tests

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#734]
Follow-up to #430

In enterprise as well as in this repo, all junit tests that use python in DB-test are marked `@Ignore`, so they are not run - presumably something is wrong with the test or with the code under test, and should be investigated.

**Comment by pete-petey** [comment]
Back to @niloc132  per 6/16 update meeting.

**Comment by niloc132** [comment]
Back to @jmao-denver https://github.com/deephaven/deephaven-core/pull/881

**Comment by niloc132** [comment]
DB-test is renamed to python-engine-test as of 5c1b52c85ab66a3fb77a0127095453276d024fe2
