### ISSUE TITLE
Establish and advertise minimum required docker version

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#769]
We had a developer run into issues, where their docker engine complained about multistage builds. They were running on Centos 7, which uses a relatively old docker version 1.13.1 (note: docker versions changed from 1.13.x -> 17.x). [Multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/#version-compatibility) were released on for 17.05, so at the very least, we need 17.05 to build. Technically, or practically, we may want to require a newer version.

There may also be docker-compose compatibility we want to advertise. (Note: an old docker-compose won't effect the building of images, just the running.)

**Comment by devinrsmith** [comment]
It would be good to further break this down into requirements for *building* and requirements for *running*.

**Comment by hythloda** [comment]
DO NOT USE:
 Docker Engine Version:      1.12.6
 Docker Engine Version:      1.13.1
 Docker Engine Version:      17.03.0-ce
 Execution failed for task ':deephaven-jpy:buildDockerForRuntime'.

BUILDS BUT DOES NOT RUN:
  Docker Engine Version:           18.09.*
  Docker Engine Version:           19.03.*
  Execution failed for task ':grpc-proxy:buildDocker'.
   Need to change alpine to version 3.12
   `vi grpc-proxy/Dockerfile
`
`   FROM docker.io/library/alpine:3.12
`

DOES NOT RUN:
docker-compose version 1.24.1
`Unsupported config option for services.envoy: 'extends'
`
So far tested runs with:
docker-compose version 1.29.2
more docker-compose tests later

**Comment by chipkent** [comment]
Resolved in #1207
