### ISSUE TITLE
Write a prototype for a Python API that can deliver data to a Python client from Deephaven

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#776]
Pete's comments about this ticket -- these are not a mandate:

- The goal is to focus on this one aspect of the Python API -- accessing Deephaven data from a Python client.  (Yes, arguably, at some point it should be part of a larger, more multi-functional, "proper" Python client, but for this exercise let's ignore that.

- The word "prototype" for this ticket is appropriate.  We want to build something that simply convinces ourselves that the approach taken is the right one.

-- The data accessible to the Python client must be deephaven tables in static form, snapshots, and updates.  

-- Per Jianfeng, it is likely wise to first explore whether Python-GRPC API and PyArrow (or Py-Arrow-FLight + Barrage) can directly provide what the user wants (without involving ourselves in wrapping C++).

@niloc132  @devinrsmith  @nbauernfeind  will all be helpful I am sure.  (Ryan too, but not having him watch it.)

**Comment by jmao-denver** [comment]
closed by #1094
