### ISSUE TITLE
Reduce log noise from autocomplete

### ISSUE THREAD

**Issue by JamesXNelson** [deephaven/deephaven-core#796]
The recently merged autocomplete winds up spamming the logs with piles of uninteresting messages about parsing documents for completion. The log level needs to be dropped to trace(), and the logger itself should be specific to the parser, rather than passing in the logger from the rpc endpoint.

**Comment by nbauernfeind** [comment]
Colin and I agree the current behavior around auto-complete logging resolves this issue.
