### ISSUE TITLE
Teach autocomplete parser to understand python class and method structure.

### ISSUE THREAD

**Issue by JamesXNelson** [deephaven/deephaven-core#827]
The old parser was able to choke down classes and methods, but resulted in treating large swaths of valid code as "junk tokens", because we would just gobble up all the tokens and stick them as "junk strings" to the end of last-understood-nodes.

By giving the parser knowledge of how a class + function looks, it can create proper structured objects AND avoid losing it's ability to parse method bodies, or code that comes after a class definition.

Note: fixing python also requires fixing groovy, as they require the same parser, and share keywords like `class` and `def`.

This is a subissue of #101

**Comment by mofojed** [comment]
I believe this was completed with https://github.com/deephaven/deephaven-core/pull/3114
