### ISSUE TITLE
Barrage repo needs to rename flight.proto to Flight.proto for better interop with upstream arrow

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#833]
Downstream projects trying to use vanilla arrow with some of our .proto files are encountering problems with this difference, the `import` statements are case sensitive. 

https://github.com/deephaven/barrage/blob/main/format/flight.proto
https://github.com/apache/arrow/blob/master/format/Flight.proto

**Comment by niloc132** [comment]
We also need to discuss collisions for clients that want DH and arrow-flight code, this affects both java and c++ so far.

ping @kosak

**Comment by nbauernfeind** [comment]
This was performed in barrage 0.2 release. Other work was done to not inter-depend on the Flight.proto file. We expect the only user of this file to now be the jsapi. Non java API languages should definitely try to use proper Flight. Java flight also works, but I suspect java users will want the query engine anyways.
