### ISSUE TITLE
Core JavaDocs does not have a searchable SmartKey entry

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#837]
The Deephaven Core JavaDocs should have a SmartKey entry that you can find by using the search bar in the top right.

Right now, there is no entry that is searchable.  There is documentation (how-to and reference docs for table partitioning) that could use the JavaDoc as a link.

Attached is an image of what does show up if you search for SmartKey in the Deephaven Core JavaDocs.

<img width="558" alt="SmartKey_CoreJavaDoc_SearchResults" src="https://user-images.githubusercontent.com/84038776/125335827-3eef9980-e30a-11eb-8e45-8b7adbe3c189.png">

**Comment by chipkent** [comment]
Possibly the javadocs are just old and need regenerating.
