### ISSUE TITLE
not equals match filter

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-core#840]
Not equals (`!=`) is not optimized as a match filter in Deephaven, but it probably should be.

**Comment by rcaudy** [comment]
Wow, good catch. As a workaround, you can use "not in" to get the same semantics, but we should fix this (or port it from DHE if it's fixed there).

**Comment by rcaudy** [comment]
We should do this for `isNull(ColumnName)` filters, too.

**Comment by niloc132** [comment]
Do note that the web UI will automatically use a match filter when you specify a "not equals" filter.
