### ISSUE TITLE
"Running..." in IDE disappears before computation is complete

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#842]
**Description**

In the Deephaven IDE, it seems that computations that take a particularly long time (~ 5 mins) will appear to complete before the code is actually done running because the "Running..." textbox disappears. When these computations look like they're done, a simple `print(3)` can take a really long time, which I can only assume means the previous computation is still happening.

**Steps to reproduce**

Execute the following code in the Deephaven IDE:

`import time`
`time.sleep(500)`

Then, when the "Running..." box goes away, execute:

`print(3)`

**Expected results**

I expect the "Running..." box to persist until 500 seconds have elapsed, and then "3" being printed to the console immediately after.

**Actual results**

The "Running..." box disappears around the 300 second mark. Printing "3" to the console after that will take about 200 more seconds.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.1.7
 - OS: macOS Big Sur 11.4
 - Browser: Tested on both Chrome 91.0.4472.114 and Safari 14.1.1.
 - Docker: Desktop 3.3.3

**Comment by mofojed** [comment]
The UI is receiving an error back: `Error: Response closed without headers`

The `timeout: 0s` is set in envoy.yaml, maybe there's another timeout we need to set?

**Comment by nbauernfeind** [comment]
I've verified that this has been fixed.
