### ISSUE TITLE
Provide a command line argument to a script to seed the application

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#853]
As a developer, I want to be able to specify a script on the command line to seed the session so that I can share my work easily with others.

Related to #695

**Comment by rcaudy** [comment]
"script" means:
1. python
2. groovy
3. Java
4. QST
5. ?

We also need to be able to specify if the resulting session is "open" or "locked down", meaning whether we allow users to save dashboards, access the filesystem, etc.

**Comment by nbauernfeind** [comment]
To be clear, session in this context means jvm / worker / dhc-core instance -- and does not refer to an API session.

**Comment by mofojed** [comment]
We'll probably have a folder that will contain a bunch of files, and run all the files.
Should also be able to have seed files with or without Application Mode (to just seed your environment)
