### ISSUE TITLE
Provide list of objects in the existing session when a client connects

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#854]
As a client UI, I want a list of objects that are available on the server so that I can open tables/plots that may have been created before I connected.

Relates to #695

**Comment by rcaudy** [comment]
This should default to the query scope, but allow application developers to specify a subset of tables and plots to make available for dashboard users.

**Comment by mofojed** [comment]
@nbauernfeind What's the progress on this? I see it was moved to In Progress 21 days ago. I need this feature to complete my Application mode changes, anything I can do to help?
