### ISSUE TITLE
Create appropriate standards around TODO

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#87]
When is it applicable? How should it be done? Should they link to a ticket (just a number, or a url)? If a corresponding TODO issue is closed, should the TODO be deleted? etc.

**Comment by mofojed** [comment]
The GitHub plugin for VSCode also has "(Create Issue Triggers)[https://code.visualstudio.com/docs/editor/github#_creating-issues]" that allow for quick creation of an issue when typing "TODO", and it automatically adds the issue number in your code, and adds a link to that code in the ticket. An example ticket: https://github.com/deephaven/web-client-ui/issues/45

**Comment by devinrsmith** [comment]
I'm confused - this is only for VSCode though, yeah? Not for how we should reference GH issues in code?

**Comment by mofojed** [comment]
VSCode creates the issue in GitHub. If you're not using the plugin and the ticket does not already exist, then create the ticket using the normal New Issue flow, and reference it with the #
