### ISSUE TITLE
DoPut usability improvements

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#892]
* Presently, the `KeyValue` customMetadata with key "deephaven:type" is always required to be the java type that the column will be on the server - this should be optional for simple cases like byte/int/double/long/String/etc. Complex cases like reinterpreted byte-boolean and DBDateTime or any VarBinary will need always need to have the type identifier included.
* Consider other examples of extension types, and decide if we should use that instead of or in addition to "deephaven:type" https://arrow.apache.org/docs/format/Columnar.html#extension-types
* Support arrow Bool fields instead of just interpreting bytes in the deephaven-specific way. See #43 for more work on this, but this bullet point is only meant to cover the case of making DoPut very accessible

**Comment by niloc132** [comment]
| deephaven:type | Arrow type | Notes |
| ----------- | ---------- | ---------- |
| int | Int 32 signed |
| long | Int 62 signed | 
| short | Int 16 signed |
| char | Int 16 unsigned |
| byte | Int 8 signed |
| boolean | | Not yet supported, please see java.lang.Boolean 
| java.lang.Boolean | Int 8 signed
| double | FloatingPoint DOUBLE |
| float | FloatingPoint SINGLE |
| java.lang.String | UTF8 |
| java.math.BigDecimal | Binary | Not yet supported
| java.math.BigInteger | Binary | Not yet supported
| io.deephaven.db.tables.utils.DBDateTime |
| java.time.LocalDate | FixedSizeBinary 6 | Not yet supported
| java.time.LocalTime | FixedSizeBinary 7 | Not yet supported

**Comment by devinrsmith** [comment]
I'm interested in having supported translation (w/o DH metadata) for the simple types. 

For reference, here is the server side I'm getting when trying to send and 1 column int table from a naive client:
```
rpc-api_1    | 2021-09-29T21:36:48.520Z | c-nio-worker-ELG-3-2 | ERROR | i.d.g.a.ArrowFlightUtil   | io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Schema did not include `deephaven:type` metadata                                           
grpc-api_1    |         at io.grpc.Status.asRuntimeException(Status.java:535)                                                                                                                                                                      
grpc-api_1    |         at io.grpc.protobuf.StatusProto.toStatusRuntimeException(StatusProto.java:52)                                                                                                                                              
grpc-api_1    |         at io.deephaven.grpc_api.util.Exceptions.statusRuntimeException(Exceptions.java:15)                                                                                                                                        
grpc-api_1    |         at io.deephaven.grpc_api.util.GrpcUtil.statusRuntimeException(GrpcUtil.java:91)                                                                                                                                            
grpc-api_1    |         at io.deephaven.grpc_api.barrage.util.BarrageSchemaUtil.schemaToTableDefinition(BarrageSchemaUtil.java:228)                                                                                                                
grpc-api_1    |         at io.deephaven.grpc_api.barrage.util.BarrageSchemaUtil.schemaToTableDefinition(BarrageSchemaUtil.java:186)                                                                                                                
grpc-api_1    |         at io.deephaven.grpc_api.arrow.ArrowFlightUtil$DoPutObserver.parseSchema(ArrowFlightUtil.java:335)                                                                                                                         
grpc-api_1    |         at io.deephaven.grpc_api.arrow.ArrowFlightUtil$DoPutObserver.lambda$onNext$2(ArrowFlightUtil.java:206)                                                                                                                     
grpc-api_1    |         at io.deephaven.grpc_api.util.GrpcUtil.rpcWrapper(GrpcUtil.java:33)                                                                                                                                                        
grpc-api_1    |         at io.deephaven.grpc_api.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:182)                                                                                                                              
grpc-api_1    |         at io.deephaven.grpc_api.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:149)                                     
```
