### ISSUE TITLE
Consolidate NULL_X paths

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#895]
QST introduced its own constants for checking null and adapting boxed/unboxed primitives.

We should consolidate this between QueryConstants; likely abstracting QueryConstants to QST or its own common layer.

**Comment by rcaudy** [comment]
I think the "right" answer here is just to move `QueryConstants` down to a module that QST can depend on. I see no reason for QST's `Util` class to be the home for these. We should move `BooleanUtils` and `TypeUtils.(un)box` down, too.
