### ISSUE TITLE
Parquet: Support predicate pushdown using column chunk statistics, dictionaries, etc

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#968]
We should add an interface to `ColumnSource` like:
```
    /**
     * Result of a {@link #prefilter(Index, SelectFilter)}.
     */
    final class PrefilteringResult implements SafeCloseable {

        /**
         * The index of keys that are included in the filter and do not need further filtering.
         */
        public final ReadOnlyIndex included;
        /**
         * The index of keys that <em>may</em> be included in the filter and need further filtering.
         */
        public final ReadOnlyIndex possible;

        public PrefilteringResult(@NotNull final Index included, @NotNull final Index possible) {
            this.included = included;
            this.possible = possible;
        }

        public void close() {
            included.close();
            possible.close();
        }
    }

    /**
     * Perform optional coarse filtering of this ColumnSource for all rows included in {@code sourceIndex}.
     *
     * @param sourceIndex The {@link Index} to consider
     * @param filter       The {@link SelectFilter} filter to apply
     * @return A {@link PrefilteringResult} to apply, or {@code null} if the entire {@code sourceIndex} should be treated
     * as possible
     */
    default PrefilteringResult prefilter(@NotNull final Index sourceIndex, @NotNull final SelectFilter filter) {
        return null;
    }
```

Implementation notes:
* This should then be integrated into `QueryTable.where(...)`, and supported by `RegionedColumnSource` and `ColumnRegion` implementations.
* We can follow the same iterator advance-oriented recursive pattern as in the implementation of `SymbolTableSource` found in `RegionedColumnSourceObjectWithDictionary`.

Design notes:
* There may be buggy statistics in some Parquet files, and so anything we do needs to be optionally disabled via `ParquetInstructions`. In particular, `String` statistics might be bad in many files, and their use should be enabled separately.
* Also note that dictionary-based filtering only applies to dictionary-encoded pages within a column chunk, and that plain pages must be examined separately.
* Look into column indices and bloom filters as well.

**Comment by malhotrashivam** [comment]
Moved to https://deephaven.atlassian.net/browse/DH-18272
