### ISSUE TITLE
Throwing IllegalStateException from inner code (eg, parquet reading) can leave the worker in a zombie state.

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#981]
This may have been done/fixed already; the idea is that we need a consistent try/catch strategy in the outer worker loop to ensure we either bail hard, or continue processing, no zombie state.

**Comment by jcferretti** [comment]
This is my suggestion for a recipe to clean up our understanding on this:

Hack two methods that are directly callable from the web UI.  Say, ParquetTools.readTable and ParquetTools.writeTable.  Modify them temporarily to throw right when they are called.   Make one throw IllegalArgumentException.  Make the other throw IllegalStateException.   Check what happens after each, and confirm what happens is what we want to happen, and document in this ticket what that is and close it if it is what we want.

As I mentioned in the description, this may be fixed already.  Or the instance when I saw this may have been a combination with something else (like OOM or weird internal parquet library state that I didn't notice).  My recollection is that on a parquet call, when the engine internals hit an IllegalStateException thrown on some parquet assumption, the worker was left in an unusable state (couldn't make a subsequent python call)

**Comment by rcaudy** [comment]
I don't need to hack anything. I can just run `throw new IllegalStateException()` in a groovy console. The worker logs the error and life proceeds as normal.

**Comment by rcaudy** [comment]
Nate wonders if the issue was auto-complete filling up the request queue for the serial executor at the worker, in which case this ticket is probably a red-herring.

**Comment by rcaudy** [comment]
I think it might be the case also that this is more of a "remembered" issue ( as you noted @jcferretti). Closing for now until we have a more recent and reproducible report.
