### ISSUE TITLE
TableService aggregation coverage

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#991]
Currently missing:
* weighted sum
* count distinct
* distinct
* unique
* sortedFirst
* sortedLast
* percentile/median field averageMedian

**Comment by rcaudy** [comment]
I think we are also missing formula.
Additionally, we need shorthand builders to aggregate all columns, e.g. `sumBy()` implies `AggSum` for all columns.

**Comment by rcaudy** [comment]
We're also missing some fancy stuff, like specifying the no-key and non-unique-value sentinels in AggUnique.

**Comment by rcaudy** [comment]
Once we close gaps here, we may want to consider follow-on tickets; `ClientSupport` and other modules are currently working against engine aggregations, not table-api aggregations.

**Comment by rcaudy** [comment]
Discussed with @devinrsmith . We need an easy syntax to specify an agg that implicitly applies to all non-key columns.
Also, I have relaxed Aggregation's static factory methods to return Aggregation instead of Multi... this seems worse, but it happens because Multi wants 2+ aggs. I think we might be making worse by insisting on purity here.

**Comment by rcaudy** [comment]
`Multi` needs more validation to ensure that all members are "compatible" and will map to a single `AggregationSpec` on the engine side. For now, I've made the `builder()` method package-private, and we build these are self with the static factories in `Aggregation`. Maybe we need a "key" for each agg, and we can validate that the aggs going into a multi are mutually compatible. This will make the check in multi easy, and also improve the code in the optimizer.

**Comment by devinrsmith** [comment]
This *really* is just about the gRPC side. I'll create a new ticket about the API side.

**Comment by rcaudy** [comment]
Sorry for polluting this one with all the API considerations...
